"""Curated voice STT synonyms for the multi-trade lexicon.

build_voice_lexicon.py emits voice_normalizer's canonicalization map from
this table. Each key is a spoken/typed form that STT reliably mangles or a
trade slang word; each value is the FAMILY canonical term that must exist in
app/seeds/lexicon/*. The generator validates every target.

Deliberately NOT included: plain descriptive product phrases the static
construction dictionary already owns ("water heater", "sheetrock",
"cement board" -> dictionary canonicals) and ambiguous single words
("pipe", "wire", "furnace", "kohler").
"""
VOICE_SYNONYMS = {
    # --- Plumbing ---------------------------------------------------------
    "silcock": "Hose Bibb",
    "sillcock": "Hose Bibb",
    "sylcock": "Hose Bibb",
    "sill cock": "Hose Bibb",
    "hose spigot": "Hose Bibb",
    "outdoor faucet": "Hose Bibb",
    "outdoor tap": "Hose Bibb",
    "spigot": "Hose Bibb",
    "p trap": "P-Trap",
    "tp valve": "T&P Relief Valve",
    "t and p valve": "T&P Relief Valve",
    "t&p valve": "T&P Relief Valve",
    "sump": "Sump Pump",
    "tankless": "Tankless Water Heater",
    "on demand water heater": "Tankless Water Heater",
    "uponor": "Uponor PEX",
    "wirsbo": "Uponor PEX",
    "nibco": "NIBCO Fittings",
    "viega": "Viega PEX",
    "zurn": "Zurn Drainage",
    "watts": "Watts Valves",
    "taco": "Taco Pumps",
    "grundfos": "Grundfos Pump",
    "rinnai": "Rinnai Tankless",
    "navien": "Navien Tankless",
    "fluidmaster": "Fluidmaster Toilet Parts",
    "eastman": "Eastman Supply Lines",
    "toto": "TOTO Toilet",
    "moen": "Moen Faucet",
    "delta faucet": "Delta Faucet",
    "quickrete": "Quikrete Mix",
    "sakrete": "Sakrete Mix",
    "sackrete": "Sakrete Mix",
    # --- Electrical ---------------------------------------------------------
    "thhn": "THHN Wire",
    "emt": "EMT Conduit",
    "greenfield": "Flexible Metal Conduit",
    "mc cable": "MC Cable",
    "ser cable": "Service Entrance Cable",
    "cat6": "Cat6 Ethernet Cable",
    "rg6": "Coaxial Cable RG6",
    "wago": "Wago Connector",
    "marrette": "Wire Nuts",
    "wire nut": "Wire Nuts",
    "pigtail": "Pigtail Wire",
    "subpanel": "Sub Panel",
    "heat trace": "Heat Trace Cable",
    "heat tape": "Heat Trace Cable",
    "can light": "Recessed Light Housing",
    "can lights": "Recessed Light Housing",
    "wafer light": "Wafer LED Light",
    "wafer lights": "Wafer LED Light",
    "disc light": "Wafer LED Light",
    "leviton": "Leviton Devices",
    "lutron": "Lutron Lighting",
    "hubbell": "Hubbell Devices",
    "siemens": "Siemens Breaker",
    "ecobee": "Ecobee Thermostat",
    "honeywell": "Honeywell Thermostat",
    "nest": "Nest Thermostat",
    "ring": "Ring Doorbell",
    "smart lock": "Smart Lock",
    # --- HVAC ---------------------------------------------------------------
    "mini split": "Mini Split System",
    "ductless": "Mini Split System",
    "flex duct": "Flexible Duct",
    "spray foam": "Spray Foam Insulation",
    "rockwool": "Mineral Wool Insulation",
    "daikin": "Daikin Mini Split",
    "mitsubishi": "Mitsubishi Mini Split",
    "fujitsu": "Fujitsu Mini Split",
    "mrcool": "MrCool Mini Split",
    "mister cool": "MrCool Mini Split",
    "goodman": "Goodman Condenser",
    "carrier": "Carrier Furnace",
    "lennox": "Lennox Furnace",
    "trane": "Trane Furnace",
    "aprilaire": "Whole Home Humidifier",
    # --- Drywall & Paint -----------------------------------------------------
    "greenboard": "Water-Resistant Gypsum Board",
    "green board": "Water-Resistant Gypsum Board",
    "sheet rock": "Gypsum Wallboard",
    "popcorn": "Popcorn Ceiling Texture",
    "cottage cheese ceiling": "Popcorn Ceiling Texture",
    "knockdown": "Drywall Texture Knockdown",
    "orange peel": "Orange Peel Texture",
    "hot mud": "Setting Joint Compound",
    "corner bead": "Metal Corner Bead",
    "banjo": "Drywall Banjo",
    "stilts": "Drywall Stilts",
    "hawk": "Drywall Hawk",
    "pva": "Drywall Primer",
    "kilz": "Kilz Primer",
    "zinsser": "Zinsser Primer",
    "behr": "Behr Paint",
    "valspar": "Valspar Paint",
    # --- Roofing & Siding ------------------------------------------------------
    "tar paper": "Roofing Felt Underlayment",
    "ice and water": "Ice and Water Shield",
    "ice and water shield": "Ice and Water Shield",
    "pipe boot": "Pipe Boot Flashing",
    "gaf": "GAF Timberline Shingles",
    "timberline": "GAF Timberline Shingles",
    "owens corning": "Owens Corning Shingles",
    "certainteed": "CertainTeed Shingles",
    "certain teed": "CertainTeed Shingles",
    "hardie plank": "HardiePlank Siding",
    "azek": "Engineered Trim Board",
    "trex": "Composite Deck Board",
    "zip tape": "Flashing Tape",
    # --- Concrete & Masonry -----------------------------------------------------
    "cinder block": "Concrete Block CMU",
    "cmu": "Concrete Block CMU",
    "sonotube": "Column Form",
    "remesh": "Welded Wire Mesh",
    "bullnose": "Bullnose Block",
    "bond beam": "Bond Beam Block",
    "lintel": "Lintel Block",
    "firecode": "Gypsum Wallboard",
    "cement board": "Cement Board",
}
