"""Finish carpentry families that round out the app's legacy "carpentry"
trade (doors, windows, cabinets, stairs, trim hardware). The rough framing
content comes from framing.py re-keyed to "carpentry"."""

TRADE = "carpentry"

FAMILIES = [
    # ---- Doors ------------------------------------------------------------------
    {
        "canonical": "Prehung Interior Door",
        "suffixes": ["28 x 80", "30 x 80", "32 x 80", "36 x 80"],
        "aliases": ["prehung door", "interior door"],
        "unit": "EA",
        "definition": "Door pre-hung in its own jamb, ready to set.",
    },
    {
        "canonical": "Interior Door Slab",
        "suffixes": ["30 x 80", "32 x 80", "36 x 80"],
        "aliases": ["door slab", "hollow core door"],
        "unit": "EA",
        "definition": "Door leaf without the jamb, for existing frames.",
    },
    {
        "canonical": "Solid Core Door",
        "suffixes": ["30 x 80", "32 x 80"],
        "aliases": ["solid core door"],
        "unit": "EA",
        "definition": "Heavier sound-dampening door slab.",
    },
    {
        "canonical": "Closet Bi-Fold Door",
        "suffixes": ["24 x 80", "30 x 80", "32 x 80", "36 x 80"],
        "aliases": ["bifold door", "bi fold door"],
        "unit": "EA",
        "definition": "Folding closet door set.",
    },
    {
        "canonical": "Exterior Prehung Door",
        "suffixes": ["30 x 80", "32 x 80", "36 x 80"],
        "aliases": ["exterior door", "entry door"],
        "unit": "EA",
        "definition": "Insulated exterior door pre-hung in a weather-stripped jamb.",
    },
    {
        "canonical": "Steel Entry Door",
        "suffixes": ["36 x 80", "36 x 80 6-Panel"],
        "aliases": ["steel door", "steel entry"],
        "unit": "EA",
        "definition": "Energy-efficient steel exterior door.",
    },
    {
        "canonical": "Sliding Patio Door",
        "suffixes": ["60 x 80", "72 x 80", "96 x 80"],
        "aliases": ["patio door", "sliding glass door"],
        "unit": "EA",
        "definition": "Sliding glass door unit with screen.",
    },
    {
        "canonical": "French Door",
        "suffixes": ["60 x 80", "72 x 80"],
        "aliases": ["french doors", "french door"],
        "unit": "EA",
        "definition": "Pair of doors with glass lites.",
    },
    {
        "canonical": "Storm Door",
        "suffixes": ["30 x 80", "32 x 80", "36 x 80"],
        "aliases": ["storm door"],
        "unit": "EA",
        "definition": "Protective second door with glass and screen.",
    },
    {
        "canonical": "Garage Door",
        "suffixes": ["16 x 7", "9 x 7", "8 x 7"],
        "aliases": ["garage door", "overhead door"],
        "unit": "EA",
        "definition": "Sectional overhead garage door.",
    },
    # ---- Windows ----------------------------------------------------------------
    {
        "canonical": "Vinyl Window",
        "suffixes": ["24 x 36", "30 x 40", "36 x 48", "48 x 60"],
        "aliases": ["vinyl window", "replacement window"],
        "unit": "EA",
        "definition": "Double-hung vinyl replacement window.",
    },
    {
        "canonical": "Double Hung Window",
        "suffixes": ["24 x 36", "32 x 48", "36 x 60"],
        "aliases": ["double hung", "double hung window"],
        "unit": "EA",
        "definition": "Window with two vertically sliding sashes.",
    },
    {
        "canonical": "Casement Window",
        "suffixes": ["24 x 36", "30 x 48"],
        "aliases": ["casement window", "crank window"],
        "unit": "EA",
        "definition": "Window that cranks outward.",
    },
    {
        "canonical": "Sliding Window",
        "suffixes": ["36 x 24", "48 x 36"],
        "aliases": ["slider window", "horizontal window"],
        "unit": "EA",
        "definition": "Window with a horizontally sliding sash.",
    },
    {
        "canonical": "Basement Egress Window",
        "suffixes": ["36 x 36", "48 x 40"],
        "aliases": ["egress window", "basement window"],
        "unit": "EA",
        "definition": "Large egress-rated basement window with well.",
    },
    {
        "canonical": "Awning Window",
        "suffixes": ["24 x 24", "30 x 30"],
        "aliases": ["awning window"],
        "unit": "EA",
        "definition": "Window that opens outward from the bottom.",
    },
    # ---- Cabinets ----------------------------------------------------------------
    {
        "canonical": "Base Cabinet",
        "suffixes": ["12 in", "18 in", "24 in", "30 in", "36 in"],
        "aliases": ["base cabinet", "lower cabinet"],
        "unit": "EA",
        "definition": "Floor cabinet with doors and drawers.",
    },
    {
        "canonical": "Wall Cabinet",
        "suffixes": ["18 in", "24 in", "30 in", "36 in"],
        "aliases": ["wall cabinet", "upper cabinet"],
        "unit": "EA",
        "definition": "Wall-hung cabinet above the counter.",
    },
    {
        "canonical": "Full Height Cabinet",
        "suffixes": ["18 in", "24 in"],
        "aliases": ["tall cabinet", "pantry cabinet"],
        "unit": "EA",
        "definition": "Floor-to-ceiling cabinet for pantries and utilities.",
    },
    {
        "canonical": "Corner Base Cabinet",
        "suffixes": ["36 in", "42 in"],
        "aliases": ["corner cabinet", "lazy susan cabinet"],
        "unit": "EA",
        "definition": "Cabinet that fills a corner with a lazy susan.",
    },
    {
        "canonical": "Kitchen Drawer Base",
        "suffixes": ["15 in", "18 in", "21 in"],
        "aliases": ["drawer cabinet", "drawer base"],
        "unit": "EA",
        "definition": "Base cabinet with drawer banks.",
    },
    {
        "canonical": "Vanity Cabinet",
        "suffixes": ["24 in", "30 in", "36 in", "48 in"],
        "aliases": ["bath vanity", "vanity base"],
        "unit": "EA",
        "definition": "Bathroom sink cabinet.",
    },
    {
        "canonical": "Medicine Cabinet",
        "suffixes": ["16 x 24", "20 x 30"],
        "aliases": ["medicine cabinet"],
        "unit": "EA",
        "definition": "Recessed or surface bathroom cabinet.",
    },
    {
        "canonical": "Garage Cabinet",
        "suffixes": ["36 in", "48 in", "60 in"],
        "aliases": ["garage cabinet", "storage cabinet"],
        "unit": "EA",
        "definition": "Heavy-duty storage cabinet for garage and shop.",
    },

    # ---- Cabinet hardware & stairs -------------------------------------------------
    {
        "canonical": "Cabinet Knob",
        "suffixes": ["Satin Nickel", "Chrome", "Bronze", "Black"],
        "aliases": ["knob", "cabinet knob"],
        "unit": "EA",
        "definition": "Small pull mounted on cabinet doors.",
    },
    {
        "canonical": "Cabinet Pull",
        "suffixes": ["4 in", "6 in", "8 in", "12 in"],
        "aliases": ["pull", "cabinet pull", "bar pull"],
        "unit": "EA",
        "definition": "Bar handle for drawers and doors.",
    },
    {
        "canonical": "Door Hinge",
        "suffixes": ["3-1/2 in", "4 in", "Ball Bearing"],
        "aliases": ["hinge", "door hinge"],
        "unit": "EA",
        "definition": "Butt hinge for hanging doors.",
    },
    {
        "canonical": "Interior Door Handle",
        "suffixes": ["Passage", "Privacy", "Dummy"],
        "aliases": ["door handle", "door knob", "lever handle"],
        "unit": "EA",
        "definition": "Lever or knob set for interior doors.",
    },
    {
        "canonical": "Door Lockset",
        "suffixes": ["Keyed", "Deadbolt"],
        "aliases": ["lockset", "entry lockset"],
        "unit": "EA",
        "definition": "Keyed entry handle set.",
    },
    {
        "canonical": "Door Stop",
        "suffixes": ["Spring", "Hinge Pin"],
        "aliases": ["door stop", "door bumper"],
        "unit": "EA",
        "definition": "Stop that protects the wall from the door.",
    },
    {
        "canonical": "Stair Riser",
        "suffixes": ["1x8", "1x10"],
        "aliases": ["riser", "stair riser"],
        "unit": "EA",
        "definition": "Vertical board between stair treads.",
    },
    {
        "canonical": "Stair Tread",
        "suffixes": ["Oak", "Pine", "Prefinished"],
        "aliases": ["tread", "stair tread"],
        "unit": "EA",
        "definition": "Horizontal board on the top of each stair.",
    },
    {
        "canonical": "Handrail",
        "suffixes": ["Oak 8 ft", "Maple 8 ft", "Metal"],
        "aliases": ["handrail", "stair rail"],
        "unit": "LF",
        "definition": "Rail that runs along the stairway.",
    },
    {
        "canonical": "Baluster",
        "suffixes": ["Oak", "Maple", "Iron"],
        "aliases": ["baluster", "spindle"],
        "unit": "EA",
        "definition": "Vertical support between handrail and tread.",
    },
    {
        "canonical": "Newel Post",
        "suffixes": ["Turned", "Square"],
        "aliases": ["newel post", "newel"],
        "unit": "EA",
        "definition": "Main post at the bottom and top of the stairs.",
    },

    # ---- Closets & shelving ----------------------------------------------------------
    {
        "canonical": "Closet Rod",
        "suffixes": ["48 in", "72 in", "96 in"],
        "aliases": ["closet rod", "clothes rod"],
        "unit": "EA",
        "definition": "Rod that hangs clothes in a closet.",
    },
    {
        "canonical": "Closet Shelf",
        "suffixes": ["12 in", "16 in", "20 in"],
        "aliases": ["closet shelf", "shelf board"],
        "unit": "LF",
        "definition": "Shelf above the closet rod.",
    },
    {
        "canonical": "Wire Closet Shelf",
        "suffixes": ["12 in", "16 in"],
        "aliases": ["wire shelving", "closet shelving"],
        "unit": "LF",
        "definition": "Vented wire shelf and rod system.",
    },
    {
        "canonical": "Closet Organizer Kit",
        "suffixes": ["4 ft", "6 ft", "8 ft"],
        "aliases": ["closet system", "closet organizer"],
        "unit": "EA",
        "definition": "Modular shelf and drawer closet system.",
    },
    {
        "canonical": "Garage Shelving",
        "suffixes": ["4 ft", "6 ft", "8 ft"],
        "aliases": ["shelving", "storage shelves"],
        "unit": "EA",
        "definition": "Heavy-duty wire or steel shelving.",
    },
    {
        "canonical": "Floating Shelf",
        "suffixes": ["24 in", "36 in", "48 in"],
        "aliases": ["floating shelf", "wall shelf"],
        "unit": "EA",
        "definition": "Shelf that appears to float with hidden brackets.",
    },
    # ---- Door & window casing extras --------------------------------------------------
    {
        "canonical": "Door Jamb Kit",
        "suffixes": ["4-9/16 in", "5-1/2 in", "6-9/16 in"],
        "aliases": ["jamb kit", "door jamb"],
        "unit": "EA",
        "definition": "Pre-milled jamb legs and header for a door.",
    },
    {
        "canonical": "Window Jamb",
        "suffixes": ["Standard", "Extension"],
        "aliases": ["window jamb", "jamb extension"],
        "unit": "LF",
        "definition": "Jamb material that finishes a window opening.",
    },
    {
        "canonical": "Door Weatherstripping",
        "suffixes": ["Foam", "Vinyl", "Kerfed"],
        "aliases": ["weatherstrip", "weatherstripping"],
        "unit": "LF",
        "definition": "Seal that blocks drafts around a door.",
    },
    {
        "canonical": "Door Sweep",
        "suffixes": ["Standard", "Heavy Duty"],
        "aliases": ["door sweep", "bottom seal"],
        "unit": "EA",
        "definition": "Bottom-of-door draft seal.",
    },
    {
        "canonical": "Window Screen",
        "suffixes": ["Standard", "Pet Resistant"],
        "aliases": ["screen", "window screen"],
        "unit": "EA",
        "definition": "Screening for a window or door.",
    },
    {
        "canonical": "Screen Repair Kit",
        "suffixes": ["Standard"],
        "aliases": ["screen kit", "screen patch"],
        "unit": "EA",
        "definition": "Spline and screen for repairs.",
    },
    {
        "canonical": "Wood Filler",
        "suffixes": ["Stainable", "Paintable"],
        "aliases": ["wood filler", "wood putty"],
        "unit": "TUBE",
        "definition": "Filler for nail holes in trim.",
    },
    {
        "canonical": "Trim Adhesive",
        "suffixes": ["10 oz", "28 oz"],
        "aliases": ["trim adhesive", "panel adhesive"],
        "unit": "TUBE",
        "definition": "Construction adhesive for trim install.",
    },
]

