"""Concrete & masonry lexicon families: mixes, rebar, forms, block, brick,
stone, finishing tools, foundations, and paver systems."""

TRADE = "Concrete & Masonry"

FAMILIES = [
    # ---- Concrete mixes ----------------------------------------------------------
    {
        "canonical": "Ready Mix Concrete",
        "suffixes": ["2500 PSI", "3000 PSI", "3500 PSI", "4000 PSI", "4500 PSI", "5000 PSI"],
        "aliases": ["ready mix", "concrete", "redimix", "truck concrete"],
        "unit": "YD",
        "definition": "Truck-delivered concrete batched to the specified compressive strength.",
        "phonetic": "KON-kreet",
        "ipa": "/ˈkɒŋkriːt/",
    },
    {
        "canonical": "Quikrete Mix",
        "suffixes": ["5000", "4000", "Fiber-Reinforced", "High Early"],
        "aliases": ["quikrete", "quickrete", "sakrete", "bagged concrete"],
        "unit": "BAG",
        "definition": "Pre-blended bagged concrete; add water and pour.",
        "phonetic": "KWIK-reet",
        "ipa": "/ˈkwɪkriːt/",
    },
    {
        "canonical": "Sakrete Mix",
        "suffixes": ["Standard", "Maximizer"],
        "aliases": ["sakrete", "sakcrete"],
        "unit": "BAG",
        "definition": "Sakrete brand bagged concrete mixes.",
        "phonetic": "SAY-kreet",
        "ipa": "/ˈseɪkriːt/",
    },
    {
        "canonical": "Self-Leveling Concrete",
        "suffixes": ["50 lb", "80 lb"],
        "aliases": ["self leveler", "self leveling compound", "floor leveler"],
        "unit": "BAG",
        "definition": "Flowable topping that self-levels to fix uneven floors.",
    },
    {
        "canonical": "Concrete Patch",
        "suffixes": ["Small 10 lb", "Vinyl Concrete", "Polymer"],
        "aliases": ["concrete patch", "patch mix"],
        "unit": "BAG",
        "definition": "Bonding patching mix for spalls and cracks.",
    },
    {
        "canonical": "Concrete Resurfacer",
        "suffixes": ["50 lb", "Quart"],
        "aliases": ["resurfacer", "concrete overlay"],
        "unit": "BAG",
        "definition": "Thin overlay that renews worn driveways and patios.",
    },
    {
        "canonical": "Shotcrete Mix",
        "suffixes": ["Gunite", "Pneumatic"],
        "aliases": ["shotcrete", "gunite", "pneumatic concrete"],
        "unit": "YD",
        "definition": "Concrete sprayed at high velocity for pools and slopes.",
    },
    {
        "canonical": "Post-Tension System",
        "suffixes": ["Tendons", "Anchors"],
        "aliases": ["post tension", "pt slab"],
        "unit": "LF",
        "definition": "Steel tendons tensioned after the slab cures for long spans.",
    },
    # ---- Rebar & reinforcing -----------------------------------------------------
    {
        "canonical": "Rebar",
        "suffixes": ["#3", "#4", "#5", "#6", "#7", "#8"],
        "lengths": ["10 ft", "20 ft"],
        "aliases": ["rebar", "reinforcing bar", "steel rebar"],
        "unit": "EA",
        "definition": "Deformed steel reinforcing bar; #4 is the slab/footing standard.",
        "phonetic": "REE-bar",
        "ipa": "/ˈriːbɑːr/",
    },
    {
        "canonical": "Epoxy Coated Rebar",
        "suffixes": ["#4", "#5"],
        "lengths": ["10 ft", "20 ft"],
        "aliases": ["epoxy rebar", "green rebar"],
        "unit": "EA",
        "definition": "Corrosion-resistant epoxy-coated bar for decks and bridges.",
    },
    {
        "canonical": "Rebar Chair",
        "suffixes": ["1-1/2 in", "2 in", "3 in", "4 in", "5 in", "6 in"],
        "aliases": ["rebar chairs", "slab bolster", "rebar stand"],
        "unit": "EA",
        "definition": "Plastic or steel support that holds rebar at the right depth.",
    },
    {
        "canonical": "Rebar Tie Wire",
        "suffixes": ["16 Gauge", "18 Gauge"],
        "aliases": ["tie wire", "rebar wire"],
        "unit": "LB",
        "definition": "Annealed wire that lashes rebar intersections.",
    },
    {
        "canonical": "Rebar Coupler",
        "suffixes": ["#4", "#5", "#6", "#8"],
        "aliases": ["rebar splice", "mechanical coupler"],
        "unit": "EA",
        "definition": "Mechanical splice that joins rebar without lapping.",
    },
    {
        "canonical": "Rebar Cap",
        "suffixes": ["#4", "#5", "#6"],
        "aliases": ["rebar cap", "safety cap"],
        "unit": "EA",
        "definition": "Plastic cap that covers exposed bar ends on site.",
    },
    {
        "canonical": "Welded Wire Mesh",
        "suffixes": ["6x6-W1.4", "6x10-W1.4", "6x6-W2.9"],
        "aliases": ["wire mesh", "remesh", "wwf"],
        "unit": "SF",
        "definition": "Welded wire fabric reinforcing for slabs on grade.",
    },
    {
        "canonical": "Concrete Fiber Reinforcement",
        "suffixes": ["Micro", "Macro"],
        "aliases": ["fiber mesh", "concrete fibers", "fiber reinforcement"],
        "unit": "BAG",
        "definition": "Synthetic fibers added to the mix to control shrinkage cracks.",
    },
    {
        "canonical": "Rebar Bender",
        "suffixes": ["Manual", "Electric"],
        "aliases": ["rebar bender", "bar bender"],
        "unit": "EA",
        "definition": "Tool that bends rebar into hooks and stirrups.",
    },
    {
        "canonical": "Rebar Cutter",
        "suffixes": ["Manual", "Electric"],
        "aliases": ["rebar cutter", "bolt cutter"],
        "unit": "EA",
        "definition": "Tool that shears rebar to length.",
    },
    # ---- Forms & concrete accessories -------------------------------------------
    {
        "canonical": "Form Lumber",
        "suffixes": ["2x4", "2x6", "2x8", "2x10"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["form boards", "form lumber", "forming lumber"],
        "unit": "LF",
        "definition": "Dimension lumber that holds wet concrete in shape until it cures.",
    },
    {
        "canonical": "Plyform Sheathing",
        "suffixes": ["1/2 in", "3/4 in"],
        "aliases": ["plyform", "form plywood", "concrete form"],
        "unit": "SF",
        "definition": "BB-OES plywood rated for concrete form faces.",
    },
    {
        "canonical": "Snap Tie",
        "suffixes": ["6 in", "12 in"],
        "aliases": ["snap ties", "form ties", "wall ties"],
        "unit": "EA",
        "definition": "Wire ties that hold wall forms together at the right thickness.",
    },
    {
        "canonical": "Form Release Agent",
        "suffixes": ["1 Gal", "5 Gal"],
        "aliases": ["form release", "form oil", "release agent"],
        "unit": "GAL",
        "definition": "Oil that keeps concrete from sticking to the forms.",
    },
    {
        "canonical": "Form Stakes",
        "suffixes": ["18 in", "24 in"],
        "aliases": ["stakes", "steel stakes", "form stakes"],
        "unit": "EA",
        "definition": "Steel pins that anchor forms to the ground.",
    },
    {
        "canonical": "Expansion Joint Material",
        "suffixes": ["3 in", "4 in"],
        "aliases": ["expansion joint", "fiber board", "asphalt joint"],
        "unit": "LF",
        "definition": "Compressible board placed between slabs and walls for movement.",
    },
    {
        "canonical": "Control Joint Tool",
        "suffixes": ["1/4 in", "3/8 in"],
        "aliases": ["control joint", "groover", "joint tool"],
        "unit": "EA",
        "definition": "Tool that cuts contraction grooves to control slab cracking.",
    },
    {
        "canonical": "Vapor Barrier",
        "suffixes": ["6 mil", "10 mil"],
        "aliases": ["vapor barrier", "poly sheeting", "moisture barrier"],
        "unit": "SF",
        "definition": "Polyethylene sheet under the slab that blocks ground moisture.",
    },
    {
        "canonical": "Curing Compound",
        "suffixes": ["Clear", "White"],
        "aliases": ["curing compound", "cure and seal"],
        "unit": "GAL",
        "definition": "Membrane that seals water into fresh concrete as it cures.",
    },
    {
        "canonical": "Bond Breaker",
        "suffixes": ["Spray", "Liquid"],
        "aliases": ["bond breaker", "tilting compound"],
        "unit": "GAL",
        "definition": "Release coating that prevents slabs from bonding to the substrate.",
    },
    {
        "canonical": "Waterstop",
        "suffixes": ["PVC", "Bentonite"],
        "aliases": ["waterstop", "water stop"],
        "unit": "LF",
        "definition": "Sealing strip at construction joints that blocks water migration.",
    },
    {
        "canonical": "Column Form",
        "suffixes": ["8 in", "10 in", "12 in", "16 in", "20 in"],
        "aliases": ["sonotube", "column tube", "round form"],
        "unit": "EA",
        "definition": "Fiber tube that forms round concrete columns and piers.",
    },
    {
        "canonical": "Concrete Pump",
        "suffixes": ["Line Pump", "Boom Pump"],
        "aliases": ["concrete pump", "pump truck"],
        "unit": "EA",
        "definition": "Truck pump that moves concrete from the truck to the pour.",
    },
    {
        "canonical": "Concrete Chute",
        "suffixes": ["Standard", "Extension"],
        "aliases": ["chute", "pour chute"],
        "unit": "EA",
        "definition": "Metal trough that directs concrete from truck to forms.",
    },
    {
        "canonical": "Wheelbarrow",
        "suffixes": ["6 cu ft", "8 cu ft"],
        "aliases": ["wheelbarrow", "concrete cart"],
        "unit": "EA",
        "definition": "Job-site cart for hauling mix, sand, and tools.",
    },
    {
        "canonical": "Wet Saw",
        "suffixes": ["Handheld", "Walk-Behind"],
        "aliases": ["wet saw", "concrete saw", "cut off saw"],
        "unit": "EA",
        "definition": "Diamond-blade saw that cuts cured concrete with water.",
    },
    # ---- Block, brick, stone -----------------------------------------------------
    {
        "canonical": "Concrete Block CMU",
        "suffixes": ["4 in Standard", "6 in Standard", "8 in Standard", "10 in Standard", "12 in Standard", "8 in Split Face", "10 in Split Face", "8 in Burnished"],
        "aliases": ["cinder block", "cmu", "block", "concrete block", "cinderblock"],
        "unit": "EA",
        "definition": "Concrete masonry unit for foundations, walls, and structures.",
        "phonetic": "SEE EM YOO",
        "ipa": "/siː ɛm juː/",
    },
    {
        "canonical": "Half Block",
        "suffixes": ["4 in", "6 in", "8 in"],
        "aliases": ["half block", "half cmu"],
        "unit": "EA",
        "definition": "Half-length block used to stagger coursing.",
    },
    {
        "canonical": "Lintel Block",
        "suffixes": ["8 in", "12 in"],
        "aliases": ["lintel block", "beam block", "u block"],
        "unit": "EA",
        "definition": "U-shaped block that forms a concrete lintel over openings.",
    },
    {
        "canonical": "Bond Beam Block",
        "suffixes": ["8 in", "12 in"],
        "aliases": ["bond beam", "bondbeam block"],
        "unit": "EA",
        "definition": "Block with a continuous channel for horizontal reinforcement.",
    },
    {
        "canonical": "Bullnose Block",
        "suffixes": ["4 in", "6 in", "8 in"],
        "aliases": ["bullnose", "rounded block"],
        "unit": "EA",
        "definition": "Block with rounded corners for exposed wall edges and stairs.",
    },
    {
        "canonical": "Cap Block",
        "suffixes": ["4 in", "8 in"],
        "aliases": ["cap block", "coping block"],
        "unit": "EA",
        "definition": "Solid block that tops a CMU wall.",
    },
    {
        "canonical": "Masonry Mortar",
        "suffixes": ["Type S", "Type N", "Type M", "Quikrete Blend"],
        "aliases": ["mortar", "masonry cement", "brick mortar"],
        "unit": "BAG",
        "definition": "Cement-lime mortar mix; Type S for structural, Type N for veneer.",
    },
    {
        "canonical": "Mortar Colors",
        "suffixes": ["Gray", "White", "Buff"],
        "aliases": ["mortar color", "colored mortar"],
        "unit": "BAG",
        "definition": "Colored mortar for architectural masonry.",
    },
    {
        "canonical": "Masonry Grout",
        "suffixes": ["Non-Shrink", "Structural", "Fine"],
        "aliases": ["grout", "masonry grout"],
        "unit": "BAG",
        "definition": "Flowable grout that fills block cores and voids.",
    },
    {
        "canonical": "Brick",
        "suffixes": ["Standard Red", "Common", "Tan", "Firebrick", "Thin Brick"],
        "aliases": ["brick", "clay brick", "masonry brick"],
        "unit": "EA",
        "definition": "Clay brick for veneers, walls, and accents.",
    },
    {
        "canonical": "Brick Paver",
        "suffixes": ["4 x 8", "4 x 8 Red", "6 x 6"],
        "aliases": ["paver brick", "brick pavers"],
        "unit": "EA",
        "definition": "Clay paver for walkways and patios.",
    },
    {
        "canonical": "Refractory Mortar",
        "suffixes": ["10 lb", "50 lb"],
        "aliases": ["refractory cement", "fire mortar"],
        "unit": "BAG",
        "definition": "High-heat mortar for fireplaces and fireboxes.",
    },
    {
        "canonical": "Flue Tile",
        "suffixes": ["8 x 8", "8 x 13", "13 x 13"],
        "aliases": ["flue tile", "chimney flue", "clay flue"],
        "unit": "EA",
        "definition": "Clay liner tile that protects the chimney from heat and gas.",
    },
    {
        "canonical": "Stone Veneer",
        "suffixes": ["Cultured Stone", "Ledger Panel", "River Rock", "Flagstone"],
        "aliases": ["stone veneer", "cultured stone", "faux stone"],
        "unit": "SF",
        "definition": "Manufactured or natural stone panels for walls and facades.",
    },
    {
        "canonical": "Retaining Wall Block",
        "suffixes": ["Keystone 8 in", "Keystone 12 in", "Allan Block"],
        "aliases": ["retaining wall block", "keystone block", "segmental wall"],
        "unit": "EA",
        "definition": "Mortarless interlocking block for retaining walls.",
    },
    # ---- Finishing tools ---------------------------------------------------------
    {
        "canonical": "Concrete Trowel",
        "suffixes": ["4 x 12", "5 x 14"],
        "aliases": ["trowel", "steel trowel", "finishing trowel"],
        "unit": "EA",
        "definition": "Steel blade that burnishes the final concrete surface.",
    },
    {
        "canonical": "Concrete Float",
        "suffixes": ["16 in", "20 in"],
        "aliases": ["float", "wood float", "magnesium float"],
        "unit": "EA",
        "definition": "Tool that levels and textures concrete before troweling.",
    },
    {
        "canonical": "Bull Float",
        "suffixes": ["48 in", "60 in"],
        "aliases": ["bull float", "bullfloater"],
        "unit": "EA",
        "definition": "Long-handle float that works the surface of a fresh slab.",
    },
    {
        "canonical": "Concrete Screed",
        "suffixes": ["2x4", "Aluminum"],
        "aliases": ["screed", "strike off"],
        "unit": "EA",
        "definition": "Straight edge that strikes off concrete to grade.",
    },
    {
        "canonical": "Power Trowel",
        "suffixes": ["Walk-Behind", "Ride-On"],
        "aliases": ["power trowel", "troweling machine"],
        "unit": "EA",
        "definition": "Gas machine that finishes large slabs.",
    },
    {
        "canonical": "Concrete Edger",
        "suffixes": ["Standard", "Radius"],
        "aliases": ["edger", "edging tool"],
        "unit": "EA",
        "definition": "Tool that rounds slab edges to prevent chipping.",
    },
    {
        "canonical": "Concrete Broom",
        "suffixes": ["36 in", "48 in"],
        "aliases": ["broom", "broom finish"],
        "unit": "EA",
        "definition": "Coarse broom that textures outdoor slabs for traction.",
    },
    {
        "canonical": "Concrete Grinder",
        "suffixes": ["Handheld", "Walk-Behind"],
        "aliases": ["concrete grinder", "diamond grinder"],
        "unit": "EA",
        "definition": "Diamond-disk grinder that smooths or textures concrete.",
    },
    {
        "canonical": "Core Drill",
        "suffixes": ["1 in", "2 in", "4 in"],
        "aliases": ["core drill", "concrete drill"],
        "unit": "EA",
        "definition": "Diamond bit that cuts round holes through slabs and walls.",
    },
    {
        "canonical": "Masonry Mixer",
        "suffixes": ["3 cu ft", "5 cu ft"],
        "aliases": ["mortar mixer", "cement mixer"],
        "unit": "EA",
        "definition": "Rotating drum that mixes mortar and small concrete batches.",
    },
    {
        "canonical": "Concrete Vibrator",
        "suffixes": ["1 in", "1-1/2 in"],
        "aliases": ["vibrator", "concrete vibrator"],
        "unit": "EA",
        "definition": "Immersion tool that consolidates concrete in forms.",
    },
    {
        "canonical": "Laser Level",
        "suffixes": ["Rotary", "Line"],
        "aliases": ["laser level", "rotary laser"],
        "unit": "EA",
        "definition": "Self-leveling tool for screed and grading work.",
    },
    # ---- Finishing products --------------------------------------------------------
    {
        "canonical": "Concrete Sealer",
        "suffixes": ["Penetrating", "Film Forming"],
        "aliases": ["sealer", "concrete sealer"],
        "unit": "GAL",
        "definition": "Protective coating for driveways, patios, and garage floors.",
    },
    {
        "canonical": "Concrete Densifier",
        "suffixes": ["Lithium", "Sodium"],
        "aliases": ["densifier", "concrete hardener"],
        "unit": "GAL",
        "definition": "Liquid that hardens and polishes concrete surfaces.",
    },
    {
        "canonical": "Concrete Stain",
        "suffixes": ["Acid", "Water-Based"],
        "aliases": ["concrete stain", "acid stain"],
        "unit": "GAL",
        "definition": "Translucent color treatment for interior and exterior slabs.",
    },
    {
        "canonical": "Epoxy Garage Floor Coating",
        "suffixes": ["Kit", "Professional Grade"],
        "aliases": ["epoxy floor", "garage floor epoxy"],
        "unit": "KIT",
        "definition": "Two-part epoxy that creates a tough glossy garage floor.",
    },
    {
        "canonical": "Stamped Concrete",
        "suffixes": ["Stamps", "Release Agent"],
        "aliases": ["stamped concrete", "texture stamps"],
        "unit": "EA",
        "definition": "Texturing stamps that imprint stone or slate patterns.",
    },
    {
        "canonical": "Exposed Aggregate",
        "suffixes": ["Sealer", "Retarder"],
        "aliases": ["exposed aggregate", "washed concrete"],
        "unit": "EA",
        "definition": "Top-seeded stone surface washed to reveal the aggregate.",
    },
    {
        "canonical": "Crack Filler",
        "suffixes": ["Tube", "Self-Leveling"],
        "aliases": ["crack filler", "concrete crack seal"],
        "unit": "TUBE",
        "definition": "Flexible sealant for concrete cracks before coating.",
    },
    {
        "canonical": "Concrete Countertop Mix",
        "suffixes": ["GFRC", "Standard"],
        "aliases": ["countertop mix", "concrete countertop"],
        "unit": "BAG",
        "definition": "Fiber-reinforced mix for cast concrete counters.",
    },
    # ---- Foundations & structure --------------------------------------------------
    {
        "canonical": "Foundation Footing",
        "suffixes": ["12 x 24", "16 x 32", "24 x 48"],
        "aliases": ["footing", "footer", "spread footing"],
        "unit": "LF",
        "definition": "Wide concrete base that spreads wall and column loads.",
        "phonetic": "foun-DAY-shun",
        "ipa": "/faʊnˈdeɪʃən/",
    },
    {
        "canonical": "Stem Wall",
        "suffixes": ["8 in", "10 in", "12 in"],
        "aliases": ["stem wall", "foundation wall"],
        "unit": "LF",
        "definition": "CMU or poured wall above the footing that carries the house.",
    },
    {
        "canonical": "Poured Concrete Wall",
        "suffixes": ["8 in", "10 in", "12 in"],
        "aliases": ["poured wall", "foundation wall"],
        "unit": "LF",
        "definition": "Cast-in-place foundation wall with rebar.",
    },
    {
        "canonical": "Concrete Pier",
        "suffixes": ["8 in", "12 in", "16 in"],
        "aliases": ["pier", "concrete pier", "pier footing"],
        "unit": "EA",
        "definition": "Round or square column footing for decks and porches.",
    },
    {
        "canonical": "Grade Beam",
        "suffixes": ["12 x 12", "12 x 18"],
        "aliases": ["grade beam", "grade beam foundation"],
        "unit": "LF",
        "definition": "Ground-level beam spanning between piers or piles.",
    },
    {
        "canonical": "Concrete Slab",
        "suffixes": ["4 in", "5 in", "6 in"],
        "aliases": ["slab", "slab on grade", "monolithic slab"],
        "unit": "SF",
        "definition": "Poured concrete floor on grade.",
    },
    {
        "canonical": "Sidewalk Concrete",
        "suffixes": ["4 in", "5 in"],
        "aliases": ["sidewalk", "walkway", "concrete walk"],
        "unit": "SF",
        "definition": "Exterior walkway slab, usually 4-5 inches thick.",
    },
    {
        "canonical": "Gravel Base",
        "suffixes": ["Mason Sand", "Concrete Sand", "Pea Gravel", "#57 Stone", "Crush and Run"],
        "lengths": ["1/2 Yard", "1 Yard"],
        "aliases": ["gravel", "sand", "aggregate", "crush run"],
        "unit": "YD",
        "definition": "Aggregate placed as a subbase under slabs, pavers, and footings.",
    },
    {
        "canonical": "Precast Concrete Steps",
        "suffixes": ["2 Step", "3 Step", "4 Step"],
        "aliases": ["precast steps", "concrete steps", "porch steps"],
        "unit": "EA",
        "definition": "Ready-made concrete entry steps.",
    },
    {
        "canonical": "Precast Lintel",
        "suffixes": ["4 x 8", "6 x 8"],
        "aliases": ["precast lintel", "concrete lintel"],
        "unit": "EA",
        "definition": "Precast beam that spans a block wall opening.",
    },
    {
        "canonical": "Concrete Window Sill",
        "suffixes": ["4 x 8", "6 x 8"],
        "aliases": ["window sill", "precast sill"],
        "unit": "EA",
        "definition": "Precast sill that sheds water below a window.",
    },
    {
        "canonical": "Splash Block",
        "suffixes": ["Standard", "Decorative"],
        "aliases": ["splash block", "downspout splash"],
        "unit": "EA",
        "definition": "Small precast trough that carries downspout water away.",
    },
    {
        "canonical": "Catch Basin",
        "suffixes": ["12 in", "24 in"],
        "aliases": ["catch basin", "yard drain"],
        "unit": "EA",
        "definition": "Buried basin that collects surface water to a drain line.",
    },
    {
        "canonical": "Drain Tile",
        "suffixes": ["4 in Perforated", "4 in Solid"],
        "aliases": ["drain tile", "french drain", "perimeter drain"],
        "unit": "LF",
        "definition": "Perforated pipe around the footing that drains groundwater.",
    },
    {
        "canonical": "Radon Mitigation Pipe",
        "suffixes": ["3 in", "4 in"],
        "aliases": ["radon pipe", "radon vent"],
        "unit": "LF",
        "definition": "Sub-slab vent pipe that pulls radon out of the house.",
    },
    {
        "canonical": "Termite Shield",
        "suffixes": ["Standard", "Copper"],
        "aliases": ["termite shield", "termite barrier"],
        "unit": "LF",
        "definition": "Metal barrier that blocks termites at the foundation line.",
    },
    # ---- Pavers ---------------------------------------------------------------------
    {
        "canonical": "Concrete Paver",
        "suffixes": ["4 x 8 Red", "4 x 8 Tan", "6 x 9 Grey", "12 x 12", "18 x 18"],
        "aliases": ["paver", "pavers", "concrete paver"],
        "unit": "SF",
        "definition": "Interlocking concrete unit for driveways, patios, and walks.",
    },
    {
        "canonical": "Paver Base",
        "suffixes": ["3/4 in", "1 in"],
        "aliases": ["paver base", "paver stone"],
        "unit": "YD",
        "definition": "Compactable crushed stone base for paver installations.",
    },
    {
        "canonical": "Paver Sand",
        "suffixes": ["Polymeric", "Regular"],
        "aliases": ["paver sand", "joint sand"],
        "unit": "BAG",
        "definition": "Sand swept into paver joints; polymeric locks when wet.",
    },
    {
        "canonical": "Paver Edge Restraint",
        "suffixes": ["Plastic", "Steel"],
        "aliases": ["edge restraint", "paver edging"],
        "unit": "LF",
        "definition": "Stake-and-spike edging that keeps pavers from spreading.",
    },
    {
        "canonical": "Concrete Test Cylinder",
        "suffixes": ["4 x 8", "6 x 12"],
        "aliases": ["test cylinder", "concrete cylinder"],
        "unit": "EA",
        "definition": "Molded sample that verifies the concrete's compressive strength.",
    },
    {
        "canonical": "Slump Cone",
        "suffixes": ["Standard"],
        "aliases": ["slump test", "slump cone"],
        "unit": "EA",
        "definition": "Cone used to measure the slump (workability) of fresh concrete.",
    },
    {
        "canonical": "Concrete Cover Meter",
        "suffixes": ["Standard", "Pro"],
        "aliases": ["cover meter", "rebar locator"],
        "unit": "EA",
        "definition": "Device that locates rebar and checks concrete cover.",
    },
    {
        "canonical": "Chimney Cap",
        "suffixes": ["Metal", "Copper", "Stone"],
        "aliases": ["chimney cap", "chimney cover"],
        "unit": "EA",
        "definition": "Cap that keeps rain, animals, and sparks out of the flue.",
    },
    {
        "canonical": "Fireplace Damper",
        "suffixes": ["Top Sealing", "Throat"],
        "aliases": ["damper", "fireplace damper"],
        "unit": "EA",
        "definition": "Flue control that seals the chimney when the fireplace is cold.",
    },
    {
        "canonical": "Masonry Wedge Anchor",
        "suffixes": ["3/8 in", "5/8 in", "3/4 in"],
        "aliases": ["wedge anchor", "sleeve anchor", "concrete anchor"],
        "unit": "EA",
        "definition": "Expansion anchor that bolts steel and wood to concrete.",
    },
    {
        "canonical": "Epoxy Anchoring Adhesive",
        "suffixes": ["Cartridge", "Syringe"],
        "aliases": ["epoxy anchor", "structural epoxy"],
        "unit": "EA",
        "definition": "Two-part adhesive that bonds threaded rod into drilled holes.",
    },
    {
        "canonical": "Concrete Dowel",
        "suffixes": ["Smooth", "Deformed"],
        "aliases": ["dowel", "load transfer bar"],
        "unit": "EA",
        "definition": "Bar that transfers load across slab construction joints.",
    },
    {
        "canonical": "Keyway Form",
        "suffixes": ["2 x 4", "3 x 4"],
        "aliases": ["keyway", "keyway board"],
        "unit": "LF",
        "definition": "Groove form that locks a second pour to the first.",
    },
    {
        "canonical": "Masonry Joint Tool",
        "suffixes": ["Concave", "V-Joint"],
        "aliases": ["jointer", "striker", "mortar joint tool"],
        "unit": "EA",
        "definition": "Tool that compresses and shapes mortar joints.",
    },
    {
        "canonical": "Masonry Saw",
        "suffixes": ["Table", "Handheld"],
        "aliases": ["masonry saw", "block saw"],
        "unit": "EA",
        "definition": "Diamond saw that cuts block and brick.",
    },
    {
        "canonical": "Brick Trowel",
        "suffixes": ["Philadelphia", "London"],
        "aliases": ["brick trowel", "masonry trowel"],
        "unit": "EA",
        "definition": "Trowel that lays and cuts mortar for brickwork.",
    },
    {
        "canonical": "Masonry Level",
        "suffixes": ["2 ft", "4 ft"],
        "aliases": ["brick level", "mason level"],
        "unit": "EA",
        "definition": "Stiff level used for block and brick coursing.",
    },
    {
        "canonical": "Plumb Bob",
        "suffixes": ["Standard", "Magnetic"],
        "aliases": ["plumb bob", "plummet"],
        "unit": "EA",
        "definition": "Weight on a line that establishes true vertical.",
    },
    {
        "canonical": "String Line",
        "suffixes": ["100 ft", "500 ft"],
        "aliases": ["string line", "mason's line", "chalk line"],
        "unit": "ROLL",
        "definition": "Nylon line used to set courses and footing heights.",
    },
    {
        "canonical": "Concrete Bucket",
        "suffixes": ["1/2 Yard", "1 Yard"],
        "aliases": ["concrete bucket", "pour bucket"],
        "unit": "EA",
        "definition": "Crane bucket that places concrete in deep forms.",
    },
    {
        "canonical": "Mud Board",
        "suffixes": ["2 x 3", "2 x 4"],
        "aliases": ["mud board", "mortar board", "hawk board"],
        "unit": "EA",
        "definition": "Flat board that holds mortar for the mason.",
    },
    {
        "canonical": "Concrete Hoe",
        "suffixes": ["Standard", "Mortar Hoe"],
        "aliases": ["hoe", "mixing hoe"],
        "unit": "EA",
        "definition": "Cut-corner hoe used to mix mortar in a trough.",
    },
    {
        "canonical": "Square Point Shovel",
        "suffixes": ["Standard", "Concrete"],
        "aliases": ["shovel", "square shovel"],
        "unit": "EA",
        "definition": "All-purpose shovel for moving concrete and aggregate.",
    },
    {
        "canonical": "Concrete Saw Blade",
        "suffixes": ["14 in", "18 in"],
        "aliases": ["saw blade", "diamond blade"],
        "unit": "EA",
        "definition": "Diamond segment blade for cutting cured concrete.",
    },
    {
        "canonical": "Wet-Dry Vacuum",
        "suffixes": ["5 Gal", "12 Gal"],
        "aliases": ["shop vac", "wet dry vac"],
        "unit": "EA",
        "definition": "Dust collection vacuum for grinding and drilling concrete.",
    },

    {
        "canonical": "Masonry Waterproofer",
        "suffixes": ["Crystal", "Sealer"],
        "aliases": ["waterproofer", "block sealer", "dampproofing"],
        "unit": "GAL",
        "definition": "Coating that blocks moisture through block and brick walls.",
    },
    {
        "canonical": "Concrete Acid Cleaner",
        "suffixes": ["1 Gal", "5 Gal"],
        "aliases": ["acid wash", "concrete cleaner", "etch"],
        "unit": "GAL",
        "definition": "Muriatic-based wash that etches and cleans concrete before coating.",
    },
]

