"""Drywall & paint lexicon families: gypsum boards, joint compound, texture,
paint sheens/finishes, trim, and the brands STT hears (Sherwin-Williams,
Benjamin Moore, USG...)."""

TRADE = "Drywall & Paint"

FAMILIES = [
    {
        "canonical": "Gypsum Wallboard",
        "suffixes": ["1/4 Regular", "1/2 Regular", "5/8 Regular", "1/2 Type X", "5/8 Type X"],
        "suffix_aliases": {"1/4 Regular": ["1/4 drywall", "1/4 sheetrock"], "1/2 Regular": ["1/2 drywall", "half inch drywall", "sheetrock"],
                           "5/8 Regular": ["5/8 drywall"], "5/8 Type X": ["type x", "firecode", "5/8 type x"]},
        "aliases": ["drywall", "gypsum board", "wallboard", "sheetrock", "plasterboard"],
        "unit": "SF",
        "definition": "Gypsum panel hung on studs for wall and ceiling finish; Type X adds fire resistance.",
        "phonetic": "JIP-sum WALL-bord",
        "ipa": "/ˈdʒɪpsəm ˈwɔːlbɔːrd/",
    },
    {
        "canonical": "Water-Resistant Gypsum Board",
        "suffixes": ["1/2 Green", "5/8 Green"],
        "aliases": ["greenboard", "green board", "moisture resistant drywall", "mr board"],
        "unit": "SF",
        "definition": "Green-faced gypsum board for damp areas like bathroom walls behind tile.",
        "phonetic": "GREEN-bord",
        "ipa": "/ˈɡriːnbɔːrd/",
    },
    {
        "canonical": "Mold-Resistant Gypsum Board",
        "suffixes": ["1/2 Purple", "5/8 Purple"],
        "aliases": ["purple board", "mold resistant drywall", "mr board"],
        "unit": "SF",
        "definition": "Purple-faced paperless gypsum board that resists mold growth.",
    },
    {
        "canonical": "DensShield Tile Backer",
        "suffixes": ["1/2", "5/8"],
        "aliases": ["densshield", "glass mat backer", "densglass tile"],
        "unit": "SF",
        "definition": "Fiberglass-faced gypsum tile backer with a waterproof coating.",
        "phonetic": "DENS-shield",
        "ipa": "/ˈdɛnsʃiːld/",
    },
    {
        "canonical": "Cement Board",
        "suffixes": ["1/2", "5/8"],
        "aliases": ["cement backer", "durock", "hardiebacker", "tile backer"],
        "unit": "SF",
        "definition": "Cementitious backer board for tile and wet areas.",
    },
    {
        "canonical": "HardieBacker Board",
        "suffixes": ["1/4", "1/2", "5/8"],
        "aliases": ["hardiebacker", "hardie backer"],
        "unit": "SF",
        "definition": "James Hardie cement board for tile substrate.",
        "phonetic": "HAR-dee BAK-er",
        "ipa": "/ˈhɑːrdi ˈbækər/",
    },
    {
        "canonical": "USG Sheetrock Brand Board",
        "suffixes": ["1/2 Ultralight", "5/8 Firecode X"],
        "aliases": ["usg sheetrock", "sheetrock brand"],
        "unit": "SF",
        "definition": "USG Sheetrock brand gypsum panels.",
        "phonetic": "SHEET-rok",
        "ipa": "/ˈʃiːtrɒk/",
    },
    {
        "canonical": "All-Purpose Joint Compound",
        "suffixes": ["4.5 Gal", "18 Gal"],
        "aliases": ["mud", "joint compound", "all purpose mud", "drywall mud"],
        "unit": "BUCKET",
        "definition": "Ready-mix compound for taping, filling, and finishing drywall joints.",
    },
    {
        "canonical": "Lightweight Joint Compound",
        "suffixes": ["4.5 Gal", "18 Gal"],
        "aliases": ["lightweight mud", "lw compound"],
        "unit": "BUCKET",
        "definition": "Low-shrink lighter compound for the finish coats.",
    },
    {
        "canonical": "Topping Compound",
        "suffixes": ["4.5 Gal"],
        "aliases": ["topping mud", "finish compound"],
        "unit": "BUCKET",
        "definition": "Smooth finish compound for the final coat over taped joints.",
    },
    {
        "canonical": "Setting Joint Compound",
        "suffixes": ["5 Minute", "20 Minute", "45 Minute", "90 Minute"],
        "aliases": ["hot mud", "setting mud", "powder compound"],
        "unit": "BAG",
        "definition": "Powdered fast-setting compound for first coats; sets in 5-90 minutes.",
    },
    {
        "canonical": "Paper Drywall Tape",
        "suffixes": ["2.1 in", "250 ft Roll"],
        "aliases": ["paper tape", "drywall tape"],
        "unit": "ROLL",
        "definition": "Perforated or non-perforated paper tape embedded in mud at joints.",
    },
    {
        "canonical": "Fiberglass Mesh Tape",
        "suffixes": ["2 in", "300 ft Roll"],
        "aliases": ["mesh tape", "fiberglass tape"],
        "unit": "ROLL",
        "definition": "Self-adhesive mesh tape used with setting compound.",
    },
    {
        "canonical": "Metal Corner Bead",
        "suffixes": ["3/4 in", "1 in", "Bullnose"],
        "aliases": ["corner bead", "metal bead", "outside corner"],
        "unit": "EA",
        "definition": "Galvanized bead that reinforces outside corners.",
    },
    {
        "canonical": "Paper-Faced Corner Bead",
        "suffixes": ["3/4 in", "1-1/4 in"],
        "aliases": ["paper corner bead", "flexible corner"],
        "unit": "EA",
        "definition": "Bead with paper flanges for a flush, crack-resistant corner.",
    },
    {
        "canonical": "Vinyl Corner Bead",
        "suffixes": ["8 ft", "10 ft"],
        "aliases": ["vinyl bead", "plastic corner bead"],
        "unit": "EA",
        "definition": "Rust-proof vinyl bead for exterior and moisture-prone corners.",
    },
    {
        "canonical": "Drywall Trim",
        "suffixes": ["L-Bead", "J-Bead"],
        "aliases": ["drywall edge", "casing bead"],
        "unit": "EA",
        "definition": "Edge trim that finishes exposed drywall ends.",
    },
    {
        "canonical": "Drywall Screws",
        "suffixes": ["1-1/4 in", "1-5/8 in", "2 in", "2-1/2 in"],
        "aliases": ["drywall screw", "sheetrock screw", "gyp screw"],
        "unit": "BOX",
        "definition": "Phosphate-coated bugle-head screws that hang gypsum board.",
    },
    {
        "canonical": "Drywall Texture Knockdown",
        "suffixes": ["Light", "Medium", "Heavy"],
        "aliases": ["knockdown", "knock down texture"],
        "unit": "SF",
        "definition": "Sprayed texture knocked flat with a knife for a mottled finish.",
    },
    {
        "canonical": "Orange Peel Texture",
        "suffixes": ["Fine", "Coarse"],
        "aliases": ["orange peel", "splatter texture"],
        "unit": "SF",
        "definition": "Fine sprayed texture that hides imperfections with a soft pebbled face.",
    },
    {
        "canonical": "Smooth Finish Texture",
        "suffixes": ["Level 4", "Level 5"],
        "aliases": ["smooth wall", "smooth texture", "level 5 finish"],
        "unit": "SF",
        "definition": "Fully sanded flat finish; Level 5 adds a skim coat for critical light.",
    },
    {
        "canonical": "Popcorn Ceiling Texture",
        "suffixes": ["Spray", "Patch"],
        "aliases": ["popcorn ceiling", "acoustic ceiling", "cottage cheese ceiling"],
        "unit": "SF",
        "definition": "Stipple acoustic texture; mostly removed from modern homes.",
    },

    # ---- Paint, primers & brands -----------------------------------------------
    {
        "canonical": "Interior Latex Paint",
        "suffixes": ["Flat", "Eggshell", "Satin", "Semi-Gloss", "Gloss"],
        "aliases": ["interior paint", "wall paint", "latex paint", "acrylic paint"],
        "unit": "GAL",
        "definition": "Water-based interior wall and trim paint; sheen rises flat to gloss.",
    },
    {
        "canonical": "Interior Enamel Paint",
        "suffixes": ["Satin", "Semi-Gloss", "Gloss"],
        "aliases": ["enamel", "trim enamel", "cabinet paint"],
        "unit": "GAL",
        "definition": "Durable enamel for trim, doors, and cabinets.",
    },
    {
        "canonical": "Exterior Latex Paint",
        "suffixes": ["Flat", "Satin", "Semi-Gloss"],
        "aliases": ["exterior paint", "house paint", "exterior latex"],
        "unit": "GAL",
        "definition": "Weather-resistant exterior paint for siding and trim.",
    },
    {
        "canonical": "Ceiling Paint",
        "suffixes": ["Flat", "Matte"],
        "aliases": ["ceiling paint", "flat ceiling"],
        "unit": "GAL",
        "definition": "High-hide flat paint formulated for ceilings.",
    },
    {
        "canonical": "Drywall Primer",
        "suffixes": ["PVA 5 Gal", "PVA 1 Gal", "Bonding", "Stain Blocking"],
        "aliases": ["primer", "drywall primer", "pva primer"],
        "unit": "GAL",
        "definition": "Sealing primer that evens out drywall suction before finish coats.",
        "phonetic": "PRY-mer",
        "ipa": "/ˈpraɪmər/",
    },
    {
        "canonical": "Floor Paint",
        "suffixes": ["Latex", "Epoxy"],
        "aliases": ["floor paint", "garage floor paint"],
        "unit": "GAL",
        "definition": "Hard-wearing paint for concrete floors and garage slabs.",
    },
    {
        "canonical": "Chalk Paint",
        "suffixes": ["Standard", "Matte"],
        "aliases": ["chalk paint", "chalky finish"],
        "unit": "GAL",
        "definition": "Furniture paint that needs no primer and distresses easily.",
    },
    {
        "canonical": "Masonry Paint",
        "suffixes": ["Flat", "Elastomeric"],
        "aliases": ["masonry paint", "block paint", "stucco paint"],
        "unit": "GAL",
        "definition": "Breathable paint for block, brick, and stucco.",
    },
    {
        "canonical": "Sherwin-Williams Paint",
        "suffixes": ["Duration Interior Flat", "Duration Interior Eggshell", "Duration Exterior Flat", "SuperPaint Interior", "Emerald Interior", "Cashmere Interior"],
        "aliases": ["sherwin williams", "sherwin", "sw paint"],
        "unit": "GAL",
        "definition": "Sherwin-Williams premium paint lines: Duration, SuperPaint, Emerald, Cashmere.",
        "phonetic": "SHUR-win WIL-yums",
        "ipa": "/ˈʃɜːrwɪn ˈwɪljəmz/",
    },
    {
        "canonical": "Benjamin Moore Paint",
        "suffixes": ["Regal Interior", "Aura Interior", "Ben Interior", "Advance Cabinet"],
        "aliases": ["benjamin moore", "ben moore", "regal select"],
        "unit": "GAL",
        "definition": "Benjamin Moore premium paints including Regal Select and Aura.",
        "phonetic": "BEN-juh-min MOOR",
        "ipa": "/ˈbɛndʒəmɪn mʊər/",
    },
    {
        "canonical": "Behr Paint",
        "suffixes": ["Premium Plus Interior", "Premium Plus Exterior", "Marquee Interior"],
        "aliases": ["behr paint", "home depot paint"],
        "unit": "GAL",
        "definition": "Behr premium paint sold at Home Depot.",
        "phonetic": "BAIR",
        "ipa": "/bɛər/",
    },
    {
        "canonical": "PPG Paint",
        "suffixes": ["Speedhide Interior", "Timeless Interior"],
        "aliases": ["ppg paint", "pittsburgh paint"],
        "unit": "GAL",
        "definition": "PPG Speedhide and Timeless interior paints.",
        "phonetic": "PEE PEE JEE",
        "ipa": "/piː piː dʒiː/",
    },
    {
        "canonical": "Valspar Paint",
        "suffixes": ["Signature Interior", "Reserve Interior"],
        "aliases": ["valspar", "lowe's paint"],
        "unit": "GAL",
        "definition": "Valspar paint sold at Lowe's.",
        "phonetic": "VAL-spar",
        "ipa": "/ˈvælspɑːr/",
    },
    {
        "canonical": "Painters Caulk",
        "suffixes": ["10 oz", "28 oz", "Big Stretch", "Siliconized Latex"],
        "aliases": ["caulk", "paintable caulk", "acrylic caulk"],
        "unit": "TUBE",
        "definition": "Paintable acrylic latex caulk for trim and drywall gaps.",
    },
    {
        "canonical": "Spackle",
        "suffixes": ["Ready Mixed", "Lightweight", "Fast Dry"],
        "aliases": ["spackle", "drywall patch", "spackling"],
        "unit": "TUBE",
        "definition": "Pink-dries-white hole filler for small dings and nail pops.",
    },
    {
        "canonical": "Drywall Patch Kit",
        "suffixes": ["6 in", "8 in", "Wall Repair"],
        "aliases": ["wall patch", "mesh patch", "drywall repair"],
        "unit": "EA",
        "definition": "Self-adhesive mesh patch with compound for holes up to 8 inches.",
    },

    # ---- Trim boards & profiles ------------------------------------------------
    {
        "canonical": "MDF Trim Board",
        "suffixes": ["1x2", "1x3", "1x4", "1x6", "1x8"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["mdf trim", "medium density fiberboard", "mdf"],
        "unit": "LF",
        "definition": "Smooth paintable MDF board for base, casing, and crown.",
    },
    {
        "canonical": "Pine Trim Board",
        "suffixes": ["1x2", "1x3", "1x4", "1x6", "1x8"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["pine trim", "finger joint pine", "clear pine"],
        "unit": "LF",
        "definition": "Knot-free finger-jointed pine for paint-grade trim.",
    },
    {
        "canonical": "Poplar Trim Board",
        "suffixes": ["1x2", "1x3", "1x4", "1x6"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["poplar", "poplar trim"],
        "unit": "LF",
        "definition": "Straight stable hardwood trim that paints beautifully.",
    },
    {
        "canonical": "PVC Trim Board",
        "suffixes": ["1x4", "1x6", "1x8"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["pvc trim", "azek", "cellular pvc"],
        "unit": "LF",
        "definition": "Cellular PVC trim that never rots for exterior use.",
    },
    {
        "canonical": "Baseboard Molding",
        "suffixes": ["3-1/4 MDF", "4-1/4 MDF", "5-1/4 MDF", "4-1/4 Pine"],
        "aliases": ["baseboard", "base molding", "base trim"],
        "unit": "LF",
        "definition": "Floor-level trim that covers the drywall-to-floor joint.",
    },
    {
        "canonical": "Door Casing",
        "suffixes": ["2-1/4 MDF", "3-1/4 MDF", "4-1/4 MDF", "2-1/4 Pine"],
        "aliases": ["casing", "door trim", "window casing"],
        "unit": "LF",
        "definition": "Trim that frames doors and windows with a beveled profile.",
    },
    {
        "canonical": "Crown Molding",
        "suffixes": ["3-5/8 MDF", "4-5/8 MDF", "5-1/4 MDF", "4-1/4 Pine"],
        "aliases": ["crown", "crown molding", "cornice"],
        "unit": "LF",
        "definition": "Angled ceiling trim that dresses the top of walls.",
    },
    {
        "canonical": "Shoe Molding",
        "suffixes": ["1/2 MDF", "1/2 Pine"],
        "aliases": ["shoe molding", "quarter round", "toe molding"],
        "unit": "LF",
        "definition": "Small rounded trim that covers the baseboard-to-floor gap.",
    },
    {
        "canonical": "Chair Rail",
        "suffixes": ["2-1/4 MDF", "3-1/4 MDF"],
        "aliases": ["chair rail", "wainscot rail"],
        "unit": "LF",
        "definition": "Horizontal trim at wainscot height that protects the wall.",
    },
    {
        "canonical": "Door Stop Molding",
        "suffixes": ["7/16 MDF", "7/16 Pine"],
        "aliases": ["door stop", "stop molding"],
        "unit": "LF",
        "definition": "Thin trim inside a jamb that stops the door leaf.",
    },
    {
        "canonical": "Cove Molding",
        "suffixes": ["3/4 MDF", "3/4 Pine"],
        "aliases": ["cove", "cove trim"],
        "unit": "LF",
        "definition": "Concave trim used at wall-to-ceiling and shelf transitions.",
    },
    {
        "canonical": "Plinth Block",
        "suffixes": ["6 x 12", "8 x 12"],
        "aliases": ["plinth", "door plinth", "jamb block"],
        "unit": "EA",
        "definition": "Solid block at the base of door casing for a stately look.",
    },
    {
        "canonical": "Rope Molding",
        "suffixes": ["3/4", "1"],
        "aliases": ["rope molding", "beaded trim"],
        "unit": "LF",
        "definition": "Decorative trim with a twisted rope profile.",
    },

    # ---- Drywall tools ----------------------------------------------------------
    {
        "canonical": "Taping Knife",
        "suffixes": ["4 in", "6 in", "8 in", "10 in", "12 in", "14 in"],
        "aliases": ["taping knife", "joint knife", "drywall knife", "mud knife"],
        "unit": "EA",
        "definition": "Flexible steel knife that lays compound and feathers joints.",
    },
    {
        "canonical": "Mud Pan",
        "suffixes": ["10 in", "12 in"],
        "aliases": ["mud pan", "compound pan"],
        "unit": "EA",
        "definition": "Stainless pan that holds compound for taping.",
    },
    {
        "canonical": "Inside Corner Trowel",
        "suffixes": ["Standard", "Flexible"],
        "aliases": ["corner trowel", "inside corner"],
        "unit": "EA",
        "definition": "Angled trowel for finishing inside corners in one pass.",
    },
    {
        "canonical": "Drywall Hawk",
        "suffixes": ["12 in", "14 in"],
        "aliases": ["hawk", "mud hawk", "plasterer hawk"],
        "unit": "EA",
        "definition": "Flat hand board that holds compound while working.",
    },
    {
        "canonical": "Drywall Banjo",
        "suffixes": ["Standard", "Box"],
        "aliases": ["banjo", "tape banjo", "tape dispenser"],
        "unit": "EA",
        "definition": "Tool that coats and dispenses tape for fast flat joints.",
    },
    {
        "canonical": "Drywall Lift",
        "suffixes": ["11 ft", "13 ft"],
        "aliases": ["panel lift", "drywall hoist", "sheetrock lift"],
        "unit": "EA",
        "definition": "Panel hoist that raises a sheet to the ceiling solo.",
    },
    {
        "canonical": "Drywall Stilts",
        "suffixes": ["18-30 in", "30-48 in"],
        "aliases": ["stilts", "drywall stilts"],
        "unit": "EA",
        "definition": "Adjustable walking stilts for ceiling work.",
    },
    {
        "canonical": "Utility Knife",
        "suffixes": ["Standard", "Retractable"],
        "aliases": ["utility knife", "box cutter", "razor knife"],
        "unit": "EA",
        "definition": "Folding blade knife for scoring drywall and trimming tape.",
    },
    {
        "canonical": "Drywall T-Square",
        "suffixes": ["48 in", "54 in"],
        "aliases": ["t square", "drywall square", "cutting square"],
        "unit": "EA",
        "definition": "Aluminum square that guides scoring cuts across a sheet.",
    },
    {
        "canonical": "Keyhole Saw",
        "suffixes": ["6 in", "10 in"],
        "aliases": ["keyhole saw", "drywall saw", "jab saw"],
        "unit": "EA",
        "definition": "Small pointed saw for cutting outlet and light openings.",
    },
    {
        "canonical": "Dust Control Sander",
        "suffixes": ["Manual", "Powered"],
        "aliases": ["drywall sander", "pole sander", "power sander"],
        "unit": "EA",
        "definition": "Sander with a dust hose for finish sanding ceilings and walls.",
    },
    {
        "canonical": "Drywall Dust Barrier",
        "suffixes": ["Doorway", "Zip Wall"],
        "aliases": ["dust barrier", "dust containment", "zipwall"],
        "unit": "EA",
        "definition": "Temporary zipper wall that keeps dust out of the rest of the house.",
    },
    {
        "canonical": "Corner Patch",
        "suffixes": ["Metal", "Plastic"],
        "aliases": ["corner patch", "patch corner"],
        "unit": "EA",
        "definition": "Preformed corner patch for repairing damaged outside corners.",
    },
    # ---- Sanding -----------------------------------------------------------------
    {
        "canonical": "Drywall Sandpaper",
        "suffixes": ["60 Grit", "100 Grit", "120 Grit", "150 Grit", "180 Grit", "220 Grit", "320 Grit"],
        "aliases": ["sandpaper", "sanding paper"],
        "unit": "PK",
        "definition": "Open-coat abrasive paper for sanding compound.",
    },
    {
        "canonical": "Sanding Screen",
        "suffixes": ["100 Grit", "120 Grit"],
        "aliases": ["sanding screen", "drywall screen"],
        "unit": "PK",
        "definition": "Mesh abrasive that won't clog on compound.",
    },
    {
        "canonical": "Sanding Sponge",
        "suffixes": ["Coarse", "Fine", "Assorted"],
        "aliases": ["sanding sponge", "flexible sanding block"],
        "unit": "EA",
        "definition": "Flexible foam block for corners and curved surfaces.",
    },
    {
        "canonical": "Pole Sander",
        "suffixes": ["Standard", "With Adapter"],
        "aliases": ["pole sander", "ceilings sander"],
        "unit": "EA",
        "definition": "Padded sanding head on an extension pole.",
    },
    {
        "canonical": "Sanding Block",
        "suffixes": ["Rubber", "Cork"],
        "aliases": ["sanding block", "sand block"],
        "unit": "EA",
        "definition": "Hand block that holds sandpaper for flat sanding.",
    },
    {
        "canonical": "Sanding Discs",
        "suffixes": ["5 in 80 Grit", "5 in 120 Grit", "6 in 80 Grit", "6 in 220 Grit"],
        "aliases": ["sanding disc", "hook and loop disc"],
        "unit": "PK",
        "definition": "Hook-and-loop discs for a random-orbit sander.",
    },

    # ---- Painting supplies & texture gear ---------------------------------------
    {
        "canonical": "Paint Roller Frame",
        "suffixes": ["9 in", "18 in"],
        "aliases": ["roller frame", "paint roller"],
        "unit": "EA",
        "definition": "Wire cage that mounts a roller cover.",
    },
    {
        "canonical": "Paint Roller Cover",
        "suffixes": ["3/8 in Nap", "1/2 in Nap", "3/4 in Nap", "1/4 in Smooth"],
        "aliases": ["roller cover", "roller sleeve"],
        "unit": "EA",
        "definition": "Absorbent sleeve sized by nap for the surface being painted.",
    },
    {
        "canonical": "Paint Brush",
        "suffixes": ["2 in", "2-1/2 in", "3 in", "Angled Sash"],
        "aliases": ["paint brush", "sash brush", "trim brush"],
        "unit": "EA",
        "definition": "Synthetic bristle brush for trim and cutting in.",
    },
    {
        "canonical": "Paint Tray",
        "suffixes": ["Standard", "With Liner"],
        "aliases": ["paint tray", "roller tray"],
        "unit": "EA",
        "definition": "Ribbed tray that loads a roller cover.",
    },
    {
        "canonical": "Extension Pole",
        "suffixes": ["4-8 ft", "8-24 ft"],
        "aliases": ["extension pole", "roller pole"],
        "unit": "EA",
        "definition": "Threaded pole that extends the roller to ceilings.",
    },
    {
        "canonical": "Paint Edger",
        "suffixes": ["Standard", "Refill Pads"],
        "aliases": ["paint edger", "edging tool"],
        "unit": "EA",
        "definition": "Pad tool with guide wheels for straight edges.",
    },
    {
        "canonical": "Canvas Drop Cloth",
        "suffixes": ["4 x 12", "6 x 9", "9 x 12"],
        "aliases": ["drop cloth", "canvas drop"],
        "unit": "EA",
        "definition": "Reusable canvas floor protection that won't slip.",
    },
    {
        "canonical": "Painter's Tape",
        "suffixes": ["1.4 in", "1.88 in", "2.5 in"],
        "aliases": ["masking tape", "painters tape", "blue tape"],
        "unit": "ROLL",
        "definition": "Clean-release masking tape for crisp paint lines.",
    },
    {
        "canonical": "5 Gallon Paint Bucket",
        "suffixes": ["Standard", "With Grid"],
        "aliases": ["5 gallon bucket", "paint bucket"],
        "unit": "EA",
        "definition": "Five-gallon pail that holds box paint and a roller grid.",
    },
    {
        "canonical": "Paint Strainer",
        "suffixes": ["Standard", "Disposable"],
        "aliases": ["paint strainer", "filter cone"],
        "unit": "EA",
        "definition": "Cone filter that strains paint before sprayer use.",
    },
    {
        "canonical": "Airless Paint Sprayer",
        "suffixes": ["Handheld", "Pro 460", "Titan 440"],
        "aliases": ["paint sprayer", "airless sprayer", "graco"],
        "unit": "EA",
        "definition": "High-pressure pump that sprays paint fast for walls and fences.",
    },

    {
        "canonical": "Texture Sprayer Hopper",
        "suffixes": ["With Gun", "Spray Texture"],
        "aliases": ["texture hopper", "texture gun"],
        "unit": "EA",
        "definition": "Hopper gun that sprays drywall texture from an air compressor.",
    },
    {
        "canonical": "Texture Scraper",
        "suffixes": ["8 in", "12 in"],
        "aliases": ["texture scraper", "popcorn scraper"],
        "unit": "EA",
        "definition": "Bladed tool for scraping popcorn texture off ceilings.",
    },
    {
        "canonical": "Caulk Gun",
        "suffixes": ["Standard", "Drip Free"],
        "aliases": ["caulk gun", "sealant gun"],
        "unit": "EA",
        "definition": "Tool that pushes a caulk tube bead evenly.",
    },
    {
        "canonical": "Kilz Primer",
        "suffixes": ["Original", "Premium"],
        "aliases": ["kilz", "stain blocking primer"],
        "unit": "GAL",
        "definition": "Stain-blocking primer that hides water and smoke marks.",
    },
    {
        "canonical": "Zinsser Primer",
        "suffixes": ["Bullseye 123", "B-I-N Shellac"],
        "aliases": ["zinsser", "shellac primer"],
        "unit": "GAL",
        "definition": "Zinsser primers; B-I-N shellac seals knots and odors.",
        "phonetic": "ZIN-ser",
        "ipa": "/ˈzɪnsər/",
    },
    {
        "canonical": "Cabinet Paint",
        "suffixes": ["Satin", "Semi-Gloss"],
        "aliases": ["cabinet paint", "furniture paint"],
        "unit": "GAL",
        "definition": "Self-leveling paint formulated for kitchen cabinets.",
    },
    {
        "canonical": "Paint Thinner",
        "suffixes": ["1 Qt", "1 Gal"],
        "aliases": ["paint thinner", "mineral spirits", "solvent"],
        "unit": "GAL",
        "definition": "Solvent for cleaning oil paint and thinning enamel.",
    },
    {
        "canonical": "Trim Nails",
        "suffixes": ["15 Gauge", "16 Gauge", "18 Gauge"],
        "aliases": ["finish nails", "trim nails", "brad nails"],
        "unit": "BOX",
        "definition": "Collated finish nails for base, casing, and crown.",
    },
    {
        "canonical": "Wood Filler",
        "suffixes": ["Stainable", "Paintable"],
        "aliases": ["wood filler", "wood putty", "patch and paint"],
        "unit": "TUBE",
        "definition": "Filler that repairs nail holes and dents in trim.",
    },
    {
        "canonical": "Drywall Adhesive",
        "suffixes": ["10 oz", "28 oz"],
        "aliases": ["drywall adhesive", "panel adhesive", "glue on drywall"],
        "unit": "TUBE",
        "definition": "Construction adhesive for gluing board to studs (glue-n-screw).",
    },
    {
        "canonical": "Masking Film",
        "suffixes": ["12 in", "24 in"],
        "aliases": ["plastic sheeting", "masking plastic"],
        "unit": "ROLL",
        "definition": "Taped plastic film that protects floors and furniture.",
    },
    {
        "canonical": "Texture Spray Can",
        "suffixes": ["Orange Peel", "Knockdown"],
        "aliases": ["spray texture", "touch up texture"],
        "unit": "CAN",
        "definition": "Aerosol texture for small drywall repairs.",
    },

    {
        "canonical": "Skip Trowel Texture",
        "suffixes": ["Light", "Heavy"],
        "aliases": ["skip trowel", "spanish texture"],
        "unit": "SF",
        "definition": "Hand-applied swirled texture with a plaster trowel.",
    },
    {
        "canonical": "Splatter Texture",
        "suffixes": ["Fine", "Coarse"],
        "aliases": ["splatter", "popcorn splatter"],
        "unit": "SF",
        "definition": "Heavy sprayed texture before knocking down or flat finishing.",
    },
    {
        "canonical": "Drywall Screw Gun",
        "suffixes": ["Standard", "Collated"],
        "aliases": ["screw gun", "drywall gun", "screw driver"],
        "unit": "EA",
        "definition": "High-speed screw gun with a depth nose for drywall.",
    },
    {
        "canonical": "Paddle Mixer",
        "suffixes": ["Standard", "Heavy Duty"],
        "aliases": ["paddle mixer", "mud mixer", "drill paddle"],
        "unit": "EA",
        "definition": "Drill-mounted paddle that mixes joint compound.",
    },
    {
        "canonical": "Acoustic Caulk",
        "suffixes": ["10 oz", "28 oz"],
        "aliases": ["acoustic sealant", "sound caulk"],
        "unit": "TUBE",
        "definition": "Latex sealant that stops air and sound through gaps.",
    },
    {
        "canonical": "Spray Can Primer",
        "suffixes": ["White", "Bonding"],
        "aliases": ["spray primer", "aerosol primer"],
        "unit": "CAN",
        "definition": "Aerosol primer for small jobs and touch-ups.",
    },
    {
        "canonical": "Brush Cleaner",
        "suffixes": ["Water Based", "Solvent Based"],
        "aliases": ["brush cleaner", "roller cleaner"],
        "unit": "JAR",
        "definition": "Restores dried paint brushes and rollers.",
    },
    {
        "canonical": "Stepladder",
        "suffixes": ["4 ft", "6 ft", "8 ft"],
        "aliases": ["step ladder", "ladder"],
        "unit": "EA",
        "definition": "Fiberglass stepladder for painting and drywall work.",
    },
    {
        "canonical": "Large Hole Patch",
        "suffixes": ["12 in", "24 in"],
        "aliases": ["hole patch", "big hole repair"],
        "unit": "EA",
        "definition": "Backer board and mesh system for repairing large drywall holes.",
    },
    {
        "canonical": "Plaster Patch",
        "suffixes": ["Ready Mix", "Powder"],
        "aliases": ["plaster patch", "spackle patch"],
        "unit": "TUBE",
        "definition": "Fast-drying patch compound for plaster and drywall repairs.",
    },
    {
        "canonical": "Stucco Patch",
        "suffixes": ["10 oz", "Quart"],
        "aliases": ["stucco patch", "exterior patch"],
        "unit": "TUBE",
        "definition": "Textured patch for repairing stucco and EIFS.",
    },
    {
        "canonical": "Corner Guard",
        "suffixes": ["8 ft", "10 ft"],
        "aliases": ["corner guard", "protective corner"],
        "unit": "EA",
        "definition": "Rigid L-shaped protector for high-traffic corners.",
    },
]

