"""Electrical lexicon families: wire/cable, conduit, devices, breakers,
panels, lighting, and the STT-critical brand names (Square D, Leviton...)."""

TRADE = "Electrical"

FAMILIES = [
    # ---- Wire & cable ---------------------------------------------------------
    {
        "canonical": "NM Cable Romex",
        "suffixes": ["14/2 wG", "14/3 wG", "12/2 wG", "12/3 wG", "10/2 wG", "10/3 wG", "8/3 wG", "6/3 wG"],
        "lengths": ["250 ft", "500 ft"],
        "suffix_aliases": {"14/2 wG": ["14/2", "romex 14/2"], "12/2 wG": ["12/2", "romex 12/2"],
                           "10/2 wG": ["10/2 romex"], "10/3 wG": ["10/3 romex"]},
        "aliases": ["romex", "nm cable", "nonmetallic cable", "sheathed cable"],
        "unit": "LF",
        "definition": "Nonmetallic sheathed cable (NM-B) for branch circuits in residential framing.",
    },
    {
        "canonical": "THHN Wire",
        "suffixes": ["14 AWG", "12 AWG", "10 AWG", "8 AWG", "6 AWG", "4 AWG", "2 AWG", "1 AWG"],
        "lengths": ["500 ft", "1000 ft"],
        "aliases": ["thhn", "stranded wire", "building wire"],
        "unit": "LF",
        "definition": "Single-conductor thermoplastic wire pulled in conduit for feeders and branch circuits.",
    },
    {
        "canonical": "Service Entrance Cable",
        "suffixes": ["1/0", "2/0", "3/0", "4/0"],
        "lengths": ["100 ft"],
        "aliases": ["ser cable", "service cable", "seu"],
        "unit": "LF",
        "definition": "Large SE cable from the meter to the main panel or a subfeed.",
    },
    {
        "canonical": "EMT Conduit",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/4\"", "1-1/2\"", "2\""],
        "lengths": ["10 ft", "20 ft"],
        "aliases": ["emt", "thinwall conduit", "electrical metallic tubing"],
        "unit": "LF",
        "definition": "Galvanized steel thin-wall conduit for exposed and underground-in-wall wiring.",
    },
    {
        "canonical": "PVC Conduit",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/4\"", "1-1/2\"", "2\""],
        "lengths": ["10 ft", "20 ft"],
        "aliases": ["pvc conduit", "schedule 40 conduit", "electrical pvc"],
        "unit": "LF",
        "definition": "Rigid gray PVC raceway for underground and damp-location wiring.",
    },
    {
        "canonical": "Flexible Metal Conduit",
        "suffixes": ["3/8\"", "1/2\"", "3/4\"", "1\""],
        "lengths": ["25 ft", "100 ft"],
        "aliases": ["fmc", "flex conduit", "greenfield"],
        "unit": "LF",
        "definition": "Spiral-wound metal flex used for last-foot motor and appliance hookups.",
    },
    {
        "canonical": "MC Cable",
        "suffixes": ["14/2", "12/2", "12/3", "10/2"],
        "lengths": ["250 ft"],
        "aliases": ["metal clad cable", "mc cable", "armored cable"],
        "unit": "LF",
        "definition": "Armored metal-clad cable for commercial and exposed residential runs.",
    },
    {
        "canonical": "Low Voltage Wire",
        "suffixes": ["18/2", "16/2", "14/2"],
        "lengths": ["500 ft"],
        "aliases": ["low voltage", "thermostat wire", "doorbell wire"],
        "unit": "LF",
        "definition": "Stranded 18-14 gauge wire for thermostats, doorbells, and controls.",
    },
    {
        "canonical": "Cat6 Ethernet Cable",
        "suffixes": ["Solid 500 ft", "Stranded 1000 ft"],
        "aliases": ["cat6", "ethernet cable", "network cable"],
        "unit": "LF",
        "definition": "Gigabit-rated network cable run for data drops.",
    },
    {
        "canonical": "Coaxial Cable RG6",
        "suffixes": ["100 ft", "500 ft"],
        "aliases": ["rg6", "coax", "coax cable"],
        "unit": "LF",
        "definition": "Quad-shield coax for TV and internet drops.",
    },
    {
        "canonical": "Speaker Wire",
        "suffixes": ["16/2", "14/2", "12/2"],
        "lengths": ["500 ft"],
        "aliases": ["speaker wire", "in wall speaker cable"],
        "unit": "LF",
        "definition": "CL2-rated in-wall speaker wire for whole-house audio.",
    },
    {
        "canonical": "Fish Tape",
        "suffixes": ["25 ft", "100 ft"],
        "aliases": ["fish tape", "wire puller", "conduit fish"],
        "unit": "EA",
        "definition": "Spring-steel tape used to pull wire through walls and conduit.",
    },
    # ---- Devices (receptacles & switches) --------------------------------------
    {
        "canonical": "Duplex Receptacle",
        "suffixes": ["15A White", "15A Ivory", "20A White", "20A Ivory"],
        "aliases": ["duplex outlet", "receptacle", "outlet", "wall outlet", "plug"],
        "unit": "EA",
        "definition": "Standard 15 or 20 amp duplex outlet for branch circuits.",
    },
    {
        "canonical": "GFCI Receptacle",
        "suffixes": ["15A", "20A"],
        "aliases": ["gfci", "gfci outlet", "ground fault outlet", "gfci receptacle"],
        "unit": "EA",
        "definition": "Ground-fault protected outlet required in kitchens, baths, and outdoors.",
    },
    {
        "canonical": "AFCI Outlet",
        "suffixes": ["15A", "20A"],
        "aliases": ["afci", "arc fault outlet", "arc fault receptacle"],
        "unit": "EA",
        "definition": "Arc-fault protected outlet for bedrooms; alternative to AFCI breakers.",
    },
    {
        "canonical": "240V Receptacle",
        "suffixes": ["20A", "30A", "50A"],
        "aliases": ["240v outlet", "dryer outlet", "range outlet", "nema 14-50"],
        "unit": "EA",
        "definition": "Heavy 240-volt outlet for dryers, ranges, EV chargers, and welders.",
    },
    {
        "canonical": "Weatherproof Receptacle",
        "suffixes": ["In-Use Cover", "Duplex"],
        "aliases": ["weatherproof outlet", "wp receptacle", "exterior outlet"],
        "unit": "EA",
        "definition": "Gasketed outdoor outlet with a bubble cover for code compliance.",
    },
    {
        "canonical": "Single Pole Switch",
        "suffixes": ["White", "Ivory", "Black"],
        "aliases": ["light switch", "single pole", "toggle switch"],
        "unit": "EA",
        "definition": "Standard on/off wall switch controlling one light or outlet.",
    },
    {
        "canonical": "3-Way Switch",
        "suffixes": ["White", "Ivory"],
        "aliases": ["three way switch", "3 way", "hall switch"],
        "unit": "EA",
        "definition": "Switch used in pairs to control a light from two locations.",
    },
    {
        "canonical": "4-Way Switch",
        "suffixes": ["White"],
        "aliases": ["four way switch", "4 way"],
        "unit": "EA",
        "definition": "Middle switch that lets 3+ locations control one light.",
    },
    {
        "canonical": "Dimmer Switch",
        "suffixes": ["Standard", "3-Way", "LED Compatible", "Smart"],
        "aliases": ["dimmer", "light dimmer", "lutron dimmer"],
        "unit": "EA",
        "definition": "Wall dimmer that varies light level; LED-rated models are current code.",
    },
    {
        "canonical": "Smart Switch",
        "suffixes": ["Wi-Fi", "Z-Wave", "Caseta"],
        "aliases": ["smart switch", "wifi switch", "caseta"],
        "unit": "EA",
        "definition": "App-and-voice-controlled switch for home automation.",
    },
    {
        "canonical": "Motion Sensor Switch",
        "suffixes": ["Occupancy", "Vacancy"],
        "aliases": ["motion switch", "occupancy sensor"],
        "unit": "EA",
        "definition": "Sensor switch that turns lights on when the room is occupied.",
    },
    {
        "canonical": "Timer Switch",
        "suffixes": ["Digital", "Mechanical"],
        "aliases": ["timer switch", "light timer"],
        "unit": "EA",
        "definition": "Scheduled switch for lights, fans, and exterior circuits.",
    },

    # ---- Breakers & panels -----------------------------------------------------
    {
        "canonical": "Square D QO Breaker",
        "suffixes": ["15A 1P", "20A 1P", "30A 2P", "40A 2P", "50A 2P", "60A 2P"],
        "aliases": ["qo breaker", "square d breaker", "qo"],
        "unit": "EA",
        "definition": "Square D QO plug-on breaker for QO load centers.",
        "phonetic": "SKWAIR DEE",
        "ipa": "/skwɛər diː/",
    },
    {
        "canonical": "Square D Homeline Breaker",
        "suffixes": ["15A 1P", "20A 1P", "30A 2P", "40A 2P", "50A 2P", "60A 2P"],
        "aliases": ["homeline breaker", "homeline"],
        "unit": "EA",
        "definition": "Square D Homeline breaker for the value-priced Homeline line.",
        "phonetic": "HOME-line",
        "ipa": "/ˈhoʊm.laɪn/",
    },
    {
        "canonical": "Eaton CH Breaker",
        "suffixes": ["15A 1P", "20A 1P", "30A 2P", "40A 2P", "50A 2P", "60A 2P"],
        "aliases": ["eaton breaker", "ch breaker", "cutler hammer"],
        "unit": "EA",
        "definition": "Eaton CH (Cutler-Hammer) breaker for CH load centers.",
        "phonetic": "EE-tun",
        "ipa": "/ˈiːtən/",
    },
    {
        "canonical": "Eaton BR Breaker",
        "suffixes": ["15A 1P", "20A 1P", "30A 2P", "40A 2P", "50A 2P", "60A 2P"],
        "aliases": ["br breaker", "type br"],
        "unit": "EA",
        "definition": "Eaton BR breaker, interchangeable with many residential panels.",
        "phonetic": "EE-tun",
        "ipa": "/ˈiːtən/",
    },
    {
        "canonical": "Siemens Breaker",
        "suffixes": ["15A 1P", "20A 1P", "30A 2P", "40A 2P", "50A 2P", "60A 2P"],
        "aliases": ["siemens breaker", "type qp"],
        "unit": "EA",
        "definition": "Siemens type QP breaker for Siemens and Murray panels.",
        "phonetic": "SEE-mens",
        "ipa": "/ˈsiːməns/",
    },
    {
        "canonical": "GFCI Breaker",
        "suffixes": ["20A 1P", "30A 2P", "50A 2P"],
        "aliases": ["gfci breaker", "ground fault breaker"],
        "unit": "EA",
        "definition": "Combination breaker that protects the whole circuit against ground faults.",
    },
    {
        "canonical": "AFCI Breaker",
        "suffixes": ["15A 1P", "20A 1P"],
        "aliases": ["afci breaker", "arc fault breaker"],
        "unit": "EA",
        "definition": "Arc-fault breaker required on bedroom and living-area branch circuits.",
    },
    {
        "canonical": "Main Breaker",
        "suffixes": ["100A", "150A", "200A"],
        "aliases": ["main breaker", "service disconnect"],
        "unit": "EA",
        "definition": "The single disconnect that shuts off the whole panel.",
    },
    {
        "canonical": "Square D Load Center",
        "suffixes": ["100A 20-Space", "200A 30-Space", "200A 40-Space"],
        "aliases": ["load center", "breaker panel", "panel board", "panel"],
        "unit": "EA",
        "definition": "Square D main-breaker load center with the space for a full house.",
        "phonetic": "SKWAIR DEE",
        "ipa": "/skwɛər diː/",
    },
    {
        "canonical": "Eaton Load Center",
        "suffixes": ["200A 30-Space", "200A 40-Space"],
        "aliases": ["eaton panel", "ch panel"],
        "unit": "EA",
        "definition": "Eaton main breaker load center.",
        "phonetic": "EE-tun",
        "ipa": "/ˈiːtən/",
    },
    {
        "canonical": "Sub Panel",
        "suffixes": ["60A", "100A"],
        "aliases": ["subpanel", "sub panel", "lug panel"],
        "unit": "EA",
        "definition": "Secondary panel fed by the main for a shop, garage, or addition.",
    },
    {
        "canonical": "Panel Cover",
        "suffixes": ["30-Space", "40-Space"],
        "aliases": ["panel door", "panelboard cover"],
        "unit": "EA",
        "definition": "Dead-front cover with a door for a load center.",
    },

    # ---- Boxes & covers --------------------------------------------------------
    {
        "canonical": "Single Gang Box",
        "suffixes": ["PVC", "Metal", "Old Work"],
        "aliases": ["switch box", "outlet box", "single gang"],
        "unit": "EA",
        "definition": "One-device box for switches and outlets; old-work grips drywall.",
    },
    {
        "canonical": "2-Gang Box",
        "suffixes": ["Metal", "Old Work"],
        "aliases": ["double gang box", "two gang"],
        "unit": "EA",
        "definition": "Two-device box for side-by-side switches or outlets.",
    },
    {
        "canonical": "3-Gang Box",
        "suffixes": ["Metal"],
        "aliases": ["triple gang box"],
        "unit": "EA",
        "definition": "Three-device metal box for multi-switch plates.",
    },
    {
        "canonical": "4-Square Box",
        "suffixes": ["Standard", "Deep"],
        "aliases": ["four square", "4 square box"],
        "unit": "EA",
        "definition": "Square box that accepts multiple mud rings for device mounting.",
    },
    {
        "canonical": "Octagon Box",
        "suffixes": ["Ceiling", "Fan Rated"],
        "aliases": ["octagon", "ceiling box"],
        "unit": "EA",
        "definition": "Round/octagon ceiling box for light fixtures and ceiling fans.",
    },
    {
        "canonical": "Junction Box",
        "suffixes": ["4 x 4", "8 x 8 x 4", "12 x 12 x 6"],
        "aliases": ["j box", "junction", "splice box"],
        "unit": "EA",
        "definition": "Accessible box where wires are spliced or pulled through.",
    },
    {
        "canonical": "Wall Plate",
        "suffixes": ["Single", "Duplex", "Blank", "Toggle"],
        "aliases": ["switch plate", "outlet cover", "faceplate"],
        "unit": "EA",
        "definition": "Screw-on cover finishing a box around a device.",
    },
    {
        "canonical": "Weatherproof Box Cover",
        "suffixes": ["In-Use", "Bell Box"],
        "aliases": ["weatherproof cover", "bubble cover"],
        "unit": "EA",
        "definition": "Gasketed outdoor cover that allows a plug in use with the cover closed.",
    },
    # ---- Lighting ---------------------------------------------------------------
    {
        "canonical": "Recessed Light Housing",
        "suffixes": ["6 inch IC", "4 inch IC", "Air-Tight IC"],
        "aliases": ["can light housing", "recessed can", "recessed housing"],
        "unit": "EA",
        "definition": "IC-rated can housing that can be buried under insulation.",
    },
    {
        "canonical": "Recessed LED Trim",
        "suffixes": ["6 inch", "4 inch", "Wide Baffle"],
        "aliases": ["can trim", "led trim", "recessed trim"],
        "unit": "EA",
        "definition": "LED module and trim that drops into a can housing.",
    },
    {
        "canonical": "Wafer LED Light",
        "suffixes": ["4 inch", "6 inch"],
        "aliases": ["wafer light", "disc light", "recessed wafer", "slim led"],
        "unit": "EA",
        "definition": "Slim retrofit LED that mounts flush in any ceiling without a can.",
    },
    {
        "canonical": "Ceiling Fan",
        "suffixes": ["52 inch", "60 inch", "With Light Kit"],
        "aliases": ["ceiling fan", "fan", "smart fan"],
        "unit": "EA",
        "definition": "52-60 inch ceiling fan, often with integrated LED light.",
    },
    {
        "canonical": "LED Strip Light",
        "suffixes": ["16 ft", "32 ft"],
        "aliases": ["led strip", "led tape light", "accent lighting"],
        "unit": "EA",
        "definition": "Adhesive LED tape for under-cabinet and accent lighting.",
    },
    {
        "canonical": "Exterior Flood Light",
        "suffixes": ["LED", "Halogen", "Motion Activated"],
        "aliases": ["flood light", "security light", "outdoor flood"],
        "unit": "EA",
        "definition": "Weatherproof floodlight for yards and driveways.",
    },
    {
        "canonical": "Vanity Light Bar",
        "suffixes": ["2 Light", "3 Light", "4 Light"],
        "aliases": ["vanity light", "bathroom light bar"],
        "unit": "EA",
        "definition": "Multi-lamp bath bar above the mirror.",
    },
    {
        "canonical": "Shop Light",
        "suffixes": ["LED 4 ft", "LED 8 ft"],
        "aliases": ["shop light", "garage light", "linkable light"],
        "unit": "EA",
        "definition": "Linkable LED strip light for garage and workshop ceilings.",
    },

    # ---- Fittings, fasteners & service ----------------------------------------
    {
        "canonical": "Wire Nuts",
        "suffixes": ["Gray", "Blue", "Red", "Yellow", "Green"],
        "aliases": ["wire nut", "twist connector", "marrette"],
        "unit": "BOX",
        "definition": "Screw-on connectors splicing 22 AWG through 6 AWG conductors.",
    },
    {
        "canonical": "Wago Connector",
        "suffixes": ["221-412", "221-413", "221-415"],
        "aliases": ["wago", "lever connector", "push in connector"],
        "unit": "BOX",
        "definition": "Lever-nut splicing connector that needs no twisting.",
        "phonetic": "VAH-go",
        "ipa": "/ˈvɑːɡoʊ/",
    },
    {
        "canonical": "Cable Staples",
        "suffixes": ["14-2", "12-2"],
        "aliases": ["cable staple", "romex staple", "wire staple"],
        "unit": "BOX",
        "definition": "Insulated staples that secure NM cable to framing every 4-1/2 feet.",
    },
    {
        "canonical": "NM Cable Connector",
        "suffixes": ["1/2\"", "3/4\""],
        "aliases": ["nm connector", "romex connector", "cable clamp"],
        "unit": "EA",
        "definition": "Clamp fitting that terminates NM cable into a box knock-out.",
    },
    {
        "canonical": "EMT Connector",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["conduit connector", "set screw connector"],
        "unit": "EA",
        "definition": "Set-screw fitting joining EMT to a box.",
    },
    {
        "canonical": "EMT Coupling",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["conduit coupling", "emt coupler"],
        "unit": "EA",
        "definition": "Fitting that joins two lengths of EMT in a straight run.",
    },
    {
        "canonical": "Conduit Strap",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["pipe strap", "conduit hanger", "one hole strap"],
        "unit": "EA",
        "definition": "Metal strap securing conduit to walls and ceilings.",
    },
    {
        "canonical": "Conduit Bender",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["bender", "emtbender", "hickey"],
        "unit": "EA",
        "definition": "Manual tool that bends EMT into offsets and 90s.",
    },
    {
        "canonical": "Ground Rod",
        "suffixes": ["5/8 x 8 ft", "1/2 x 8 ft"],
        "aliases": ["ground rod", "grounding rod", "earth rod"],
        "unit": "EA",
        "definition": "Copper-clad rod driven into earth for the grounding electrode.",
    },
    {
        "canonical": "Ground Clamp",
        "suffixes": ["Standard", "Acorn"],
        "aliases": ["ground clamp", "grounding clamp"],
        "unit": "EA",
        "definition": "Clamp connecting the ground wire to the rod, pipe, or plate.",
    },
    {
        "canonical": "Electrical Tape",
        "suffixes": ["Black", "Red", "Yellow"],
        "aliases": ["electrical tape", "vinyl tape", "elec tape"],
        "unit": "ROLL",
        "definition": "Vinyl insulating tape for splices and phase identification.",
    },
    {
        "canonical": "Heat Shrink Tubing",
        "suffixes": ["Assorted", "Wire Size"],
        "aliases": ["heat shrink", "shrink tube"],
        "unit": "BOX",
        "definition": "Insulating tubing that shrinks around a splice with heat.",
    },
    {
        "canonical": "Meter Base",
        "suffixes": ["200A Ringless", "400A"],
        "aliases": ["meter base", "meter socket", "meter can"],
        "unit": "EA",
        "definition": "Utility meter socket mounted outside the house.",
    },
    {
        "canonical": "Service Disconnect",
        "suffixes": ["60A Non-Fused", "100A Non-Fused", "200A"],
        "aliases": ["disconnect", "ac disconnect", "kill switch"],
        "unit": "EA",
        "definition": "Lockable disconnect between the meter and panel or HVAC unit.",
    },
    {
        "canonical": "Weatherhead",
        "suffixes": ["1-1/4\"", "2\""],
        "aliases": ["weatherhead", "service head", "meter head"],
        "unit": "EA",
        "definition": "Rain cap at the top of the service mast where overhead drops enter.",
    },
    {
        "canonical": "Generator Inlet",
        "suffixes": ["30A", "50A"],
        "aliases": ["generator inlet", "gen inlet", "generator plug"],
        "unit": "EA",
        "definition": "Weatherproof male inlet that backfeeds the house from a generator.",
    },
    {
        "canonical": "Transfer Switch",
        "suffixes": ["6 Circuit", "10 Circuit"],
        "aliases": ["transfer switch", "generator switch"],
        "unit": "EA",
        "definition": "Manual switch that safely selects generator vs utility power.",
    },
    {
        "canonical": "EV Charger",
        "suffixes": ["Level 2 40A", "Level 2 50A"],
        "aliases": ["ev charger", "electric car charger", "level 2 charger"],
        "unit": "EA",
        "definition": "240-volt wall charger for electric vehicles.",
    },
    {
        "canonical": "Heat Trace Cable",
        "suffixes": ["3 ft", "30 ft"],
        "aliases": ["heat tape", "pipe heat cable", "heat trace"],
        "unit": "EA",
        "definition": "Self-regulating cable that keeps pipes from freezing.",
    },

    # ---- Brands + smart home + detectors ---------------------------------------
    {
        "canonical": "Leviton Devices",
        "suffixes": ["Decora Switch", "Decora Dimmer", "GFCI Outlet"],
        "aliases": ["leviton", "decora"],
        "unit": "EA",
        "definition": "Leviton Decora line of rocker switches, dimmers, and outlets.",
        "phonetic": "LEV-ih-ton",
        "ipa": "/ˈlɛvɪtən/",
    },
    {
        "canonical": "Lutron Lighting",
        "suffixes": ["Caseta Dimmer", "Maestro", "Pico Remote"],
        "aliases": ["lutron", "caseta"],
        "unit": "EA",
        "definition": "Lutron dimmers and wireless lighting controls.",
        "phonetic": "LOO-tron",
        "ipa": "/ˈluːtrɒn/",
    },
    {
        "canonical": "Hubbell Devices",
        "suffixes": ["Commercial Receptacle", "Locking Plug"],
        "aliases": ["hubbell", "hubbell outlet"],
        "unit": "EA",
        "definition": "Hubbell heavy-duty receptacles and plugs.",
        "phonetic": "HUB-ul",
        "ipa": "/ˈhʌbəl/",
    },
    {
        "canonical": "Pass & Seymour Devices",
        "suffixes": ["15A Outlet", "20A Outlet"],
        "aliases": ["pass and seymour", "p and s", "legrand"],
        "unit": "EA",
        "definition": "Pass & Seymour (Legrand) wiring devices.",
        "phonetic": "PASS and SEE-mor",
        "ipa": "/pæs ənd ˈsiːmɔːr/",
    },
    {
        "canonical": "GE Enbrighten Devices",
        "suffixes": ["Smart Dimmer", "Smart Outlet"],
        "aliases": ["ge smart", "enbrighten"],
        "unit": "EA",
        "definition": "GE Enbrighten smart dimmers and outlets.",
        "phonetic": "GEE EE",
        "ipa": "/dʒiː iː/",
    },
    {
        "canonical": "Smoke Detector",
        "suffixes": ["Hardwired", "Battery", "Combo CO"],
        "aliases": ["smoke alarm", "smoke detector"],
        "unit": "EA",
        "definition": "Ionization or photoelectric smoke alarm; combos add CO sensing.",
    },
    {
        "canonical": "Carbon Monoxide Detector",
        "suffixes": ["Battery", "Plug-In"],
        "aliases": ["co detector", "co alarm", "carbon monoxide alarm"],
        "unit": "EA",
        "definition": "CO alarm required near sleeping areas and fuel-burning appliances.",
    },
    {
        "canonical": "Ecobee Thermostat",
        "suffixes": ["3 Lite", "Smart", "Premium"],
        "aliases": ["ecobee", "smart thermostat"],
        "unit": "EA",
        "definition": "Ecobee learning thermostat with remote sensors.",
        "phonetic": "EE-co-bee",
        "ipa": "/ˈiːkoʊbiː/",
    },
    {
        "canonical": "Nest Thermostat",
        "suffixes": ["E", "Learning", "Temperature Sensor"],
        "aliases": ["nest", "nest thermostat"],
        "unit": "EA",
        "definition": "Google Nest learning thermostat.",
        "phonetic": "NEST",
        "ipa": "/nɛst/",
    },
    {
        "canonical": "Ring Doorbell",
        "suffixes": ["Pro", "Video Doorbell 4", "Chime"],
        "aliases": ["ring", "video doorbell"],
        "unit": "EA",
        "definition": "Ring video doorbell and chime.",
        "phonetic": "RING",
        "ipa": "/rɪŋ/",
    },
    {
        "canonical": "Smart Lock",
        "suffixes": ["August", "Schlage Encode", "Yale Assure"],
        "aliases": ["smart lock", "keyless lock", "wifi lock"],
        "unit": "EA",
        "definition": "Keyless deadbolt controlled by app, keypad, or voice.",
    },
    {
        "canonical": "Smart Bulb",
        "suffixes": ["A19", "BR30", "Candle"],
        "aliases": ["smart bulb", "wifi bulb", "philips hue"],
        "unit": "EA",
        "definition": "Color-tunable Wi-Fi/zigbee LED bulb.",
    },
    {
        "canonical": "Smart Plug",
        "suffixes": ["Mini", "Outdoor"],
        "aliases": ["smart plug", "wifi outlet plug"],
        "unit": "EA",
        "definition": "Plug-in outlet that turns a lamp or appliance on by app or voice.",
    },
    {
        "canonical": "Ethernet Wall Jack",
        "suffixes": ["Keystone", "Wall Plate"],
        "aliases": ["ethernet jack", "rj45 jack", "cat6 jack"],
        "unit": "EA",
        "definition": "Termination jack for a structured-wiring data drop.",
    },
    {
        "canonical": "Patch Panel",
        "suffixes": ["12 Port", "24 Port"],
        "aliases": ["patch panel", "network patch"],
        "unit": "EA",
        "definition": "Rack panel that organizes data drops to the switch.",
    },
    {
        "canonical": "Whole Home Battery Backup",
        "suffixes": ["Tesla Powerwall", "Generac PWRcell"],
        "aliases": ["battery backup", "home battery", "powerwall"],
        "unit": "EA",
        "definition": "Whole-home battery that keeps critical loads running in an outage.",
    },

    {
        "canonical": "Range Cord",
        "suffixes": ["4 Prong 50A", "3 Prong 50A"],
        "aliases": ["range cord", "stove cord", "electric range cord"],
        "unit": "EA",
        "definition": "Pre-made 50A cord that hardwires an electric range.",
    },
    {
        "canonical": "Dryer Cord",
        "suffixes": ["4 Prong 30A", "3 Prong 30A"],
        "aliases": ["dryer cord", "dryer pigtail"],
        "unit": "EA",
        "definition": "30A cord that connects an electric dryer to its outlet.",
    },
    {
        "canonical": "Pigtail Wire",
        "suffixes": ["12 AWG", "14 AWG"],
        "aliases": ["pigtail", "lead wire", "short wire"],
        "unit": "EA",
        "definition": "Short jumper used to connect multiple wires to one device.",
    },
    {
        "canonical": "Wire Strippers",
        "suffixes": ["Automatic", "Self-Adjusting"],
        "aliases": ["wire stripper", "stripper tool"],
        "unit": "EA",
        "definition": "Tool that strips NM and THHN insulation without nicking copper.",
    },
    {
        "canonical": "Voltage Tester",
        "suffixes": ["Non-Contact", "Multimeter"],
        "aliases": ["voltage tester", "tick tester", "multimeter"],
        "unit": "EA",
        "definition": "Safety tester that confirms a circuit is dead before working on it.",
    },
    {
        "canonical": "Outlet Tester",
        "suffixes": ["Standard", "GFCI"],
        "aliases": ["outlet tester", "receptacle tester"],
        "unit": "EA",
        "definition": "Plug-in tester that checks wiring and GFCI function at an outlet.",
    },
    {
        "canonical": "Cable Tester",
        "suffixes": ["Ethernet", "Coax"],
        "aliases": ["network tester", "cat6 tester"],
        "unit": "EA",
        "definition": "Continuity tester for data and coax runs.",
    },
    {
        "canonical": "Wire Labels",
        "suffixes": ["Breaker Labels", "Cable Labels"],
        "aliases": ["wire labels", "panel labels"],
        "unit": "ROLL",
        "definition": "Self-adhesive labels for panel directories and conductor ID.",
    },
]

