"""Framing & rough carpentry lexicon families (lumber, engineered wood,
Simpson Strong-Tie connectors, fasteners, layout). Suffix x length matrices
generate the real size stock; build_rows() expands them to full rows.
"""

TRADE = "Framing"

FAMILIES = [
    # ---- Dimensional lumber ---------------------------------------------------
    {
        "canonical": "SPF Stud",
        "suffixes": ["2x4", "2x6", "2x8"],
        "lengths": ["8'", "10'", "12'", "16'"],
        "suffix_aliases": {"2x4": ["2x4 stud", "2 by 4 stud", "precut stud"],
                           "2x6": ["2x6 stud", "2 by 6 stud"]},
        "aliases": ["spf stud", "spruce pine fir stud", "stud"],
        "unit": "EA",
        "definition": "Kiln-dried spruce-pine-fir stud for wall framing; the vertical workhorse of residential partitions.",
    },
    {
        "canonical": "SYP Stud",
        "suffixes": ["2x4", "2x6"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["southern yellow pine stud", "syp stud"],
        "unit": "EA",
        "definition": "Stronger southern yellow pine stud commonly used for load-bearing walls and garages.",
    },
    {
        "canonical": "Douglas Fir Stud",
        "suffixes": ["2x4", "2x6"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["doug fir stud", "df stud", "d fir"],
        "unit": "EA",
        "definition": "High-strength Douglas fir stud for tall walls and heavy loads.",
    },
    {
        "canonical": "SPF Plate",
        "suffixes": ["2x4", "2x6"],
        "lengths": ["8'", "10'", "12'"],
        "suffix_aliases": {"2x4": ["bottom plate", "top plate", "sole plate"]},
        "aliases": ["spf plate", "wall plate"],
        "unit": "LF",
        "definition": "Horizontal 2x laid flat under and over studs to tie wall framing together.",
    },
    {
        "canonical": "Pressure Treated Plate",
        "suffixes": ["2x4", "2x6"],
        "lengths": ["8'", "10'"],
        "aliases": ["pt plate", "treated plate", "treated sill plate", "treated bottom plate"],
        "unit": "LF",
        "definition": "Preservative-treated plate used where lumber sits directly on concrete.",
    },
    {
        "canonical": "SPF Board",
        "suffixes": ["2x4", "2x6", "2x8", "2x10", "2x12"],
        "lengths": ["8'", "10'", "12'", "16'"],
        "aliases": ["spf board", "2x lumber", "dimension lumber"],
        "unit": "EA",
        "definition": "General-purpose dimension lumber for blocking, bracing, headers, and rough framing.",
    },
    {
        "canonical": "Pressure Treated Lumber",
        "suffixes": ["2x4", "2x6", "2x8", "4x4", "6x6"],
        "lengths": ["8'", "10'", "12'"],
        "suffix_aliases": {"4x4": ["pt 4x4 post", "treated 4x4"], "6x6": ["pt 6x6 post", "treated 6x6"]},
        "aliases": ["pt lumber", "treated lumber", "pressure treated"],
        "unit": "EA",
        "definition": "Chemical-preservative-treated lumber for ground contact, decks, and exterior framing.",
    },
    {
        "canonical": "Cedar Board",
        "suffixes": ["1x4", "1x6", "1x8"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["cedar lumber", "western red cedar", "cedar trim board"],
        "unit": "EA",
        "definition": "Naturally rot-resistant cedar board for exterior trim, soffits, and fascia.",
    },
    # ---- Engineered wood ------------------------------------------------------
    {
        "canonical": "LVL Beam",
        "suffixes": ["1-3/4x9-1/4", "1-3/4x11-7/8", "1-3/4x14", "3-1/2x11-7/8"],
        "lengths": ["12'", "16'", "20'"],
        "aliases": ["lvl", "laminated veneer lumber", "engineered beam", "microllam"],
        "unit": "LF",
        "definition": "Laminated-veneer-lumber beam that carries big header and girder loads without heavy solid timber.",
    },
    {
        "canonical": "TimberStrand LSL Stud",
        "suffixes": ["2x4", "2x6"],
        "lengths": ["8'", "10'"],
        "aliases": ["lsl", "laminated strand lumber", "timberstrand"],
        "unit": "EA",
        "definition": "Laminated-strand-lumber stud that stays straight and takes long loads for tall walls.",
    },
    {
        "canonical": "I-Joist TJI",
        "suffixes": ["9-1/2", "11-7/8", "14", "16"],
        "lengths": ["14'", "16'", "20'"],
        "suffix_aliases": {"9-1/2": ["tji 9-1/2"], "11-7/8": ["tji 11-7/8"]},
        "aliases": ["i joist", "engineered joist", "trus joist", "tji"],
        "unit": "LF",
        "definition": "Engineered I-shaped floor joist with OSB web and LVL/SPF flanges; long spans, straight floors.",
    },
    {
        "canonical": "OSB Sheathing",
        "suffixes": ["7/16", "15/32", "19/32"],
        "suffix_aliases": {"15/32": ["1/2 osb", "15/32 osb"], "19/32": ["5/8 osb"]},
        "aliases": ["osb", "oriented strand board", "sheathing"],
        "unit": "SF",
        "definition": "Oriented-strand-board panel for wall and roof sheathing; accepts fasteners and seals the envelope.",
    },
    {
        "canonical": "CDX Plywood",
        "suffixes": ["1/2", "5/8", "3/4"],
        "aliases": ["cdx", "plywood sheathing", "plywood"],
        "unit": "SF",
        "definition": "Exposure-1 plywood for subfloor, wall, and roof sheathing; 3/4 is the standard subfloor.",
    },
    {
        "canonical": "Glulam Beam",
        "suffixes": ["3-1/8x9", "3-1/8x12", "5-1/8x9", "5-1/8x12"],
        "lengths": ["12'", "16'", "20'"],
        "aliases": ["glulam", "glued laminated timber", "glue lam"],
        "unit": "LF",
        "definition": "Glued-laminated timber beam for exposed beams, headers, and long clear spans.",
    },
    {
        "canonical": "Rim Board",
        "suffixes": ["1x10", "1x12"],
        "lengths": ["8'", "12'"],
        "aliases": ["rim joist board", "band joist"],
        "unit": "LF",
        "definition": "The outer edge of a floor system that caps the joist ends and transfers shear to the walls.",
    },

    # ---- Simpson Strong-Tie connectors ----------------------------------------
    {
        "canonical": "Hurricane Tie",
        "suffixes": ["H2.5A", "H2.5AZ", "H10A"],
        "suffix_aliases": {"H2.5A": ["h2.5a", "hurricane tie", "rafter tie"],
                           "H2.5AZ": ["zmax hurricane tie"], "H10A": ["h10a"]},
        "aliases": ["simpson hurricane tie", "hurricane clip"],
        "unit": "EA",
        "definition": "Galvanized rafter-to-top-plate connector that keeps the roof attached in high wind; code-required in many zones.",
    },
    {
        "canonical": "Joist Hanger",
        "suffixes": ["LUS24", "LUS26", "LUS28", "LUS210", "LUS212"],
        "suffix_aliases": {"LUS28": ["lus28", "2x8 hanger"], "LUS210": ["lus210", "2x10 hanger"], "LUS212": ["lus212", "2x12 hanger"]},
        "aliases": ["joist hanger", "simpson hanger"],
        "unit": "EA",
        "definition": "Galvanized hanger that seats a joist into a beam or ledger with full bearing.",
    },
    {
        "canonical": "Post Base",
        "suffixes": ["ABU44", "ABU66", "CBSQ44"],
        "suffix_aliases": {"ABU44": ["post base", "abu44", "post anchor"], "ABU66": ["abu66", "6x6 post base"]},
        "aliases": ["simpson post base", "post base standoff"],
        "unit": "EA",
        "definition": "Galvanized post base that holds a post off concrete and anchors it to the slab or footing.",
    },
    {
        "canonical": "Anchor Bolt",
        "suffixes": ["3/8 x 4", "1/2 x 6", "5/8 x 8"],
        "aliases": ["anchor bolt", "j bolt", "foundation bolt"],
        "unit": "EA",
        "definition": "Embedded or expansion bolt that ties the sill plate to the foundation.",
    },
    {
        "canonical": "Rafter Tie",
        "suffixes": ["RTC2", "RTC2Z"],
        "aliases": ["rafter tie", "ceiling tie", "simpson rafter tie"],
        "unit": "EA",
        "definition": "Connects opposing rafters or ceiling joists against wind uplift.",
    },
    {
        "canonical": "Framing Angle",
        "suffixes": ["A21", "A35", "A44"],
        "suffix_aliases": {"A35": ["framing angle", "corner brace"]},
        "aliases": ["simpson angle", "galvanized angle", "tie angle"],
        "unit": "EA",
        "definition": "Galvanized angle bracket for right-angle wood-to-wood or wood-to-masonry connections.",
    },
    {
        "canonical": "Strap Tie",
        "suffixes": ["CS14", "CS16", "CTS16"],
        "aliases": ["strap tie", "hold down strap", "shear strap"],
        "unit": "EA",
        "definition": "Galvanized strap that ties framing members together for shear and uplift resistance.",
    },
    {
        "canonical": "Holdown Anchor",
        "suffixes": ["HDU2", "HDU4", "HDU8"],
        "aliases": ["holdown", "hold down", "tie down anchor"],
        "unit": "EA",
        "definition": "High-capacity connector that ties a shear wall or post down to the foundation.",
    },
    {
        "canonical": "Column Cap",
        "suffixes": ["CCQ44", "CCQ66"],
        "aliases": ["column cap", "post cap", "beam seat"],
        "unit": "EA",
        "definition": "Galvanized cap that seats a beam on a post without through-bolting the beam.",
    },

    # ---- Fasteners -------------------------------------------------------------
    {
        "canonical": "Framing Nails",
        "suffixes": ["16d Common", "16d Sinker", "3-1/4 Collated", "Duplex"],
        "suffix_aliases": {"16d Common": ["16d common", "framing nail"], "16d Sinker": ["16d sinker"],
                           "3-1/4 Collated": ["collated framing nails", "gun nails", "21 degree nails"],
                           "Duplex": ["duplex nail", "double head nail", "form nail"]},
        "aliases": ["framing nails", "common nails"],
        "unit": "LB",
        "definition": "16d common nails for structural wall and roof framing; hand or gun driven.",
    },
    {
        "canonical": "Deck Screws",
        "suffixes": ["#8 x 2-1/2", "#8 x 3", "#9 x 3-1/2"],
        "aliases": ["deck screw", "coated deck screw", "ceramic coated screws"],
        "unit": "BOX",
        "definition": "Corrosion-coated exterior screws for deck boards and treated lumber.",
    },
    {
        "canonical": "Structural Wood Screws",
        "suffixes": ["#9 x 2-1/2", "#10 x 3", "GRK RSS 1/4 x 3-1/8"],
        "aliases": ["structural screw", "grk", "headlok", "structural wood screw"],
        "unit": "EA",
        "definition": "High-strength engineered screws that replace lag bolts for ledger and beam connections.",
    },
    {
        "canonical": "Lag Bolts",
        "suffixes": ["3/8 x 3", "1/2 x 4", "1/2 x 6"],
        "aliases": ["lag bolt", "lag screw", "lag"],
        "unit": "EA",
        "definition": "Heavy hex-head wood bolt for beams, posts, and ledger connections.",
    },
    {
        "canonical": "Masonry Screws",
        "suffixes": ["Tapcon 1/4 x 1-3/4", "Tapcon 3/8 x 3"],
        "aliases": ["tapcon", "masonry screw", "concrete screw"],
        "unit": "EA",
        "definition": "Self-tapping screw that anchors into concrete and block without a plug.",
    },
    {
        "canonical": "Powder Actuated Fasteners",
        "suffixes": ["0.27 Cal Pin", "0.27 Cal Washer"],
        "aliases": ["powder actuated pin", "powder pin", "shot pin", "ramset"],
        "unit": "BOX",
        "definition": "Powder-driven pins that fasten steel track and plates to concrete.",
    },
    {
        "canonical": "Construction Adhesive",
        "suffixes": ["10 oz", "28 oz"],
        "aliases": ["construction adhesive", "liquid nails", "panel adhesive", "subfloor adhesive"],
        "unit": "TUBE",
        "definition": "Heavy-duty adhesive for subfloor and sheathing that works with mechanical fasteners.",
    },
    # ---- Layout, blocking & rough misc ----------------------------------------
    {
        "canonical": "Fire Blocking",
        "suffixes": ["2x4", "2x6", "Foam"],
        "aliases": ["fire block", "fire blocking", "draft stop", "fire stop foam"],
        "unit": "LF",
        "definition": "Blocking or foam installed in wall cavities to slow fire spread between floors.",
    },
    {
        "canonical": "Wood Shims",
        "suffixes": ["Standard", "Door & Window"],
        "aliases": ["shims", "cedar shims", "door shims"],
        "unit": "EA",
        "definition": "Tapered wood wedges for plumbing doors and windows and leveling trim.",
    },
    {
        "canonical": "Jack Stud",
        "suffixes": ["2x4", "2x6"],
        "aliases": ["jack stud", "trimmer", "trimmer stud"],
        "unit": "EA",
        "definition": "Short stud under each header end that carries the opening load to the bottom plate.",
    },
    {
        "canonical": "Cripple Stud",
        "suffixes": ["2x4", "2x6"],
        "aliases": ["cripple", "cripple stud"],
        "unit": "EA",
        "definition": "Short stud between a header and top plate, or sill and bottom plate, at openings.",
    },
    {
        "canonical": "Corner Assembly",
        "suffixes": ["2x4 Three-Stud", "2x6 Three-Stud"],
        "aliases": ["corner studs", "corner post", "three stud corner"],
        "unit": "EA",
        "definition": "Prebuilt three-stud corner giving drywall a nailing surface and keeping the wall square.",
    },
    {
        "canonical": "Sill Seal Foam",
        "suffixes": ["2 inch", "3 inch"],
        "aliases": ["sill sealer", "sill gasket", "foam sill seal"],
        "unit": "LF",
        "definition": "Foam gasket under the sill plate sealing the slab-to-wood joint against air leaks.",
    },
    {
        "canonical": "Flashing Tape",
        "suffixes": ["6 inch", "9 inch"],
        "aliases": ["flashing tape", "butyl tape", "peel and stick", "zip tape"],
        "unit": "ROLL",
        "definition": "Self-adhering membrane tape sealing sheathing seams, windows, and flashings.",
    },
    {
        "canonical": "Joist Tape",
        "suffixes": ["6 inch", "9 inch"],
        "aliases": ["joist tape", "deck joist tape", "butyl joist tape"],
        "unit": "ROLL",
        "definition": "Peel-and-stick tape over deck joist tops that keeps moisture off the lumber.",
    },
    {
        "canonical": "Framing Square",
        "suffixes": ["12 inch", "16 inch"],
        "aliases": ["framing square", "speed square", "rafter square"],
        "unit": "EA",
        "definition": "Layout square used to mark rafters, stairs, and right angles on framing lumber.",
    },
    {
        "canonical": "Chalk Line",
        "suffixes": ["50 ft", "100 ft"],
        "aliases": ["chalk line", "chalk reel", "snap line"],
        "unit": "EA",
        "definition": "Reel-and-chalk tool for snapping straight layout lines across subfloors and walls.",
    },

    {
        "canonical": "Kiln Dried Board",
        "suffixes": ["1x2", "1x3", "1x4", "1x6"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["kd board", "clear pine", "whitewood board"],
        "unit": "EA",
        "definition": "Straight kiln-dried board for furring, strapping, shelves, and trim backing.",
    },
    {
        "canonical": "Furring Strip",
        "suffixes": ["1x2", "1x3"],
        "lengths": ["8'", "10'"],
        "aliases": ["furring", "furring strips"],
        "unit": "EA",
        "definition": "Thin strips nailed to masonry or studs to create a level nailing surface.",
    },
    {
        "canonical": "Pressure Treated Deck Board",
        "suffixes": ["2x4", "2x6"],
        "lengths": ["8'", "10'", "12'", "16'"],
        "aliases": ["pt deck board", "deck board", "treated decking"],
        "unit": "LF",
        "definition": "Treated 5/4 or 2x decking plank for outdoor decks and walkways.",
    },
    {
        "canonical": "Composite Deck Board",
        "suffixes": ["Trex Select", "Trex Transcend"],
        "lengths": ["16'", "20'"],
        "aliases": ["trex", "composite decking", "capped composite"],
        "unit": "LF",
        "definition": "Cap-stock composite decking that never needs staining or sealing.",
    },
    {
        "canonical": "Metal Stud",
        "suffixes": ["2-1/2 inch", "3-5/8 inch", "6 inch"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["steel stud", "metal framing stud", "c stud"],
        "unit": "EA",
        "definition": "Galvanized steel wall stud for non-load-bearing interior partitions.",
    },
    {
        "canonical": "Metal Track",
        "suffixes": ["2-1/2 inch", "3-5/8 inch", "6 inch"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["steel track", "metal runner", "u stud"],
        "unit": "EA",
        "definition": "Galvanized steel U-track that caps the top and bottom of metal stud walls.",
    },
    {
        "canonical": "Double Header",
        "suffixes": ["2x8", "2x10", "2x12"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["double header", "2 ply header", "built up header"],
        "unit": "LF",
        "definition": "Two 2x members nailed together over an opening to carry the wall load above.",
    },
    {
        "canonical": "Post",
        "suffixes": ["4x4", "6x6", "8x8"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["wood post", "support post", "column"],
        "unit": "EA",
        "definition": "Solid square post carrying beam and girder loads to the foundation.",
    },
    {
        "canonical": "Stair Stringer",
        "suffixes": ["2x10", "2x12"],
        "lengths": ["8'", "10'", "12'", "16'"],
        "aliases": ["stringer", "stair stringer", "stair horse"],
        "unit": "EA",
        "definition": "Notched or solid member that carries stair treads and risers between floors.",
    },
    {
        "canonical": "Subfloor Panel",
        "suffixes": ["Advantech 23/32", "CDX 23/32", "Zip 3/4"],
        "aliases": ["subfloor", "advantech", "floor sheathing"],
        "unit": "SF",
        "definition": "Thick panel sheathing that forms the walking surface over floor joists.",
    },
    {
        "canonical": "I-Joist Hanger",
        "suffixes": ["IUS28", "IUS210", "IUS212"],
        "aliases": ["i joist hanger", "ius hanger"],
        "unit": "EA",
        "definition": "Flanged hanger sized for the tapered flange of engineered I-joists.",
    },
    {
        "canonical": "Let-In Brace",
        "suffixes": ["1x4 x 8", "Metal 18 gauge"],
        "aliases": ["let in brace", "corner brace", "diagonal brace"],
        "unit": "EA",
        "definition": "Diagonal bracing let into wall studs to resist racking before sheathing goes on.",
    },
    {
        "canonical": "Blocking Board",
        "suffixes": ["2x4", "2x6"],
        "lengths": ["8'", "10'"],
        "aliases": ["blocking", "blocking lumber"],
        "unit": "LF",
        "definition": "Short 2x cut-offs used between studs or joists for fire blocking and nailers.",
    },
    {
        "canonical": "Screws for Steel Studs",
        "suffixes": ["#8 x 1/2", "#8 x 1-1/4"],
        "aliases": ["steel stud screw", "self tapping screw", "drywall to metal screw"],
        "unit": "BOX",
        "definition": "Self-tapping pan-head screws that bite steel studs and track.",
    },

    {
        "canonical": "Through Bolt",
        "suffixes": ["1/2 x 6", "1/2 x 8", "5/8 x 8"],
        "aliases": ["through bolt", "machine bolt", "hex bolt"],
        "unit": "EA",
        "definition": "Hex-head bolt with nut for wood-to-wood, wood-to-steel, and post-to-beam connections.",
    },
    {
        "canonical": "All-Thread Rod",
        "suffixes": ["1/4", "3/8", "1/2"],
        "lengths": ["3'", "6'"],
        "aliases": ["all thread", "threaded rod", "redi rod"],
        "unit": "EA",
        "definition": "Continuous threaded rod for hangers, bracing, and hanging assemblies.",
    },
    {
        "canonical": "Galvanized Nails",
        "suffixes": ["6d", "8d", "10d"],
        "aliases": ["galvanized nail", "hot dipped nail"],
        "unit": "LB",
        "definition": "Corrosion-resistant nails for exterior and treated-lumber work.",
    },
    {
        "canonical": "Ring Shank Nails",
        "suffixes": ["6d", "8d", "10d"],
        "aliases": ["ring shank", "ring nail", "deck nail"],
        "unit": "LB",
        "definition": "Nails with annular rings that grip subfloor and decking against withdrawal.",
    },
    {
        "canonical": "Concrete Nails",
        "suffixes": ["1-1/2", "2", "2-1/2"],
        "aliases": ["masonry nail", "hardened nail", "concrete nail"],
        "unit": "LB",
        "definition": "Hardened fluted nails driven into concrete or block for base plates and furring.",
    },
    {
        "canonical": "PT 5/4 Decking",
        "suffixes": ["x 4", "x 6"],
        "lengths": ["8'", "10'", "12'"],
        "aliases": ["5/4 decking", "pt 5/4", "five quarter decking"],
        "unit": "LF",
        "definition": "Five-quarter treated decking plank with a radius edge for comfortable barefoot decks.",
    },
    {
        "canonical": "Zip System Wall Sheathing",
        "suffixes": ["1/2", "5/8"],
        "aliases": ["zip wall", "zip system", "zip sheathing"],
        "unit": "SF",
        "definition": "OSB panel with built-in weather-resistive barrier; seams tape with Zip tape.",
    },
    {
        "canonical": "Zip System Roof Sheathing",
        "suffixes": ["7/16", "1/2"],
        "aliases": ["zip roof", "zip roof sheathing"],
        "unit": "SF",
        "definition": "Roof-rated OSB with integrated WRB that tapes into a fully water-shedding deck.",
    },
    {
        "canonical": "Plywood Underlayment",
        "suffixes": ["1/4", "1/2"],
        "aliases": ["underlayment", "underlayment plywood"],
        "unit": "SF",
        "definition": "Smooth-faced plywood laid over subfloor to level floors before finish flooring.",
    },
]

