"""HVAC lexicon families: ductwork, furnaces, condensers, heat pumps,
mini-splits, thermostats, insulation, air quality, refrigerant."""

TRADE = "HVAC"

FAMILIES = [
    # ---- Ductwork --------------------------------------------------------------
    {
        "canonical": "Flexible Duct",
        "suffixes": ["4\"", "5\"", "6\"", "7\"", "8\"", "10\"", "12\"", "14\""],
        "lengths": ["25 ft", "50 ft"],
        "aliases": ["flex duct", "insulated flex", "flex pipe"],
        "unit": "LF",
        "definition": "Wire-reinforced insulated flex duct for branch supply and returns.",
    },
    {
        "canonical": "Rigid Metal Duct",
        "suffixes": ["4\"", "5\"", "6\"", "8\"", "10\"", "12\""],
        "lengths": ["60 in", "96 in"],
        "aliases": ["galvanized duct", "sheet metal duct", "metal pipe"],
        "unit": "LF",
        "definition": "Galvanized snap-lock or spiral duct for main runs.",
    },
    {
        "canonical": "Duct Elbow",
        "suffixes": ["4\"", "5\"", "6\"", "8\"", "10\"", "12\""],
        "aliases": ["duct elbow", "90 degree elbow", "sheet metal elbow"],
        "unit": "EA",
        "definition": "Galvanized 90-degree elbow for turning a duct run.",
    },
    {
        "canonical": "Duct Tee",
        "suffixes": ["6\"", "8\"", "10\"", "12\""],
        "aliases": ["duct tee", "saddle tap", "duct takeoff"],
        "unit": "EA",
        "definition": "Fitting that branches a supply run to a register.",
    },
    {
        "canonical": "Duct Coupling",
        "suffixes": ["6\"", "8\"", "10\"", "12\""],
        "aliases": ["duct coupler", "duct collar"],
        "unit": "EA",
        "definition": "Collar that joins two lengths of round duct.",
    },
    {
        "canonical": "Floor Register",
        "suffixes": ["4 x 10", "4 x 12", "6 x 10", "6 x 14"],
        "aliases": ["floor vent", "supply register", "heat vent"],
        "unit": "EA",
        "definition": "Floor-mounted supply grille with a damper.",
    },
    {
        "canonical": "Ceiling Diffuser",
        "suffixes": ["6\"", "8\"", "10\"", "12\""],
        "aliases": ["ceiling vent", "supply diffuser", "round diffuser"],
        "unit": "EA",
        "definition": "Round ceiling supply outlet with adjustable blades.",
    },
    {
        "canonical": "Return Air Grille",
        "suffixes": ["12 x 12", "16 x 16", "20 x 20", "12 x 20"],
        "aliases": ["return grille", "return vent", "return air"],
        "unit": "EA",
        "definition": "Non-dampered grille that pulls air back to the system.",
    },
    {
        "canonical": "Register Boot",
        "suffixes": ["6\" x 4x10", "8\" x 6x12"],
        "aliases": ["floor boot", "register boot", "duct boot"],
        "unit": "EA",
        "definition": "Sheet-metal transition from round duct to a floor register.",
    },
    {
        "canonical": "Volume Damper",
        "suffixes": ["6\"", "8\"", "10\"", "12\""],
        "aliases": ["damper", "balance damper"],
        "unit": "EA",
        "definition": "Blade assembly that balances air flow in a branch duct.",
    },
    {
        "canonical": "Duct Sealant Mastic",
        "suffixes": ["1 Gal", "5 Gal"],
        "aliases": ["duct mastic", "duct sealant", "mastic"],
        "unit": "PAIL",
        "definition": "Brush-on sealant that makes duct joints air-tight.",
    },
    {
        "canonical": "Foil Duct Tape",
        "suffixes": ["2 in", "3 in"],
        "aliases": ["foil tape", "duct tape", "aluminum tape"],
        "unit": "ROLL",
        "definition": "UL-rated foil tape for sealing duct connections.",
    },
    {
        "canonical": "Duct Insulation Wrap",
        "suffixes": ["24 in", "48 in"],
        "aliases": ["duct wrap", "insulated duct wrap"],
        "unit": "LF",
        "definition": "Foil-faced fiberglass wrap for unheated attic duct runs.",
    },
    # ---- Heating & cooling equipment ------------------------------------------
    {
        "canonical": "80% AFUE Gas Furnace",
        "suffixes": ["60,000 BTU", "80,000 BTU", "100,000 BTU", "120,000 BTU"],
        "aliases": ["gas furnace", "80 percent furnace", "standard efficiency furnace"],
        "unit": "EA",
        "definition": "Non-condensing natural gas furnace with a metal flue pipe.",
    },
    {
        "canonical": "95% Condensing Gas Furnace",
        "suffixes": ["60,000 BTU", "80,000 BTU", "100,000 BTU", "120,000 BTU"],
        "aliases": ["high efficiency furnace", "condensing furnace", "95 percent furnace"],
        "unit": "EA",
        "definition": "Two-stage condensing furnace vented through PVC; up to 97% AFUE.",
    },
    {
        "canonical": "AC Condenser",
        "suffixes": ["1.5 Ton", "2 Ton", "2.5 Ton", "3 Ton", "3.5 Ton", "4 Ton", "5 Ton"],
        "aliases": ["condenser", "air conditioner", "a c unit", "outside unit", "condensing unit"],
        "unit": "EA",
        "definition": "Outdoor condensing unit with compressor and coil for split AC.",
    },
    {
        "canonical": "Heat Pump",
        "suffixes": ["1.5 Ton", "2 Ton", "2.5 Ton", "3 Ton", "4 Ton", "5 Ton"],
        "aliases": ["heat pump", "air source heat pump", "hp"],
        "unit": "EA",
        "definition": "Outdoor unit that both cools and heats by reversing refrigerant flow.",
    },
    {
        "canonical": "Evaporator Coil",
        "suffixes": ["2 Ton", "3 Ton", "4 Ton", "5 Ton"],
        "aliases": ["a coil", "indoor coil", "evap coil", "cased coil"],
        "unit": "EA",
        "definition": "Indoor cased coil that sits on the furnace and cools supply air.",
    },
    {
        "canonical": "Line Set",
        "suffixes": ["1/4 x 3/8", "3/8 x 3/4", "3/8 x 7/8"],
        "lengths": ["25 ft", "50 ft"],
        "aliases": ["lineset", "refrigerant lines", "line set"],
        "unit": "LF",
        "definition": "Pre-insulated copper suction and liquid lines between indoor and outdoor units.",
    },
    {
        "canonical": "Mini Split System",
        "suffixes": ["9,000 BTU", "12,000 BTU", "18,000 BTU", "24,000 BTU", "36,000 BTU"],
        "aliases": ["ductless", "mini split", "ductless heat pump", "ductless ac"],
        "unit": "EA",
        "definition": "Ductless heat pump with an indoor wall head and outdoor condenser.",
    },
    {
        "canonical": "MrCool Mini Split",
        "suffixes": ["DIY 12,000 BTU", "DIY 18,000 BTU", "DIY 24,000 BTU"],
        "aliases": ["mrcool", "mister cool", "diy mini split"],
        "unit": "EA",
        "definition": "Pre-charged DIY ductless system that needs no HVAC license to install.",
        "phonetic": "MIS-ter KOOL",
        "ipa": "/ˈmɪstər kuːl/",
    },
    {
        "canonical": "Daikin Mini Split",
        "suffixes": ["12,000 BTU", "18,000 BTU", "24,000 BTU"],
        "aliases": ["daikin", "daikin ductless"],
        "unit": "EA",
        "definition": "Daikin ductless heat pump systems.",
        "phonetic": "DIE-kin",
        "ipa": "/ˈdaɪkɪn/",
    },
    {
        "canonical": "Mitsubishi Mini Split",
        "suffixes": ["12,000 BTU", "18,000 BTU", "24,000 BTU"],
        "aliases": ["mitsubishi", "mitsubishi ductless", "hyper heat"],
        "unit": "EA",
        "definition": "Mitsubishi ductless systems; Hyper-Heat models run at -13F.",
        "phonetic": "mit-suh-BISH-ee",
        "ipa": "/ˌmɪtsəˈbɪʃi/",
    },
    {
        "canonical": "Fujitsu Mini Split",
        "suffixes": ["12,000 BTU", "18,000 BTU"],
        "aliases": ["fujitsu", "fujitsu ductless"],
        "unit": "EA",
        "definition": "Fujitsu ductless heat pumps.",
        "phonetic": "FOO-jit-soo",
        "ipa": "/ˈfuːdʒɪtsuː/",
    },
    {
        "canonical": "Trane Furnace",
        "suffixes": ["S9V80", "S9X1", "XC95"],
        "aliases": ["trane", "trane furnace"],
        "unit": "EA",
        "definition": "Trane gas furnaces from standard to top-tier XC95 condensing.",
        "phonetic": "TRAYN",
        "ipa": "/treɪn/",
    },
    {
        "canonical": "Carrier Furnace",
        "suffixes": ["59SC2", "59TP6", "Infinity"],
        "aliases": ["carrier", "carrier furnace"],
        "unit": "EA",
        "definition": "Carrier gas furnaces.",
        "phonetic": "KAIR-ee-er",
        "ipa": "/ˈkɛəriər/",
    },
    {
        "canonical": "Lennox Furnace",
        "suffixes": ["ML296", "EL296", "SLP98"],
        "aliases": ["lennox", "lennox furnace"],
        "unit": "EA",
        "definition": "Lennox gas furnaces.",
        "phonetic": "LEN-ox",
        "ipa": "/ˈlɛnəks/",
    },
    {
        "canonical": "Goodman Condenser",
        "suffixes": ["GSX14 3 Ton", "GSX16 3 Ton", "GSXC18 3 Ton"],
        "aliases": ["goodman", "goodman ac"],
        "unit": "EA",
        "definition": "Goodman condensing units.",
        "phonetic": "GOOD-man",
        "ipa": "/ˈɡʊdmən/",
    },
    {
        "canonical": "Rheem Condenser",
        "suffixes": ["RA16 3 Ton", "RA14 3 Ton"],
        "aliases": ["rheem ac", "rheem condenser"],
        "unit": "EA",
        "definition": "Rheem condensing units.",
        "phonetic": "REEM",
        "ipa": "/riːm/",
    },
    # ---- Thermostats & controls ------------------------------------------------
    {
        "canonical": "Honeywell Thermostat",
        "suffixes": ["T5", "T6 Pro", "Home T9"],
        "aliases": ["honeywell", "honeywell thermostat"],
        "unit": "EA",
        "definition": "Honeywell programmable and smart thermostats.",
        "phonetic": "HUN-ee-well",
        "ipa": "/ˈhʌniwɛl/",
    },
    {
        "canonical": "Programmable Thermostat",
        "suffixes": ["Basic 7-Day", "Wi-Fi"],
        "aliases": ["programmable thermostat", "digital thermostat"],
        "unit": "EA",
        "definition": "7-day programmable thermostat for schedule-based savings.",
    },
    {
        "canonical": "Line Voltage Thermostat",
        "suffixes": ["120V", "240V"],
        "aliases": ["line voltage tstat", "baseboard thermostat"],
        "unit": "EA",
        "definition": "Thermostat that directly switches baseboard heat circuits.",
    },
    {
        "canonical": "Zone Damper Control",
        "suffixes": ["2 Zone", "3 Zone"],
        "aliases": ["zone control", "zone panel"],
        "unit": "EA",
        "definition": "Controller that opens and closes dampers per-zone thermostat calls.",
    },
    # ---- Insulation -------------------------------------------------------------
    {
        "canonical": "Fiberglass Batt Insulation",
        "suffixes": ["R11 15 in", "R13 15 in", "R19 23 in", "R21 23 in", "R30 23 in"],
        "aliases": ["fiberglass batt", "batt insulation", "faced insulation"],
        "unit": "SF",
        "definition": "Faced fiberglass batts for walls, floors, and attics.",
    },
    {
        "canonical": "Attic Insulation Roll",
        "suffixes": ["R30", "R38", "R49"],
        "aliases": ["attic insulation", "blown in insulation", "unfaced roll"],
        "unit": "SF",
        "definition": "Unfaced fiberglass rolls for attic depth requirements.",
    },
    {
        "canonical": "Blown Cellulose Insulation",
        "suffixes": ["30 lb Bag", "50 lb Bag"],
        "aliases": ["cellulose", "blown insulation"],
        "unit": "BAG",
        "definition": "Recycled-paper blown insulation for attic and wall retrofit.",
    },
    {
        "canonical": "Mineral Wool Insulation",
        "suffixes": ["R15", "R23"],
        "aliases": ["rockwool", "mineral wool", "stone wool"],
        "unit": "SF",
        "definition": "Fire-resistant batt insulation that also blocks sound.",
    },
    {
        "canonical": "Spray Foam Insulation",
        "suffixes": ["Closed Cell", "Open Cell"],
        "aliases": ["spray foam", "foam insulation", "spray polyurethane"],
        "unit": "SF",
        "definition": "Two-component foam that seals and insulates in one pass.",
    },
    {
        "canonical": "Foam Board Insulation",
        "suffixes": ["Rigid 1 in", "Rigid 2 in", "XPS 1 in"],
        "aliases": ["rigid foam", "xps", "eps board", "foam board"],
        "unit": "SF",
        "definition": "Rigid board insulation for slabs, basements, and exterior walls.",
    },

    {
        "canonical": "Furnace Filter",
        "suffixes": ["16 x 25 MERV 8", "16 x 25 MERV 11", "20 x 25 MERV 8", "20 x 25 MERV 13", "16 x 20 MERV 8"],
        "aliases": ["air filter", "furnace filter", "pleated filter"],
        "unit": "EA",
        "definition": "Pleated media filter sized to the return filter grille.",
    },
    {
        "canonical": "Media Filter Cabinet",
        "suffixes": ["16 x 25", "20 x 25"],
        "aliases": ["filter cabinet", "media cabinet"],
        "unit": "EA",
        "definition": "5-inch deep filter cabinet that takes high-MERV media.",
    },
    {
        "canonical": "Condensate Pump",
        "suffixes": ["Little Giant 554415", "Standard 1/4 HP"],
        "aliases": ["condensate pump", "ac condensate pump"],
        "unit": "EA",
        "definition": "Pump that lifts AC condensation to a drain line or outdoors.",
    },
    {
        "canonical": "Condensate Drain Line",
        "suffixes": ["3/4 PVC", "1/2 Tube"],
        "aliases": ["condensate line", "drain line"],
        "unit": "LF",
        "definition": "Drain line that carries condensate from coil to floor drain.",
    },
    {
        "canonical": "Float Switch",
        "suffixes": ["Vertical", "Inline"],
        "aliases": ["float switch", "condensate overflow switch"],
        "unit": "EA",
        "definition": "Safety switch that kills the system if the drain pan fills.",
    },
    {
        "canonical": "Whole Home Humidifier",
        "suffixes": ["Bypass", "Fan Powered", "Steam"],
        "aliases": ["humidifier", "aprilaire", "furnace humidifier"],
        "unit": "EA",
        "definition": "Furnace-mounted humidifier that adds moisture to supply air.",
    },
    {
        "canonical": "ERV",
        "suffixes": ["100 CFM", "200 CFM"],
        "aliases": ["erv", "energy recovery ventilator"],
        "unit": "EA",
        "definition": "Balanced ventilation unit that recovers heat and moisture.",
    },
    {
        "canonical": "UV Air Purifier",
        "suffixes": ["16 in", "24 in"],
        "aliases": ["uv light", "uv purification", "germicidal light"],
        "unit": "EA",
        "definition": "UV-C lamp in the ductwork that neutralizes mold and bacteria on the coil.",
    },
    {
        "canonical": "Vibration Isolation Pad",
        "suffixes": ["Small", "Large"],
        "aliases": ["vibration pad", "compressor pad", "isolator"],
        "unit": "EA",
        "definition": "Rubber pad under the outdoor unit that kills noise transfer.",
    },

    # ---- Refrigerant & service --------------------------------------------------
    {
        "canonical": "R-410A Refrigerant",
        "suffixes": ["25 lb", "50 lb"],
        "aliases": ["410a", "puron", "freon 410a"],
        "unit": "LB",
        "definition": "The standard HFC blend for modern residential AC and heat pumps.",
    },
    {
        "canonical": "R-22 Refrigerant",
        "suffixes": ["30 lb"],
        "aliases": ["r22", "freon", "r-22"],
        "unit": "LB",
        "definition": "Legacy HCFC refrigerant for older systems; being phased out.",
    },
    {
        "canonical": "R-454B Refrigerant",
        "suffixes": ["25 lb"],
        "aliases": ["454b", "puron advance"],
        "unit": "LB",
        "definition": "Next-generation low-GWP refrigerant for 2025+ systems.",
    },
    {
        "canonical": "Refrigerant Recovery Tank",
        "suffixes": ["30 lb", "50 lb"],
        "aliases": ["recovery tank", "refrigerant tank"],
        "unit": "EA",
        "definition": "DOT-rated tank for reclaiming refrigerant during service.",
    },
    {
        "canonical": "Manifold Gauge Set",
        "suffixes": ["Standard", "Digital"],
        "aliases": ["gauges", "manifold gauges", "ac gauges"],
        "unit": "EA",
        "definition": "Pressure gauges used to charge and diagnose systems.",
    },
    {
        "canonical": "Nitrogen Tank",
        "suffixes": ["40 CF", "80 CF"],
        "aliases": ["nitrogen", "dry nitrogen"],
        "unit": "EA",
        "definition": "Dry nitrogen used to purge and pressure-test line sets.",
    },
    {
        "canonical": "Trane Heat Pump",
        "suffixes": ["XV18 3 Ton", "XR15 3 Ton"],
        "aliases": ["trane heat pump"],
        "unit": "EA",
        "definition": "Trane air-source heat pumps.",
        "phonetic": "TRAYN",
        "ipa": "/treɪn/",
    },
    {
        "canonical": "Carrier Heat Pump",
        "suffixes": ["25HNB6 3 Ton", "25HCE4 3 Ton"],
        "aliases": ["carrier heat pump"],
        "unit": "EA",
        "definition": "Carrier heat pump systems.",
        "phonetic": "KAIR-ee-er",
        "ipa": "/ˈkɛəriər/",
    },
    {
        "canonical": "Ductless Wall Head",
        "suffixes": ["9,000 BTU", "12,000 BTU", "18,000 BTU"],
        "aliases": ["wall head", "indoor head", "wall mount unit"],
        "unit": "EA",
        "definition": "Indoor blower head for a mini-split system.",
    },
    {
        "canonical": "Condenser Pad",
        "suffixes": ["24 x 24", "30 x 30"],
        "aliases": ["ac pad", "condenser pad", "concrete pad"],
        "unit": "EA",
        "definition": "Concrete or composite pad that levels the outdoor unit off the ground.",
    },
    {
        "canonical": "Line Set Cover",
        "suffixes": ["2 in", "3 in"],
        "aliases": ["line hide", "line set cover", "refrigerant line cover"],
        "unit": "LF",
        "definition": "PVC raceway that hides exterior refrigerant lines.",
    },
    {
        "canonical": "Ductless Drain Hose",
        "suffixes": ["10 ft", "25 ft"],
        "aliases": ["condensate hose", "drain hose"],
        "unit": "EA",
        "definition": "Flexible drain hose that carries mini-split condensate to a drain.",
    },

    {
        "canonical": "Combi Boiler",
        "suffixes": ["Navien NCB-240E", "Rinnai I Series"],
        "aliases": ["combi", "combi boiler"],
        "unit": "EA",
        "definition": "Combination boiler that does space heating and on-demand hot water.",
    },
    {
        "canonical": "Hydronic Boiler",
        "suffixes": ["Gas 80k BTU", "Propane 100k BTU"],
        "aliases": ["boiler", "hydronic boiler"],
        "unit": "EA",
        "definition": "Boiler that heats water for baseboard or radiant systems.",
    },
    {
        "canonical": "Air Handler",
        "suffixes": ["2 Ton", "3 Ton", "4 Ton", "5 Ton"],
        "aliases": ["air handler", "indoor unit"],
        "unit": "EA",
        "definition": "Indoor blower cabinet with the coil for a split heat pump or AC.",
    },
    {
        "canonical": "Baseboard Heater",
        "suffixes": ["120V 4 ft", "120V 6 ft", "240V 4 ft", "240V 6 ft", "240V 8 ft"],
        "aliases": ["baseboard heat", "electric baseboard"],
        "unit": "EA",
        "definition": "Electric resistance baseboard heating unit.",
    },
    {
        "canonical": "Bathroom Exhaust Fan",
        "suffixes": ["50 CFM", "80 CFM", "110 CFM", "Remote"],
        "aliases": ["exhaust fan", "bath fan", "vent fan"],
        "unit": "EA",
        "definition": "Ceiling exhaust fan sized to bathroom cubic footage.",
    },
    {
        "canonical": "Range Hood",
        "suffixes": ["Under Cabinet", "Wall Mount", "Ductless"],
        "aliases": ["range hood", "kitchen hood", "vent hood"],
        "unit": "EA",
        "definition": "Kitchen exhaust hood with a grease filter.",
    },
    {
        "canonical": "Dryer Vent Kit",
        "suffixes": ["Flex 4 in", "Wall Cap"],
        "aliases": ["dryer vent", "dryer duct"],
        "unit": "EA",
        "definition": "Vent duct and exterior cap for the clothes dryer.",
    },
    {
        "canonical": "Whole House Fan",
        "suffixes": ["24 in", "30 in"],
        "aliases": ["whole house fan", "attic fan"],
        "unit": "EA",
        "definition": "High-volume fan that pulls cool night air through the whole house.",
    },
    {
        "canonical": "Vent Termination",
        "suffixes": ["Wall Cap", "Roof Jack"],
        "aliases": ["vent cap", "termination cap"],
        "unit": "EA",
        "definition": "Exterior cap for a vent run through the wall or roof.",
    },
    {
        "canonical": "Ductwork Fire Damper",
        "suffixes": ["4 in", "6 in", "8 in"],
        "aliases": ["fire damper", "duct fire damper"],
        "unit": "EA",
        "definition": "Spring-loaded damper that closes on heat to protect fire walls.",
    },
    {
        "canonical": "Insulation Chute",
        "suffixes": ["16 in", "22 in"],
        "aliases": ["attic chute", "insulation baffle", "rafter vent"],
        "unit": "EA",
        "definition": "Cardboard baffle that keeps soffit intake air flowing above insulation.",
    },
    {
        "canonical": "Electrostatic Air Filter",
        "suffixes": ["16 x 25", "20 x 25"],
        "aliases": ["washable filter", "electrostatic filter"],
        "unit": "EA",
        "definition": "Reusable washable filter for the return grille.",
    },
    {
        "canonical": "Coil Cleaner",
        "suffixes": ["Aerosol", "Concentrate"],
        "aliases": ["coil cleaner", "ac coil cleaner"],
        "unit": "CAN",
        "definition": "Foaming cleaner for the outdoor condenser and indoor coil.",
    },
    {
        "canonical": "Condensate Pan",
        "suffixes": ["Standard", "Safety Switch"],
        "aliases": ["drain pan", "coil pan", "secondary pan"],
        "unit": "EA",
        "definition": "Catch pan under the coil or furnace with a secondary drain.",
    },
    {
        "canonical": "Hydronic Zone Valve",
        "suffixes": ["3/4 in", "1 in"],
        "aliases": ["zone valve", "boiler zone valve"],
        "unit": "EA",
        "definition": "Motorized valve that opens a zone loop on thermostat call.",
    },
    {
        "canonical": "Boiler Expansion Tank",
        "suffixes": ["2 Gal", "4 Gal"],
        "aliases": ["expansion tank", "extrol"],
        "unit": "EA",
        "definition": "Pressurized tank that absorbs boiler water expansion.",
    },
    {
        "canonical": "Blower Motor",
        "suffixes": ["1/2 HP", "3/4 HP"],
        "aliases": ["blower motor", "furnace motor"],
        "unit": "EA",
        "definition": "PSC or ECM motor that drives the furnace or air handler blower.",
    },
    {
        "canonical": "HVAC Capacitor",
        "suffixes": ["Dual 45/5", "Run 35/5", "Dual 60/7.5"],
        "aliases": ["capacitor", "start capacitor", "run capacitor"],
        "unit": "EA",
        "definition": "Motor start/run capacitor for the compressor and fan.",
    },
    {
        "canonical": "Contactor",
        "suffixes": ["1 Pole 30A", "2 Pole 40A"],
        "aliases": ["contactor", "ac contactor"],
        "unit": "EA",
        "definition": "Relay that switches power to the compressor and condenser fan.",
    },
    {
        "canonical": "Defrost Control Board",
        "suffixes": ["Standard", "Universal"],
        "aliases": ["defrost board", "control board"],
        "unit": "EA",
        "definition": "Circuit board that runs heat pump defrost cycles.",
    },
    {
        "canonical": "Reversing Valve",
        "suffixes": ["Standard", "Heat Pump"],
        "aliases": ["reversing valve", "4 way valve"],
        "unit": "EA",
        "definition": "Refrigerant valve that flips a heat pump between heat and cool.",
    },
    {
        "canonical": "Thermostat Transformer",
        "suffixes": ["24V 40VA", "24V 75VA"],
        "aliases": ["transformer", "tstat transformer"],
        "unit": "EA",
        "definition": "Step-down transformer that powers the thermostat and controls.",
    },
    {
        "canonical": "Heat Pump Water Heater",
        "suffixes": ["50 Gallon", "80 Gallon"],
        "aliases": ["hpwh", "hybrid water heater"],
        "unit": "EA",
        "definition": "Hybrid water heater that pulls heat from the surrounding air.",
    },

    {
        "canonical": "Pioneer Mini Split",
        "suffixes": ["9,000 BTU", "12,000 BTU"],
        "aliases": ["pioneer ductless"],
        "unit": "EA",
        "definition": "Pioneer budget ductless systems.",
        "phonetic": "PIE-uh-neer",
        "ipa": "/ˌpaɪəˈnɪər/",
    },
    {
        "canonical": "Furnace Vent Pipe",
        "suffixes": ["PVC 2 in", "PVC 3 in"],
        "aliases": ["furnace vent", "condensing vent pipe"],
        "unit": "LF",
        "definition": "Schedule 40 PVC used to vent condensing furnaces.",
    },
    {
        "canonical": "Condensate Neutralizer",
        "suffixes": ["Standard", "Combo With Pump"],
        "aliases": ["condensate neutralizer", "acid neutralizer"],
        "unit": "EA",
        "definition": "Filter that neutralizes acidic condensate before it hits the drain.",
    },
    {
        "canonical": "Mini Split Mounting Bracket",
        "suffixes": ["Standard", "Heavy Duty"],
        "aliases": ["wall bracket", "mini split bracket"],
        "unit": "EA",
        "definition": "Galvanized bracket that mounts the outdoor unit to a wall.",
    },
    {
        "canonical": "Refrigerant Scale",
        "suffixes": ["Analog", "Digital"],
        "aliases": ["charging scale", "refrigerant scale"],
        "unit": "EA",
        "definition": "Scale used to weigh refrigerant into a system.",
    },
    {
        "canonical": "Radiant Floor Manifold",
        "suffixes": ["2 Zone", "3 Zone"],
        "aliases": ["manifold", "radiant manifold"],
        "unit": "EA",
        "definition": "Supply/return manifold with zone valves for radiant loops.",
    },
    {
        "canonical": "Return Filter Grille",
        "suffixes": ["12 x 12", "20 x 25"],
        "aliases": ["filter grille", "return grille with filter"],
        "unit": "EA",
        "definition": "Return grille with a built-in filter slot.",
    },
    {
        "canonical": "Duct Liner",
        "suffixes": ["1/2 in", "1 in"],
        "aliases": ["duct liner", "duct insulation liner"],
        "unit": "LF",
        "definition": "Acoustic liner bonded inside metal ductwork.",
    },
    {
        "canonical": "Flexible Connector",
        "suffixes": ["6 in", "8 in"],
        "aliases": ["flex connector", "canvas connector"],
        "unit": "EA",
        "definition": "Vibration-isolating canvas connection at the unit.",
    },
    {
        "canonical": "Supply Plenum",
        "suffixes": ["Standard", "Return"],
        "aliases": ["plenum", "furnace plenum"],
        "unit": "EA",
        "definition": "Sheet-metal box on the furnace that feeds the duct system.",
    },
    {
        "canonical": "Duct Board",
        "suffixes": ["1 in", "2 in"],
        "aliases": ["duct board", "fiberglass duct board"],
        "unit": "SF",
        "definition": "Rigid fiberglass board fabricated into rectangular ducts.",
    },
    {
        "canonical": "Wye Strainer",
        "suffixes": ["3/4 in", "1 in"],
        "aliases": ["wye strainer", "pipe strainer"],
        "unit": "EA",
        "definition": "Screen strainer protecting pumps and valves from debris.",
    },
    {
        "canonical": "AC Charging Hose",
        "suffixes": ["Standard", "Low Loss"],
        "aliases": ["charging hose", "refrigerant hose"],
        "unit": "EA",
        "definition": "Manifold hose for connecting gauges to the system ports.",
    },
    {
        "canonical": "Vacuum Pump",
        "suffixes": ["1 CFM", "3 CFM"],
        "aliases": ["vacuum pump", "ac vacuum pump"],
        "unit": "EA",
        "definition": "Two-stage pump that pulls the system into a deep vacuum before charging.",
    },
    {
        "canonical": "Micron Gauge",
        "suffixes": ["Analog", "Digital"],
        "aliases": ["micron gauge", "vacuum gauge"],
        "unit": "EA",
        "definition": "Measures the depth of vacuum pulled on a system.",
    },
    {
        "canonical": "Refrigerant Leak Detector",
        "suffixes": ["Electronic", "UV Lamp"],
        "aliases": ["leak detector", "sniffer"],
        "unit": "EA",
        "definition": "Handheld detector that finds refrigerant leaks.",
    },
    {
        "canonical": "HVAC Fuse",
        "suffixes": ["3 Amp", "5 Amp"],
        "aliases": ["fuse", "furnace fuse", "control fuse"],
        "unit": "EA",
        "definition": "Control-circuit fuse for furnace and condenser boards.",
    },
    {
        "canonical": "Pressure Switch",
        "suffixes": ["Standard", "Dual"],
        "aliases": ["pressure switch", "draft pressure switch"],
        "unit": "EA",
        "definition": "Safety switch that verifies inducer draft on a condensing furnace.",
    },
    {
        "canonical": "Flue Pipe Connector",
        "suffixes": ["6 in", "8 in"],
        "aliases": ["flue connector", "vent connector"],
        "unit": "EA",
        "definition": "Single-wall metal connector between a water heater or furnace and the chimney.",
    },
    {
        "canonical": "Chimney Liner",
        "suffixes": ["Flex 6 in", "Flex 8 in"],
        "aliases": ["chimney liner", "flue liner"],
        "unit": "LF",
        "definition": "Flexible stainless liner that relines a masonry chimney.",
    },
    {
        "canonical": "Attic Insulation Support",
        "suffixes": ["Wire", "Spiral"],
        "aliases": ["insulation support", "batt hanger"],
        "unit": "EA",
        "definition": "Support that holds batts in place between exposed joists.",
    },

    {
        "canonical": "Smart AC Controller",
        "suffixes": ["Sensi", "Tado"],
        "aliases": ["smart ac", "window ac controller", "mini split wifi"],
        "unit": "EA",
        "definition": "Wi-Fi controller that makes mini splits and window AC voice-controlled.",
    },
    {
        "canonical": "Mini Split Remote",
        "suffixes": ["Standard", "Wi-Fi Adapter"],
        "aliases": ["ductless remote", "mini split controller"],
        "unit": "EA",
        "definition": "IR remote or Wi-Fi dongle for a ductless head.",
    },
    {
        "canonical": "Boiler Flush Kit",
        "suffixes": ["Standard"],
        "aliases": ["flush kit", "system cleaner kit"],
        "unit": "EA",
        "definition": "Hoses and valves used to flush and descale a hydronic system.",
    },
    {
        "canonical": "Radiator Bleed Key",
        "suffixes": ["Standard", "Multi-Size"],
        "aliases": ["bleed key", "radiator key"],
        "unit": "EA",
        "definition": "Small square key that vents air from radiators.",
    },
    {
        "canonical": "HVAC Hose Bibb Valve",
        "suffixes": ["3/4 in"],
        "aliases": ["boiler drain", "hose valve"],
        "unit": "EA",
        "definition": "Drain valve used to fill and purge hydronic systems.",
    },
]

