"""Plumbing lexicon families: pipe stock, fittings, valves, fixtures,
drainage, and the brand names STT hears daily (Moen, Kohler, Rinnai...)."""

TRADE = "Plumbing"

FAMILIES = [
    # ---- Pipe stock -----------------------------------------------------------
    {
        "canonical": "PEX-A Pipe",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "lengths": ["100 ft", "300 ft"],
        "aliases": ["pex a", "uponor pex", "expansion pex", "pex pipe"],
        "unit": "LF",
        "definition": "Cross-linked polyethylene hot-and-cold water supply pipe; PEX-A expands for fittings.",
    },
    {
        "canonical": "PEX-B Pipe",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "lengths": ["100 ft", "300 ft"],
        "aliases": ["pex b", "crimp pex", "sioux chief pex"],
        "unit": "LF",
        "definition": "Crimp-ring PEX supply pipe; the most common PEX for residential repipes.",
    },
    {
        "canonical": "Copper Pipe Type M",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "lengths": ["10 ft", "20 ft"],
        "aliases": ["type m copper", "copper pipe", "thin wall copper"],
        "unit": "LF",
        "definition": "Thin-wall copper supply pipe for standard residential water distribution.",
    },
    {
        "canonical": "Copper Pipe Type L",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "lengths": ["10 ft", "20 ft"],
        "aliases": ["type l copper", "thick wall copper"],
        "unit": "LF",
        "definition": "Heavier-wall copper used where higher pressure or exposure demands more metal.",
    },
    {
        "canonical": "PVC Schedule 40 Pipe",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/4\"", "1-1/2\"", "2\""],
        "lengths": ["10 ft"],
        "aliases": ["pvc pipe", "schedule 40 pvc", "pvc40"],
        "unit": "LF",
        "definition": "Rigid white PVC for cold-water supply and DWV drainage above ground.",
    },
    {
        "canonical": "PVC Schedule 80 Pipe",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/4\"", "1-1/2\"", "2\""],
        "lengths": ["10 ft"],
        "aliases": ["schedule 80 pvc", "gray pvc", "pvc80"],
        "unit": "LF",
        "definition": "Heavy-wall gray PVC for higher-pressure and industrial applications.",
    },
    {
        "canonical": "CPVC Pipe",
        "suffixes": ["1/2\"", "3/4\""],
        "lengths": ["10 ft"],
        "aliases": ["cpvc", "flowguard gold", "chlorinated pvc"],
        "unit": "LF",
        "definition": "Chlorinated PVC rated for hot water; glued with orange CPVC cement.",
    },
    {
        "canonical": "ABS DWV Pipe",
        "suffixes": ["1-1/2\"", "2\"", "3\"", "4\""],
        "lengths": ["10 ft"],
        "aliases": ["abs pipe", "black drain pipe", "abs"],
        "unit": "LF",
        "definition": "Black plastic drain-waste-vent pipe joined with solvent cement.",
    },
    {
        "canonical": "Cast Iron Pipe",
        "suffixes": ["2\"", "3\"", "4\""],
        "lengths": ["10 ft"],
        "aliases": ["cast iron", "no hub cast iron", "service weight"],
        "unit": "LF",
        "definition": "Heavy no-hub cast iron for DWV where sound deadening matters; joined with rubber couplings.",
    },
    {
        "canonical": "Galvanized Steel Pipe",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "lengths": ["10 ft"],
        "aliases": ["galvanized pipe", "steel pipe", "galv pipe"],
        "unit": "LF",
        "definition": "Zinc-coated threaded steel pipe, mostly found in older homes' water supply.",
    },
    {
        "canonical": "Polyethylene Water Pipe",
        "suffixes": ["3/4\"", "1\""],
        "lengths": ["100 ft", "300 ft"],
        "aliases": ["pe pipe", "poly pipe", "black water line", "polyethylene"],
        "unit": "LF",
        "definition": "Black PE pipe for underground water service from the meter to the house.",
    },
    {
        "canonical": "Black Iron Gas Pipe",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "lengths": ["10 ft", "21 ft"],
        "aliases": ["black iron", "gas pipe", "steel gas pipe"],
        "unit": "LF",
        "definition": "Threaded black steel pipe for natural gas and propane distribution.",
    },
    {
        "canonical": "Flexible Gas Connector",
        "suffixes": ["1/2 x 24", "3/4 x 36"],
        "aliases": ["gas flex line", "csst", "appliance connector", "gas line"],
        "unit": "EA",
        "definition": "Corrugated stainless steel flexible gas connector for appliances.",
    },
    {
        "canonical": "Radiant PEX Tubing",
        "suffixes": ["1/2\"", "3/4\""],
        "lengths": ["300 ft", "500 ft"],
        "aliases": ["radiant pex", "in floor pex", "underfloor heating tube"],
        "unit": "LF",
        "definition": "Oxygen-barrier PEX tubing embedded in slabs or subfloor for radiant heat.",
    },
    # ---- Fittings -------------------------------------------------------------
    {
        "canonical": "PEX Elbow",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["pex 90", "pex bend", "pex elbow fitting"],
        "unit": "EA",
        "definition": "90-degree PEX fitting for turning supply lines; crimp or expansion style.",
    },
    {
        "canonical": "PEX Coupling",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["pex coupler", "pex splice"],
        "unit": "EA",
        "definition": "Straight PEX-to-PEX fitting for joining two lengths of supply pipe.",
    },
    {
        "canonical": "PEX Tee",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["pex t", "pex branch fitting"],
        "unit": "EA",
        "definition": "Three-way PEX fitting that branches a supply line without soldering.",
    },
    {
        "canonical": "Copper 90 Elbow",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["copper elbow", "sweat 90", "solder elbow"],
        "unit": "EA",
        "definition": "Sweat-solder 90-degree copper fitting for supply lines.",
    },
    {
        "canonical": "Copper Coupling",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["copper coupler", "sweat coupling"],
        "unit": "EA",
        "definition": "Sweat-solder straight fitting joining two copper pipes.",
    },
    {
        "canonical": "Copper Tee",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["sweat tee", "copper t"],
        "unit": "EA",
        "definition": "Sweat-solder three-way copper fitting for branch lines.",
    },
    {
        "canonical": "SharkBite Push Fitting",
        "suffixes": ["Elbow 1/2\"", "Elbow 3/4\"", "Coupling 1/2\"", "Coupling 3/4\"", "Tee 1/2\"", "Tee 3/4\""],
        "aliases": ["sharkbite", "push to connect", "push fit"],
        "unit": "EA",
        "definition": "Push-to-connect fitting that joins copper, PEX, or CPVC without soldering.",
        "phonetic": "SHARK-bite",
        "ipa": "/ˈʃɑːrkbaɪt/",
    },
    {
        "canonical": "PEX Manifold",
        "suffixes": ["8 Port", "10 Port", "12 Port"],
        "aliases": ["manifold", "pex manifold", "home run manifold"],
        "unit": "EA",
        "definition": "Central distribution block running each fixture on its own PEX home run.",
    },
    {
        "canonical": "Stub Out Ell",
        "suffixes": ["1/2 x 6", "1/2 x 8"],
        "aliases": ["stub out", "drop ear ell", "stub ell"],
        "unit": "EA",
        "definition": "Pre-formed supply stub that comes through the wall plate for a fixture hookup.",
    },
    {
        "canonical": "PVC 90 Elbow",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/2\"", "2\""],
        "aliases": ["pvc elbow", "pvc 90"],
        "unit": "EA",
        "definition": "Solvent-welded PVC elbow for drainage and cold-water turns.",
    },
    {
        "canonical": "PVC Coupling",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/2\"", "2\""],
        "aliases": ["pvc coupler", "pvc splice"],
        "unit": "EA",
        "definition": "Straight solvent-welded PVC joint for extending a pipe run.",
    },
    {
        "canonical": "PVC Tee",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/2\"", "2\""],
        "aliases": ["pvc t", "pvc branch"],
        "unit": "EA",
        "definition": "Three-way solvent-welded PVC fitting for branch takeoffs.",
    },
    {
        "canonical": "PVC Cap",
        "suffixes": ["1\"", "1-1/2\"", "2\""],
        "aliases": ["pvc end cap", "pvc plug"],
        "unit": "EA",
        "definition": "Solvent-welded cap that closes the end of a PVC run.",
    },
    {
        "canonical": "PVC Wye Fitting",
        "suffixes": ["2\"", "3\"", "4\""],
        "aliases": ["wye", "sanitary tee", "pvc wye"],
        "unit": "EA",
        "definition": "Y-shaped DWV fitting that joins a branch drain at a gradual angle.",
    },

    # ---- Valves ---------------------------------------------------------------
    {
        "canonical": "Brass Ball Valve",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/4\""],
        "aliases": ["ball valve", "quarter turn valve", "brass valve"],
        "unit": "EA",
        "definition": "Quarter-turn brass shutoff for supply lines; the standard house water valve.",
    },
    {
        "canonical": "PVC Ball Valve",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "1-1/2\""],
        "aliases": ["pvc valve", "plastic ball valve"],
        "unit": "EA",
        "definition": "Solvent-welded PVC shutoff for irrigation and cold-water lines.",
    },
    {
        "canonical": "Gate Valve",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["gate valve", "full port gate"],
        "unit": "EA",
        "definition": "Rising-stem full-flow shutoff valve; common on main water services.",
    },
    {
        "canonical": "Check Valve",
        "suffixes": ["1/2\"", "3/4\"", "1\"", "2\""],
        "aliases": ["check valve", "swing check", "spring check"],
        "unit": "EA",
        "definition": "One-way valve that prevents backflow in supply and pump lines.",
    },
    {
        "canonical": "Globe Valve",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["globe valve", "throttling valve"],
        "unit": "EA",
        "definition": "Multi-turn valve designed for throttling and fine flow control.",
    },
    {
        "canonical": "Angle Stop Valve",
        "suffixes": ["1/2 x 3/8", "1/2 x 1/2"],
        "aliases": ["angle stop", "supply stop", "shutoff valve"],
        "unit": "EA",
        "definition": "Compression shutoff at sinks and toilets connecting the supply stub to the fixture.",
    },
    {
        "canonical": "Pressure Reducing Valve",
        "suffixes": ["3/4\"", "1\""],
        "aliases": ["prv", "pressure regulator", "water pressure valve"],
        "unit": "EA",
        "definition": "Regulates street water pressure down to a safe 50-60 psi for the house.",
    },
    {
        "canonical": "Hose Bibb",
        "suffixes": ["1/2\" Standard", "3/4\" Frost-Free", "1/2\" Anti-Siphon"],
        "aliases": ["sillcock", "silcock", "hose spigot", "outdoor faucet", "spigot", "outdoor tap"],
        "unit": "EA",
        "definition": "Exterior water faucet for garden hoses; frost-free models shut off inside the wall.",
        "phonetic": "HOZE bibb",
        "ipa": "/hoʊz bɪb/",
    },
    {
        "canonical": "Backflow Preventer",
        "suffixes": ["3/4\"", "1\"", "Reduced Pressure 1\""],
        "aliases": ["backflow valve", "rpb", "double check"],
        "unit": "EA",
        "definition": "Protects the potable supply from contamination by irrigation or fire lines.",
    },
    {
        "canonical": "Water Hammer Arrestor",
        "suffixes": ["1/2\"", "3/4\""],
        "aliases": ["water hammer", "shock arrestor", "hammer stop"],
        "unit": "EA",
        "definition": "Air-chamber device that stops the bang when fast-closing valves slam shut.",
    },

    # ---- Fixtures -------------------------------------------------------------
    {
        "canonical": "Toilet",
        "suffixes": ["1.28 GPF Elongated", "1.28 GPF Round", "1.6 GPF Elongated", "Comfort Height 1.28"],
        "aliases": ["toilet", "water closet", "wc", "commode"],
        "unit": "EA",
        "definition": "Two-piece water closet with low-flow flush; comfort-height is ADA-friendly.",
    },
    {
        "canonical": "TOTO Toilet",
        "suffixes": ["Drake", "Ultramax", "Entrada"],
        "aliases": ["toto", "toto wc"],
        "unit": "EA",
        "definition": "TOTO-brand toilet with the powerful Tornado flush and quiet-close lid.",
        "phonetic": "TOE-toe",
        "ipa": "/ˈtoʊtoʊ/",
    },
    {
        "canonical": "Kohler Toilet",
        "suffixes": ["Cimarron", "Highline", "Wellworth"],
        "aliases": ["kohler wc"],
        "unit": "EA",
        "definition": "Kohler-brand toilet known for class-five flushing technology.",
        "phonetic": "KOE-ler",
        "ipa": "/ˈkoʊlər/",
    },
    {
        "canonical": "Bathroom Sink",
        "suffixes": ["Pedestal", "Vessel", "Drop-In", "Undermount"],
        "aliases": ["vanity sink", "lavatory", "bathroom lav"],
        "unit": "EA",
        "definition": "Bathroom lavatory mounted on a pedestal, counter, or vanity top.",
    },
    {
        "canonical": "Kitchen Sink",
        "suffixes": ["Stainless 33 x 22", "Cast Iron", "Composite Granite", "Farmhouse"],
        "aliases": ["kitchen sink", "farm sink"],
        "unit": "EA",
        "definition": "Kitchen basin; stainless is the standard, farmhouse adds an exposed apron.",
    },
    {
        "canonical": "Kitchen Faucet",
        "suffixes": ["Pull-Down", "Pull-Out", "Two Handle", "Touchless"],
        "aliases": ["kitchen faucet", "kitchen tap"],
        "unit": "EA",
        "definition": "Residential kitchen faucet with pull-down or pull-out spray head.",
    },
    {
        "canonical": "Moen Faucet",
        "suffixes": ["Arbor", "One-Handle Bath", "PosiTemp Shower Valve"],
        "aliases": ["moen", "moen fixture"],
        "unit": "EA",
        "definition": "Moen-brand faucet or shower valve with pull-down spray and lifetime warranty.",
        "phonetic": "MOAN",
        "ipa": "/moʊn/",
    },
    {
        "canonical": "Delta Faucet",
        "suffixes": ["Leland", "Windemere", "Trinsic"],
        "aliases": ["delta faucet", "delta fixture"],
        "unit": "EA",
        "definition": "Delta-brand faucet with Diamond Seal technology.",
        "phonetic": "DEL-tuh",
        "ipa": "/ˈdɛltə/",
    },
    {
        "canonical": "Kohler Faucet",
        "suffixes": ["Vinnata", "Bellera", "Simplice"],
        "aliases": ["kohler faucet", "kohler tap"],
        "unit": "EA",
        "definition": "Kohler-brand kitchen or bath faucet.",
        "phonetic": "KOE-ler",
        "ipa": "/ˈkoʊlər/",
    },
    {
        "canonical": "Shower System",
        "suffixes": ["Rainhead 8 inch", "Handheld Combo", "Slide Bar"],
        "aliases": ["shower head", "rain shower", "shower fixture"],
        "unit": "EA",
        "definition": "Overhead or handheld showering fixture with the valve and trim.",
    },
    {
        "canonical": "Bathtub",
        "suffixes": ["Alcove 60 x 32", "Drop-In", "Freestanding", "Whirlpool"],
        "aliases": ["tub", "soaking tub", "bath tub"],
        "unit": "EA",
        "definition": "Residential bathtub; alcove is the standard stud-to-stub installation.",
    },
    {
        "canonical": "Tub Drain Kit",
        "suffixes": ["With Overflow", "Without Overflow"],
        "aliases": ["tub drain", "bathtub drain assembly"],
        "unit": "EA",
        "definition": "Drain, overflow, and trip-lever waste assembly for a bathtub.",
    },
    {
        "canonical": "Gas Water Heater",
        "suffixes": ["40 Gallon", "50 Gallon", "75 Gallon"],
        "aliases": ["water heater", "hot water tank", "gas tank heater"],
        "unit": "EA",
        "definition": "Natural-gas storage water heater; 40/50 gallon is the standard home size.",
    },
    {
        "canonical": "Electric Water Heater",
        "suffixes": ["40 Gallon", "50 Gallon", "80 Gallon"],
        "aliases": ["electric water heater", "electric tank"],
        "unit": "EA",
        "definition": "Electric storage water heater with dual elements.",
    },
    {
        "canonical": "Tankless Water Heater",
        "suffixes": ["Rinnai RUC98", "Navien NPE-240A", "Rheem RTGH-68"],
        "aliases": ["tankless", "on demand water heater", "instant hot water"],
        "unit": "EA",
        "definition": "Condensing on-demand water heater that never runs out of hot water.",
    },
    {
        "canonical": "Sump Pump",
        "suffixes": ["1/3 HP", "1/2 HP", "Battery Backup"],
        "aliases": ["sump pump", "pedestal pump", "submersible pump"],
        "unit": "EA",
        "definition": "Submersible or pedestal pump that clears the basement sump pit.",
    },
    {
        "canonical": "Garbage Disposal",
        "suffixes": ["1/2 HP", "3/4 HP", "1 HP"],
        "aliases": ["disposal", "garbage disposal", "food waste disposer"],
        "unit": "EA",
        "definition": "Under-sink food waste grinder; 3/4 HP is the residential sweet spot.",
    },

    {
        "canonical": "Water Softener",
        "suffixes": ["30,000 Grain", "40,000 Grain", "64,000 Grain"],
        "aliases": ["softener", "water softener", "water conditioner"],
        "unit": "EA",
        "definition": "Salt-based ion-exchange system that strips hardness from the whole house.",
    },
    {
        "canonical": "Whole House Water Filter",
        "suffixes": ["20 Inch", "2 Stage"],
        "aliases": ["whole house filter", "point of entry filter"],
        "unit": "EA",
        "definition": "In-line filter housing on the main that removes sediment and chlorine.",
    },
    {
        "canonical": "Recirculation Pump",
        "suffixes": ["1/6 HP", "1/12 HP"],
        "aliases": ["recirc pump", "hot water recirculator"],
        "unit": "EA",
        "definition": "Small pump that keeps hot water circulating so fixtures get it instantly.",
    },
    # ---- Drainage & repair parts ----------------------------------------------
    {
        "canonical": "P-Trap",
        "suffixes": ["1-1/4\"", "1-1/2\"", "2\""],
        "aliases": ["p trap", "trap", "sink trap"],
        "unit": "EA",
        "definition": "U-bend trap under a sink that keeps sewer gas out of the room.",
    },
    {
        "canonical": "Cleanout Plug",
        "suffixes": ["2\"", "3\"", "4\""],
        "aliases": ["cleanout", "clean out fitting", "wc cleanout"],
        "unit": "EA",
        "definition": "Access fitting in a drain line that lets a snake or camera in.",
    },
    {
        "canonical": "Toilet Flange",
        "suffixes": ["Standard", "Offset", "Repair Ring"],
        "aliases": ["toilet flange", "closet flange", "wc flange"],
        "unit": "EA",
        "definition": "PVC or metal ring that anchors the toilet to the waste pipe.",
    },
    {
        "canonical": "Pipe Insulation",
        "suffixes": ["1/2 x 3/8", "3/4 x 3/8", "1 x 1/2"],
        "aliases": ["pipe wrap", "water pipe insulation", "foam pipe insulation"],
        "unit": "LF",
        "definition": "Closed-cell foam wrap for hot and cold supply pipes; prevents sweating and heat loss.",
    },
    {
        "canonical": "Escutcheon Plate",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["escutcheon", "pipe trim ring", "wall escutcheon"],
        "unit": "EA",
        "definition": "Chrome or plastic ring that finishes a pipe passing through a wall.",
    },
    {
        "canonical": "Braided Supply Line",
        "suffixes": ["20 Inch", "30 Inch", "1/2 x 3/8"],
        "aliases": ["supply line", "faucet supply", "braided hose"],
        "unit": "EA",
        "definition": "Pre-made stainless braided supply connecting shutoff to faucet or toilet.",
    },
    {
        "canonical": "Water Heater Pan",
        "suffixes": ["24 Inch", "28 Inch"],
        "aliases": ["heater pan", "drip pan", "water heater drain pan"],
        "unit": "EA",
        "definition": "Metal or plastic pan under the tank that drains leaks to a floor drain.",
    },

    {
        "canonical": "T&P Relief Valve",
        "suffixes": ["3/4 x 6", "3/4 x 12"],
        "aliases": ["tp valve", "temperature pressure relief", "t and p valve"],
        "unit": "EA",
        "definition": "Safety valve on a water heater that relieves pressure or overtemperature.",
    },
    {
        "canonical": "Wax Ring",
        "suffixes": ["Standard", "Reinforced", "Wax Free"],
        "aliases": ["wax seal", "toilet wax ring", "wc seal"],
        "unit": "EA",
        "definition": "Compressible wax seal between toilet and flange that blocks sewer gas.",
    },
    {
        "canonical": "Toilet Fill Valve",
        "suffixes": ["Universal", "Quiet Fill"],
        "aliases": ["fill valve", "toilet valve", "ballcock"],
        "unit": "EA",
        "definition": "Refills the toilet tank after a flush; Fluidmaster is the standard brand.",
    },
    {
        "canonical": "Toilet Flapper",
        "suffixes": ["Universal", "Rubber"],
        "aliases": ["flapper", "tank flapper", "flush valve seal"],
        "unit": "EA",
        "definition": "Rubber stopper that holds and releases water from the tank into the bowl.",
    },
    {
        "canonical": "Toilet Seat",
        "suffixes": ["Round", "Elongated", "Slow Close"],
        "aliases": ["toilet seat", "wc seat"],
        "unit": "EA",
        "definition": "Residential toilet seat; slow-close hinges are the standard upgrade.",
    },
    {
        "canonical": "Plumbers Putty",
        "suffixes": ["12 oz", "24 oz"],
        "aliases": ["plumbers putty", "putty"],
        "unit": "TUBE",
        "definition": "Soft sealing compound for sink drains, faucets, and tubs.",
    },
    {
        "canonical": "Teflon Tape",
        "suffixes": ["1/2 Inch", "3/4 Inch"],
        "aliases": ["teflon tape", "thread seal tape", "plumbers tape", "ptfe tape"],
        "unit": "ROLL",
        "definition": "PTFE thread-sealing tape wrapped on pipe threads to stop leaks.",
    },
    {
        "canonical": "Pipe Dope",
        "suffixes": ["4 oz", "16 oz"],
        "aliases": ["pipe joint compound", "pipe sealant"],
        "unit": "TUBE",
        "definition": "Thread-sealing paste for metal and plastic pipe joints.",
    },
    {
        "canonical": "Lead Free Solder",
        "suffixes": ["1/2 Lb", "1 Lb"],
        "aliases": ["solder", "silver solder", "95/5"],
        "unit": "LB",
        "definition": "Lead-free tin/silver solder for copper sweat joints.",
    },
    {
        "canonical": "Soldering Flux",
        "suffixes": ["2 oz", "8 oz"],
        "aliases": ["flux", "paste flux", "rosin flux"],
        "unit": "JAR",
        "definition": "Cleaning paste applied to copper before soldering for a clean joint.",
    },
    {
        "canonical": "PVC Cement",
        "suffixes": ["4 oz", "8 oz", "16 oz"],
        "aliases": ["pvc glue", "solvent cement", "pvc solvent"],
        "unit": "CAN",
        "definition": "Solvent weld cement for joining PVC pipe and fittings.",
    },
    {
        "canonical": "PVC Primer",
        "suffixes": ["4 oz", "8 oz"],
        "aliases": ["purple primer", "pvc cleaner", "solvent cleaner"],
        "unit": "CAN",
        "definition": "Purple cleaner-primer applied before PVC cement for a code-visible joint.",
    },

    # ---- Brands (hand-written phonetics for STT) --------------------------------
    {
        "canonical": "Uponor PEX",
        "suffixes": ["AquaPEX", "Wirsbo", "Expansion Tool"],
        "aliases": ["uponor", "wirsbo pex", "aquadynamic"],
        "unit": "EA",
        "definition": "The PEX-A expansion brand; original system uses cold-expansion tools.",
        "phonetic": "U-pon-or",
        "ipa": "/ˈjuːpənɔːr/",
    },
    {
        "canonical": "Watts Valves",
        "suffixes": ["Pressure Reducing", "Backflow", "Manifold"],
        "aliases": ["watts", "watts regulator"],
        "unit": "EA",
        "definition": "Watts brand pressure, backflow, and water safety products.",
        "phonetic": "WATS",
        "ipa": "/wɒts/",
    },
    {
        "canonical": "Rinnai Tankless",
        "suffixes": ["RUC98i", "RSC199"],
        "aliases": ["rinnai", "rinnai tankless water heater"],
        "unit": "EA",
        "definition": "Rinnai condensing tankless water heaters.",
        "phonetic": "ri-NAY",
        "ipa": "/rɪˈneɪ/",
    },
    {
        "canonical": "Navien Tankless",
        "suffixes": ["NPE-A2", "NCB-E"],
        "aliases": ["navien", "navien combi"],
        "unit": "EA",
        "definition": "Navien condensing tankless and combi boilers.",
        "phonetic": "NAV-ee-en",
        "ipa": "/ˈnæviən/",
    },
    {
        "canonical": "Rheem Water Heater",
        "suffixes": ["Performance", "Prestige", "Marathon"],
        "aliases": ["rheem", "rheem tank"],
        "unit": "EA",
        "definition": "Rheem gas, electric, and hybrid water heaters.",
        "phonetic": "REEM",
        "ipa": "/riːm/",
    },
    {
        "canonical": "American Standard Fixtures",
        "suffixes": ["Cadet Toilet", "Studio Faucet"],
        "aliases": ["american standard", "am standard"],
        "unit": "EA",
        "definition": "American Standard toilets and faucets.",
        "phonetic": "uh-MER-ih-kun STAN-durd",
        "ipa": "/əˈmɛrɪkən ˈstændərd/",
    },
    {
        "canonical": "Bradford White Water Heater",
        "suffixes": ["Defender", "RE2 Series"],
        "aliases": ["bradford white", "bw tank"],
        "unit": "EA",
        "definition": "Bradford White residential water heaters.",
        "phonetic": "BRAD-furd WITE",
        "ipa": "/ˈbrædfərd waɪt/",
    },
    {
        "canonical": "Taco Pumps",
        "suffixes": ["007 Circulator", "169008 Zone Valve"],
        "aliases": ["taco pump", "taco circulator"],
        "unit": "EA",
        "definition": "Taco circulator pumps and zone valves for hydronic systems.",
        "phonetic": "TACK-oh",
        "ipa": "/ˈtækoʊ/",
    },
    {
        "canonical": "Grundfos Pump",
        "suffixes": ["UPS15-58", "CR Series"],
        "aliases": ["grundfos", "grundfos circulator"],
        "unit": "EA",
        "definition": "Grundfos circulation and booster pumps.",
        "phonetic": "GROOND-fos",
        "ipa": "/ˈɡrʊntfɔs/",
    },
    {
        "canonical": "NIBCO Fittings",
        "suffixes": ["Copper Elbow", "PVC Fitting"],
        "aliases": ["nibco", "nibco fitting"],
        "unit": "EA",
        "definition": "NIBCO copper and PVC fittings.",
        "phonetic": "NIB-co",
        "ipa": "/ˈnɪbkoʊ/",
    },
    {
        "canonical": "Viega PEX",
        "suffixes": ["FostaPEX", "ProPEX Adapter"],
        "aliases": ["viega", "viega pex"],
        "unit": "EA",
        "definition": "Viega press and PEX systems.",
        "phonetic": "VEE-a-ga",
        "ipa": "/ˈviːəɡə/",
    },
    {
        "canonical": "Charlotte Pipe",
        "suffixes": ["PVC DWV", "Cast Iron"],
        "aliases": ["charlotte pvc", "charlotte pipe"],
        "unit": "EA",
        "definition": "Charlotte Pipe & Foundry drainage products.",
        "phonetic": "SHAR-lit",
        "ipa": "/ˈʃɑːrlət/",
    },
    {
        "canonical": "Zurn Drainage",
        "suffixes": ["Floor Drain", "Roof Drain"],
        "aliases": ["zurn", "zurn drain"],
        "unit": "EA",
        "definition": "Zurn floor, roof, and trench drains.",
        "phonetic": "ZURN",
        "ipa": "/zɜːrn/",
    },
    {
        "canonical": "Fluidmaster Toilet Parts",
        "suffixes": ["400 Fill Valve", "Flapper"],
        "aliases": ["fluidmaster", "fluid master"],
        "unit": "EA",
        "definition": "Fluidmaster fill valves and flappers.",
        "phonetic": "FLUE-id-mas-ter",
        "ipa": "/ˈfluːɪdˌmæstər/",
    },
    {
        "canonical": "Eastman Supply Lines",
        "suffixes": ["Braided 20", "PEX Adapter"],
        "aliases": ["eastman", "eastman supply"],
        "unit": "EA",
        "definition": "Eastman braided supply lines and fittings.",
        "phonetic": "EEST-man",
        "ipa": "/ˈiːstmən/",
    },

    {
        "canonical": "PEX Crimp Ring",
        "suffixes": ["3/8\"", "1/2\"", "3/4\"", "1\""],
        "aliases": ["crimp ring", "pex ring", "crimp clamp"],
        "unit": "EA",
        "definition": "Copper or stainless ring crushed onto PEX-B to lock the fitting.",
    },
    {
        "canonical": "PEX Crimp Tool",
        "suffixes": ["Go-No-Go", "Milwaukee M12"],
        "aliases": ["crimp tool", "pex crimper"],
        "unit": "EA",
        "definition": "Manual or cordless tool that installs PEX crimp rings.",
    },
    {
        "canonical": "PEX Cutter",
        "suffixes": ["Ratchet", "Scissor"],
        "aliases": ["pex cutter", "pipe cutter"],
        "unit": "EA",
        "definition": "Clean square-cutting tool for PEX and soft copper.",
    },
    {
        "canonical": "Shower Valve Trim",
        "suffixes": ["Rough-In", "Finish Kit"],
        "aliases": ["shower valve", "shower mixing valve"],
        "unit": "EA",
        "definition": "Pressure-balance valve and trim for a shower system.",
    },
    {
        "canonical": "Tub Spout",
        "suffixes": ["6 Inch", "Diverter"],
        "aliases": ["tub spout", "bathtub spout"],
        "unit": "EA",
        "definition": "Wall-mounted spout that diverts water between tub and shower.",
    },
    {
        "canonical": "Shower Arm",
        "suffixes": ["6 Inch", "12 Inch"],
        "aliases": ["shower arm", "shower elbow"],
        "unit": "EA",
        "definition": "Threaded pipe that carries the showerhead off the wall.",
    },
    {
        "canonical": "Pipe Hanger",
        "suffixes": ["1/2\"", "3/4\"", "1\""],
        "aliases": ["pipe hanger", "pipe strap", "plumber tape"],
        "unit": "EA",
        "definition": "Metal strap or hanger that supports horizontal and vertical pipe runs.",
    },
    {
        "canonical": "Faucet Cartridge",
        "suffixes": ["Moen 1225", "Delta 1300", "Kohler Valve"],
        "aliases": ["faucet cartridge", "mixing cartridge", "valve cartridge"],
        "unit": "EA",
        "definition": "Replaceable ceramic or plastic cartridge inside a faucet or shower valve.",
    },
    {
        "canonical": "Valve Box",
        "suffixes": ["6 Inch", "12 Inch"],
        "aliases": ["valve box", "irrigation valve box"],
        "unit": "EA",
        "definition": "Buried enclosure that protects a main or irrigation shutoff.",
    },
    {
        "canonical": "Sump Basin",
        "suffixes": ["18 Inch", "24 Inch"],
        "aliases": ["sump pit", "sump crock", "basin"],
        "unit": "EA",
        "definition": "Cylindrical pit that collects groundwater for the sump pump.",
    },
    {
        "canonical": "Toilet Tank Bolts",
        "suffixes": ["Brass", "Stainless"],
        "aliases": ["tank bolts", "closet bolts", "toilet bolts"],
        "unit": "EA",
        "definition": "Bolts and washers that fasten the tank to the bowl or the bowl to the floor.",
    },
    {
        "canonical": "Shutoff Key",
        "suffixes": ["Curb Key", "Meter Key"],
        "aliases": ["curb key", "water key", "shutoff key"],
        "unit": "EA",
        "definition": "Long-handled key that reaches the street shutoff or meter valve.",
    },
]

