"""Roofing & siding lexicon families: shingles (brand x color), underlayment,
metal roofing, gutters, flashing, siding profiles/colors, soffit, vents."""

TRADE = "Roofing & Siding"

FAMILIES = [
    # ---- Shingles --------------------------------------------------------------
    {
        "canonical": "GAF Timberline Shingles",
        "suffixes": ["HDZ Charcoal", "HDZ Weathered Wood", "HDZ Pewter Gray", "HDZ Estate Gray", "UHD Slate"],
        "aliases": ["gaf shingles", "timberline", "architectural shingles", "timberline hdz"],
        "unit": "SQ",
        "definition": "GAF Timberline architectural shingles; HDZ is the flagship line.",
        "phonetic": "TIM-ber-line",
        "ipa": "/ˈtɪmbərlaɪn/",
    },
    {
        "canonical": "Owens Corning Shingles",
        "suffixes": ["Duration Charcoal", "Duration Weathered Wood", "TruDefinition Estate Gray", "TruDefinition Driftwood"],
        "aliases": ["owens corning", "duration shingles", "oc shingles"],
        "unit": "SQ",
        "definition": "Owens Corning Duration architectural shingles with SureNail strip.",
        "phonetic": "OH-enz KOR-ning",
        "ipa": "/ˈoʊənz ˈkɔːrnɪŋ/",
    },
    {
        "canonical": "CertainTeed Shingles",
        "suffixes": ["Landmark Weathered Wood", "Landmark Moire Black", "Landmark Pro Driftwood"],
        "aliases": ["certainteed", "landmark shingles", "certain teed"],
        "unit": "SQ",
        "definition": "CertainTeed Landmark architectural shingles.",
        "phonetic": "SUR-tin-teed",
        "ipa": "/ˈsɜːrtɪntiːd/",
    },
    {
        "canonical": "Three Tab Shingles",
        "suffixes": ["Standard", "Impact Resistant"],
        "aliases": ["3 tab", "three tab", "strip shingle"],
        "unit": "SQ",
        "definition": "Budget flat shingle with three cutouts; rarely specified on new roofs.",
    },
    {
        "canonical": "Synthetic Roofing Shingles",
        "suffixes": ["Cedar Shake", "Slate", "Clay Tile"],
        "aliases": ["synthetic shake", "synthetic slate", "composite shingle"],
        "unit": "SQ",
        "definition": "Recycled-polymer shingles that mimic shake, slate, or tile.",
    },
    {
        "canonical": "Starter Shingle",
        "suffixes": ["3-Tab", "Architectural"],
        "aliases": ["starter course", "starter strip"],
        "unit": "SQ",
        "definition": "Pre-cut first-course shingle that seals the eaves against wind.",
    },
    {
        "canonical": "Ridge Cap Shingle",
        "suffixes": ["Standard", "Hip Cap"],
        "aliases": ["ridge cap", "hip shingle", "ridge shingle"],
        "unit": "EA",
        "definition": "Bent tab shingle that covers the ridge and hip lines.",
    },
    {
        "canonical": "Cedar Shingle",
        "suffixes": ["Perfection", "Hand Split", "Medium"],
        "aliases": ["cedar shakes", "cedar shingles"],
        "unit": "SQ",
        "definition": "Western red cedar shake or shingle roofing.",
    },
    # ---- Underlayment & deck protection ----------------------------------------
    {
        "canonical": "Roofing Felt Underlayment",
        "suffixes": ["15 lb", "30 lb"],
        "aliases": ["roof felt", "tar paper", "builder felt"],
        "unit": "ROLL",
        "definition": "Asphalt-saturated felt installed over the deck before shingles.",
    },
    {
        "canonical": "Synthetic Underlayment",
        "suffixes": ["GAF Tiger Paw", "Titanium UDL 30", "SharkSkin SA", "Deck-Armor"],
        "aliases": ["synthetic felt", "polypropylene underlayment"],
        "unit": "ROLL",
        "definition": "Woven polypropylene underlayment that walks better than felt.",
    },
    {
        "canonical": "Ice and Water Shield",
        "suffixes": ["18 in", "36 in"],
        "aliases": ["ice water shield", "peel and stick underlayment", "ice and water"],
        "unit": "ROLL",
        "definition": "Self-adhering membrane at eaves and valleys that blocks ice dams.",
    },
    {
        "canonical": "Roof Deck Protection",
        "suffixes": ["Zip Deck", "CDX Plus"],
        "aliases": ["roof sheathing protection", "deck protector"],
        "unit": "SF",
        "definition": "Board-and-tape deck systems that weather-protect the roof before shingles.",
    },
    # ---- Metal roofing & gutters ------------------------------------------------
    {
        "canonical": "Metal Roof Panel",
        "suffixes": ["Standing Seam Galvalume", "Standing Seam Copper", "Standing Seam Charcoal", "Corrugated Galvalume", "Corrugated Painted"],
        "aliases": ["standing seam", "metal roof", "corrugated roof"],
        "unit": "SF",
        "definition": "Concealed-fastener metal panels for long-lasting steep or low-slope roofs.",
    },
    {
        "canonical": "Metal Shingle Roofing",
        "suffixes": ["Galvalume", "Painted"],
        "aliases": ["metal shingles", "metal shake"],
        "unit": "SQ",
        "definition": "Interlocking metal shingles that look like shake or slate.",
    },
    {
        "canonical": "Trim Coil",
        "suffixes": ["14 in White", "24 in White", "24 in Charcoal", "14 in Copper"],
        "aliases": ["trim coil", "metal trim coil", "rolled trim"],
        "unit": "LF",
        "definition": "Rolled aluminum sheet bent on site for fascia, rake, and window trim.",
    },
    {
        "canonical": "Seamless Gutter",
        "suffixes": ["5 in White", "5 in Almond", "5 in Brown", "5 in Copper", "6 in White", "6 in Almond", "6 in Brown"],
        "aliases": ["gutters", "rain gutter", "eavestrough"],
        "unit": "LF",
        "definition": "Roll-formed aluminum gutter run to the exact eave length.",
    },
    {
        "canonical": "Downspout",
        "suffixes": ["2x3 White", "2x3 Almond", "2x3 Brown", "3x4 White", "3x4 Brown"],
        "aliases": ["downspout", "down pipe", "leader"],
        "unit": "LF",
        "definition": "Rectangular or round vertical tube carrying gutter water to the ground.",
    },
    {
        "canonical": "Downspout Elbow",
        "suffixes": ["A Style", "B Style"],
        "aliases": ["downspout elbow", "gutter elbow"],
        "unit": "EA",
        "definition": "Pre-formed bend that routes the downspout away from the wall.",
    },
    {
        "canonical": "Downspout Extension",
        "suffixes": ["2 ft", "4 ft"],
        "aliases": ["downspout extension", "splash block adapter"],
        "unit": "EA",
        "definition": "Fold-out extension that carries water past the foundation.",
    },
    {
        "canonical": "Gutter Guard",
        "suffixes": ["Micro-Mesh", "Reverse Curve", "Screen", "Brush"],
        "aliases": ["leaf guard", "gutter cover", "gutter helmet"],
        "unit": "LF",
        "definition": "Cover that lets water in but keeps leaves and debris out.",
    },
    {
        "canonical": "Gutter Hanger",
        "suffixes": ["Hidden", "Strap"],
        "aliases": ["gutter hanger", "gutter bracket"],
        "unit": "EA",
        "definition": "Bracket that supports the gutter and hides behind the cover.",
    },
    {
        "canonical": "Gutter Sealant",
        "suffixes": ["10 oz", "28 oz"],
        "aliases": ["gutter caulk", "gutter sealant"],
        "unit": "TUBE",
        "definition": "Flexible sealant for gutter joints and end caps.",
    },
    {
        "canonical": "Gutter Apron",
        "suffixes": ["Standard", "Wide"],
        "aliases": ["gutter apron", "drip apron"],
        "unit": "LF",
        "definition": "Flashing that sheds water from the deck into the gutter.",
    },

    # ---- Flashing ----------------------------------------------------------------
    {
        "canonical": "Drip Edge",
        "suffixes": ["Standard", "High Heat", "Copper"],
        "aliases": ["drip edge", "eave flashing"],
        "unit": "LF",
        "definition": "L-shaped metal edge that sheds water off the roof deck.",
    },
    {
        "canonical": "Step Flashing",
        "suffixes": ["4 x 4", "5 x 5"],
        "aliases": ["step flashing", "sidewall flashing"],
        "unit": "EA",
        "definition": "Lap pieces woven into shingle courses where a roof meets a wall.",
    },
    {
        "canonical": "Valley Flashing",
        "suffixes": ["W Style", "V Style"],
        "aliases": ["valley flashing", "valley metal"],
        "unit": "LF",
        "definition": "Sheet metal that lines the valley where two roof planes meet.",
    },
    {
        "canonical": "Pipe Boot Flashing",
        "suffixes": ["Rubber 2-3 in", "Rubber 4-5 in", "Lead 2 in"],
        "aliases": ["pipe boot", "vent boot", "roof jack", "plumbing vent flashing"],
        "unit": "EA",
        "definition": "Rubber or lead collar that seals a vent pipe through the roof.",
    },
    {
        "canonical": "Chimney Flashing",
        "suffixes": ["Counter", "Base", "Saddle"],
        "aliases": ["chimney flashing", "cricket"],
        "unit": "LF",
        "definition": "Layered flashing that seals a chimney to the roof, including the cricket.",
    },
    {
        "canonical": "Flashing Roll",
        "suffixes": ["14 in", "20 in"],
        "aliases": ["flashing roll", "aluminum flashing"],
        "unit": "LF",
        "definition": "Rolled aluminum flashing cut on site for transitions.",
    },
    # ---- Roofing vents & coatings -------------------------------------------------
    {
        "canonical": "Ridge Vent",
        "suffixes": ["Roll 10 in", "Rigid 9 in", "Shingle-Over"],
        "aliases": ["ridge vent", "roof ridge vent"],
        "unit": "LF",
        "definition": "Vent along the ridge that lets hot attic air escape.",
    },
    {
        "canonical": "Gable Vent",
        "suffixes": ["12 x 12", "16 x 16"],
        "aliases": ["gable vent", "gable louver"],
        "unit": "EA",
        "definition": "Louvered vent in the gable end that cross-ventilates the attic.",
    },
    {
        "canonical": "Roof Turbine Vent",
        "suffixes": ["12 in", "14 in"],
        "aliases": ["turbine vent", "whirlybird", "wind turbine"],
        "unit": "EA",
        "definition": "Wind-driven spinning vent that pulls hot air from the attic.",
    },
    {
        "canonical": "Soflit Intake Vent",
        "suffixes": ["Round", "Rectangular"],
        "aliases": ["soffit vent", "intake vent", "eave vent"],
        "unit": "EA",
        "definition": "Inlet vent under the eave that feeds the ridge vent system.",
    },
    {
        "canonical": "Roof Coating",
        "suffixes": ["Elastomeric", "Aluminum", "Silicone"],
        "aliases": ["roof coating", "white roof coating"],
        "unit": "GAL",
        "definition": "Reflective coating that extends the life of low-slope roofs.",
    },
    {
        "canonical": "Roof Cement",
        "suffixes": ["1 Gal", "5 Gal"],
        "aliases": ["roof cement", "roof patch", "tar"],
        "unit": "GAL",
        "definition": "Asphalt-based repair cement for flashings and small leaks.",
    },
    {
        "canonical": "Roof Moss Killer",
        "suffixes": ["Spray", "Granular"],
        "aliases": ["moss killer", "roof algae treatment"],
        "unit": "BAG",
        "definition": "Zinc or copper treatment that stops moss and algae streaks.",
    },

    # ---- Siding -----------------------------------------------------------------
    {
        "canonical": "Vinyl Siding",
        "suffixes": ["Double 4 White", "Double 4 Ivory", "Double 4 Grey", "Double 4 Tan", "Double 5 White", "Double 5 Ivory", "Double 5 Grey", "Dutch Lap White", "Dutch Lap Ivory", "Dutch Lap Grey", "Dutch Lap Tan", "Beaded White", "Beaded Ivory", "Beaded Cream", "Traditional White", "Traditional Grey", "Traditional Tan", "Cedar Mill White", "Cedar Mill Grey", "Cedar Mill Cream"],
        "aliases": ["vinyl siding", "plastic siding"],
        "unit": "SQ",
        "definition": "Maintenance-free vinyl siding in lap profiles and factory colors.",
    },
    {
        "canonical": "HardiePlank Siding",
        "suffixes": ["5/16 Smooth Primed", "7/16 Smooth Primed", "7/16 Woodgrain Primed", "7/16 Cedar Mill Primed"],
        "aliases": ["hardieplank", "fiber cement siding", "hardie siding", "james hardie"],
        "unit": "SF",
        "definition": "James Hardie fiber-cement lap siding; rot-proof and termite-proof.",
        "phonetic": "HAR-dee-plank",
        "ipa": "/ˈhɑːrdiplæŋk/",
    },
    {
        "canonical": "HardieShingle Siding",
        "suffixes": ["Panel", "Single"],
        "aliases": ["hardieshingle", "fiber cement shingle"],
        "unit": "SF",
        "definition": "Fiber-cement shingle siding with a wood shake look.",
    },
    {
        "canonical": "LP SmartSide Siding",
        "suffixes": ["Lap", "Panel", "Trim"],
        "aliases": ["smartside", "lp siding", "engineered wood siding"],
        "unit": "SF",
        "definition": "LP engineered-wood lap and trim that resists moisture.",
    },
    {
        "canonical": "Cedar Shake Siding",
        "suffixes": ["Hand Split", "Taper Sawn"],
        "aliases": ["cedar shake siding", "shake siding"],
        "unit": "SQ",
        "definition": "Western red cedar shakes for exterior walls.",
    },
    {
        "canonical": "Cedar Bevel Siding",
        "suffixes": ["5/8 x 6", "5/8 x 8"],
        "aliases": ["cedar bevel", "clapboard", "lap siding"],
        "unit": "SF",
        "definition": "Tapered cedar clapboards nailed horizontally.",
    },
    {
        "canonical": "T1-11 Siding",
        "suffixes": ["4 x 8", "4 x 10"],
        "aliases": ["t1-11", "plywood siding", "t one eleven"],
        "unit": "SF",
        "definition": "Grooved plywood sheet siding for sheds, garages, and cabins.",
    },
    {
        "canonical": "Aluminum Siding",
        "suffixes": ["Smooth", "Insulated"],
        "aliases": ["aluminum siding"],
        "unit": "SQ",
        "definition": "Old-school metal lap siding; durable but dents easily.",
    },
    {
        "canonical": "Steel Siding",
        "suffixes": ["Smooth", "Wood Grain"],
        "aliases": ["steel siding"],
        "unit": "SQ",
        "definition": "Dent-resistant steel lap siding in a baked finish.",
    },
    {
        "canonical": "Log Siding",
        "suffixes": ["Half Log", "Full Log"],
        "aliases": ["log siding", "log cabin siding"],
        "unit": "LF",
        "definition": "Pre-milled log profile siding for a cabin look.",
    },
    {
        "canonical": "Stucco EIFS",
        "suffixes": ["Base Coat", "Finish Coat"],
        "aliases": ["stucco", "eifs", "synthetic stucco"],
        "unit": "SF",
        "definition": "Exterior insulation and finish system with a textured acrylic finish.",
    },
    {
        "canonical": "Vinyl Shake Siding",
        "suffixes": ["Shingle", "Scallop"],
        "aliases": ["vinyl shakes", "vinyl shingle siding"],
        "unit": "SQ",
        "definition": "Vinyl panels molded to look like wood shingles.",
    },
    {
        "canonical": "Siding J-Channel",
        "suffixes": ["Standard", "Deep"],
        "aliases": ["j channel", "j trim"],
        "unit": "LF",
        "definition": "Vinyl trim that caps siding edges at windows and corners.",
    },
    {
        "canonical": "Siding Corner Post",
        "suffixes": ["Standard", "Inside Corner"],
        "aliases": ["corner post", "siding corner"],
        "unit": "LF",
        "definition": "Trim that finishes outside and inside siding corners.",
    },
    {
        "canonical": "Siding Starter Strip",
        "suffixes": ["Standard", "Vinyl"],
        "aliases": ["starter strip", "siding starter"],
        "unit": "LF",
        "definition": "Nailing strip that locks the first siding course level.",
    },
    {
        "canonical": "Undersill Trim",
        "suffixes": ["Standard", "Utility"],
        "aliases": ["undersill", "siding undersill"],
        "unit": "LF",
        "definition": "Trim that finishes siding under windows and eaves.",
    },
    {
        "canonical": "Engineered Trim Board",
        "suffixes": ["Azek 1x4", "Kleer 1x6", "SmartSide Trim"],
        "aliases": ["pvc trim", "cellular trim", "azek"],
        "unit": "LF",
        "definition": "Cellular PVC and engineered trim for rot-proof exterior detail.",
        "phonetic": "AY-zek",
        "ipa": "/ˈeɪzɛk/",
    },
    {
        "canonical": "Siding Screws",
        "suffixes": ["2 in", "2-1/2 in"],
        "aliases": ["siding screw", "hardie screw"],
        "unit": "BOX",
        "definition": "Self-tapping trim screws for fiber cement and trim.",
    },
    {
        "canonical": "Siding Brake",
        "suffixes": ["24 in", "36 in"],
        "aliases": ["brake", "metal brake", "sheet brake"],
        "unit": "EA",
        "definition": "Bending tool that folds metal trim and flashing.",
    },
    {
        "canonical": "Tin Snips",
        "suffixes": ["Straight", "Left", "Right"],
        "aliases": ["tin snips", "aviation snips", "metal shears"],
        "unit": "EA",
        "definition": "Compound snips for cutting coil and flashing.",
    },

    # ---- Soffit, fascia & finishing -----------------------------------------------
    {
        "canonical": "Vented Soffit",
        "suffixes": ["White", "Ivory", "Grey", "Almond", "Brown"],
        "aliases": ["soffit vent", "vented soffit panel"],
        "unit": "SF",
        "definition": "Perforated soffit panel that feeds attic intake air.",
    },
    {
        "canonical": "Solid Soffit",
        "suffixes": ["White", "Ivory", "Grey", "Almond", "Brown"],
        "aliases": ["soffit panel", "eave soffit"],
        "unit": "SF",
        "definition": "Unperforated soffit panel for eaves without venting.",
    },
    {
        "canonical": "Fascia Board",
        "suffixes": ["1x4 White", "1x4 Ivory", "1x6 White", "1x6 Ivory", "1x6 Brown"],
        "aliases": ["fascia", "fascia trim", "roof fascia"],
        "unit": "LF",
        "definition": "Trim running along the roof edge that carries the gutters.",
    },
    {
        "canonical": "Roofing Nails",
        "suffixes": ["1-1/4 Coil", "1-1/2", "Cap 1 in", "Ring Shank"],
        "aliases": ["roofing nail", "shingle nails", "coil nails"],
        "unit": "BOX",
        "definition": "Wide-head galvanized nails that hold shingles in the nailing zone.",
    },
    {
        "canonical": "Roofing Nailer",
        "suffixes": ["Coil", "Stick"],
        "aliases": ["roofing nailer", "coil nailer"],
        "unit": "EA",
        "definition": "Pneumatic nailer for high-volume shingle nailing.",
    },
    {
        "canonical": "Roofing Shovel",
        "suffixes": ["Standard", "Square Point"],
        "aliases": ["tear off shovel", "roof shovel", "spud bar"],
        "unit": "EA",
        "definition": "Flat blade that strips old shingles and staples.",
    },
    {
        "canonical": "Roofing Hatchet",
        "suffixes": ["Standard", "With Hammer"],
        "aliases": ["roofing hatchet", "shingle hatchet"],
        "unit": "EA",
        "definition": "Hammer-hatchet used to cut and nail shingles.",
    },
    {
        "canonical": "Roofing Square",
        "suffixes": ["Standard"],
        "aliases": ["roofing square", "shingle square"],
        "unit": "EA",
        "definition": "Chalk-guideline tool for square shingle courses.",
    },
    {
        "canonical": "Shingle Cutter",
        "suffixes": ["Shear", "Guillotine"],
        "aliases": ["shingle cutter", "cut-off tool"],
        "unit": "EA",
        "definition": "Tool that trims shingles at rakes and valleys.",
    },
    {
        "canonical": "Roof Ladder Hook",
        "suffixes": ["Standard", "Adjustable"],
        "aliases": ["ladder hook", "roof hook", "ridge hook"],
        "unit": "EA",
        "definition": "Hook that anchors a ladder over the ridge for roof access.",
    },
    {
        "canonical": "Roof Anchor",
        "suffixes": ["Permanent", "Temporary"],
        "aliases": ["roof anchor", "safety anchor", "fall protection"],
        "unit": "EA",
        "definition": "OSHA-rated anchor point for a roofing safety line.",
    },
    {
        "canonical": "Magnetic Nail Sweeper",
        "suffixes": ["24 in", "36 in"],
        "aliases": ["nail sweeper", "magnet sweeper"],
        "unit": "EA",
        "definition": "Rolling magnet that cleans nails off driveways and yards.",
    },
    {
        "canonical": "Roof Wash",
        "suffixes": ["Spray", "Concentrate"],
        "aliases": ["roof cleaner", "roof wash"],
        "unit": "GAL",
        "definition": "Soft-wash solution that removes algae and black streaks.",
    },
    {
        "canonical": "Skylight",
        "suffixes": ["Fixed 22 x 46", "Venting 22 x 46", "Tube 10 in"],
        "aliases": ["skylight", "roof window", "sun tunnel"],
        "unit": "EA",
        "definition": "Fixed or venting skylight with a flashing curb.",
    },
    {
        "canonical": "Skylight Flashing",
        "suffixes": ["Flat Roof", "Steep Slope"],
        "aliases": ["skylight flashing", "skylight curb"],
        "unit": "EA",
        "definition": "Pre-formed flashing kit for a skylight installation.",
    },
    {
        "canonical": "Snow Guard",
        "suffixes": ["Round", "Bar"],
        "aliases": ["snow guard", "snow stop"],
        "unit": "EA",
        "definition": "Cleat that holds snow on the roof above entries and gutters.",
    },
    {
        "canonical": "Rain Diverter",
        "suffixes": ["Over Door", "Standard"],
        "aliases": ["rain diverter", "gutter diverter"],
        "unit": "EA",
        "definition": "Splash guard that diverts rain over a doorway.",
    },
    {
        "canonical": "Weather Seal Tape",
        "suffixes": ["2 in", "4 in"],
        "aliases": ["weather seal", "butyl tape"],
        "unit": "ROLL",
        "definition": "Flashing tape for seams, pipe boots, and penetrations.",
    },
    {
        "canonical": "Gutter Splice",
        "suffixes": ["5 in", "6 in"],
        "aliases": ["gutter splice", "gutter connector"],
        "unit": "EA",
        "definition": "Joiner with sealant groove that connects gutter sections.",
    },
    {
        "canonical": "Gutter End Cap",
        "suffixes": ["Left", "Right"],
        "aliases": ["end cap", "gutter cap"],
        "unit": "EA",
        "definition": "Pre-formed cap that closes a gutter run end.",
    },
    {
        "canonical": "Gutter Drop Outlet",
        "suffixes": ["5 in", "6 in"],
        "aliases": ["drop outlet", "downspout outlet"],
        "unit": "EA",
        "definition": "Flanged opening that transitions the gutter to the downspout.",
    },
    {
        "canonical": "Downspout Band",
        "suffixes": ["Standard", "Adjustable"],
        "aliases": ["downspout strap", "pipe band"],
        "unit": "EA",
        "definition": "Metal band that mounts the downspout to the wall.",
    },
    {
        "canonical": "Roof Panel Fasteners",
        "suffixes": ["Screws 1 in", "Lap Sealant"],
        "aliases": ["metal roof screws", "panel screws"],
        "unit": "BOX",
        "definition": "Neoprene-washered screws that fasten standing seam and corrugated panels.",
    },
    {
        "canonical": "Metal Roof Sealant",
        "suffixes": ["Butyl", "Silicone"],
        "aliases": ["roof sealant", "panel sealant"],
        "unit": "TUBE",
        "definition": "Sealant for metal roof laps and fasteners.",
    },
    {
        "canonical": "Gutter Heating Cable",
        "suffixes": ["30 ft", "100 ft"],
        "aliases": ["gutter heat cable", "roof ice cable", "heat tape"],
        "unit": "EA",
        "definition": "Self-regulating cable in gutters and eaves that melts ice.",
    },
    {
        "canonical": "Power Attic Vent",
        "suffixes": ["1500 CFM", "3000 CFM"],
        "aliases": ["power attic fan", "attic ventilator", "exhaust fan roof"],
        "unit": "EA",
        "definition": "Thermostat-controlled fan that vents the attic in summer.",
    },
    {
        "canonical": "Solar Attic Fan",
        "suffixes": ["10 Watt", "20 Watt"],
        "aliases": ["solar fan", "solar attic ventilator"],
        "unit": "EA",
        "definition": "Solar-powered attic vent that needs no wiring.",
    },
    {
        "canonical": "Atlas Shingles",
        "suffixes": ["Pinnacle Pristine", "StormMaster Slate"],
        "aliases": ["atlas shingles"],
        "unit": "SQ",
        "definition": "Atlas architectural and storm-rated shingles.",
        "phonetic": "AT-las",
        "ipa": "/ˈætləs/",
    },
    {
        "canonical": "IKO Shingles",
        "suffixes": ["Cambridge Charcoal", "Nordic Weathered Wood"],
        "aliases": ["iko shingles"],
        "unit": "SQ",
        "definition": "IKO Cambridge architectural shingles.",
        "phonetic": "EYE-koh",
        "ipa": "/ˈaɪkoʊ/",
    },
    {
        "canonical": "Malarkey Shingles",
        "suffixes": ["Legacy", "Vista"],
        "aliases": ["malarkey shingles"],
        "unit": "SQ",
        "definition": "Malarkey asphalt shingles with polymer-modified rubber.",
        "phonetic": "MAL-ar-kee",
        "ipa": "/ˈmælɑːrki/",
    },
    {
        "canonical": "Copper Gutter",
        "suffixes": ["K-Style 5 in", "Half Round 5 in"],
        "aliases": ["copper gutters"],
        "unit": "LF",
        "definition": "Copper gutter that patinas to a classic green.",
    },
    {
        "canonical": "Copper Downspout",
        "suffixes": ["2x3", "3x4"],
        "aliases": ["copper downspout"],
        "unit": "LF",
        "definition": "Copper leader matching a copper gutter system.",
    },
    {
        "canonical": "Ice Dam Removal",
        "suffixes": ["Steam", "Chemical"],
        "aliases": ["ice dam", "ice melt"],
        "unit": "EA",
        "definition": "Method or agent that clears ice dams without damaging shingles.",
    },
    {
        "canonical": "Class 4 Impact Shingles",
        "suffixes": ["GAF Timberline ArmorShield", "OC Duration Flex"],
        "aliases": ["impact resistant", "class 4", "hail resistant"],
        "unit": "SQ",
        "definition": "Hail-rated shingles that earn insurance discounts.",
    },
    {
        "canonical": "Low-Slope Modified Shingles",
        "suffixes": ["Modified Bitumen", "SBS Cap Sheet"],
        "aliases": ["low slope", "flat roof shingles"],
        "unit": "SQ",
        "definition": "Rolled modified-bitumen roofing for nearly flat roofs.",
    },
    {
        "canonical": "Ridge Closure",
        "suffixes": ["Foam", "Pre-Cut Metal"],
        "aliases": ["ridge closure", "ridge seal"],
        "unit": "LF",
        "definition": "Closure strip that seals the corrugation crowns at the ridge.",
    },
    {
        "canonical": "Roof Edge Trim",
        "suffixes": ["Gable", "Eave"],
        "aliases": ["roof edge", "edge trim", "rake trim"],
        "unit": "LF",
        "definition": "Pre-finished metal that wraps rakes and eaves on metal roofs.",
    },
    {
        "canonical": "Eave Protector",
        "suffixes": ["Gutter Screens", "Eave Foam"],
        "aliases": ["eave protector", "bird block"],
        "unit": "LF",
        "definition": "Blocking that keeps birds and debris out of the eave cavity.",
    },
    {
        "canonical": "Hardie Trim Boards",
        "suffixes": ["1x4", "1x6"],
        "aliases": ["hardie trim", "fiber cement trim", "hardietrim"],
        "unit": "LF",
        "definition": "Fiber-cement trim boards matching HardiePlank siding.",
    },
    {
        "canonical": "Hardie Soffit Panel",
        "suffixes": ["Vented", "Solid"],
        "aliases": ["hardie soffit", "fiber cement soffit"],
        "unit": "SF",
        "definition": "Fiber-cement soffit panels for a maintenance-free eave.",
    },
    {
        "canonical": "Siding Color Match Caulk",
        "suffixes": ["White", "Grey", "Tan", "Brown"],
        "aliases": ["siding caulk", "color match caulk"],
        "unit": "TUBE",
        "definition": "Caulk tinted to match siding colors for invisible seams.",
    },
    {
        "canonical": "Siding Removal Tool",
        "suffixes": ["Zip Tool", "Hook"],
        "aliases": ["siding tool", "zip tool"],
        "unit": "EA",
        "definition": "Tool that unlocks and removes individual siding courses.",
    },
    {
        "canonical": "Fiber Cement Saw Blade",
        "suffixes": ["7-1/4 in", "10 in"],
        "aliases": ["hardie blade", "fiber cement blade", "diamond blade"],
        "unit": "EA",
        "definition": "Carbide-tipped blade that cuts fiber cement without chipping.",
    },
    {
        "canonical": "Siding Nails",
        "suffixes": ["2 in Galvanized", "Stainless 2 in"],
        "aliases": ["siding nail", "lap nail"],
        "unit": "BOX",
        "definition": "Ring-shank nails for nailing fiber cement and wood siding.",
    },
    {
        "canonical": "Brick Veneer Siding",
        "suffixes": ["Thin Brick", "Brick Panel"],
        "aliases": ["brick veneer", "thin brick"],
        "unit": "SF",
        "definition": "Lightweight brick veneer for accent walls and wainscots.",
    },
    {
        "canonical": "Stone Veneer Siding",
        "suffixes": ["Ledger Panel", "Cut Stone"],
        "aliases": ["stone veneer", "faux stone", "cultured stone"],
        "unit": "SF",
        "definition": "Manufactured stone veneer panels for exteriors and fireplaces.",
    },
    {
        "canonical": "Dormer Vent",
        "suffixes": ["10 x 8", "12 x 10"],
        "aliases": ["dormer vent", "attic vent dormer"],
        "unit": "EA",
        "definition": "Louvered vent that finishes a dormer and vents the attic.",
    },
    {
        "canonical": "Vent Screen",
        "suffixes": ["6 x 6", "8 x 8"],
        "aliases": ["vent screen", "bug screen"],
        "unit": "EA",
        "definition": "Mesh screen behind intake vents that keeps insects out.",
    },
    {
        "canonical": "Roof Boot Adapter",
        "suffixes": ["Straight", "Offset"],
        "aliases": ["roof boot", "vent adapter"],
        "unit": "EA",
        "definition": "Adapter that seals odd-angle vent pipes through the roof.",
    },
    {
        "canonical": "Underlayment Staples",
        "suffixes": ["7/16 in", "1/2 in"],
        "aliases": ["felt staples", "cap staples"],
        "unit": "BOX",
        "definition": "Galvanized staples that fasten underlayment to the deck.",
    },
    {
        "canonical": "Roofing Cap Nails",
        "suffixes": ["7/8 in", "1 in"],
        "aliases": ["cap nails", "button cap nails"],
        "unit": "BOX",
        "definition": "Plastic-cap nails used with a cap nailer on underlayment.",
    },
    {
        "canonical": "Window Sill Pan",
        "suffixes": ["Copper", "Aluminum"],
        "aliases": ["sill pan", "window pan"],
        "unit": "EA",
        "definition": "Pre-formed pan that drains water out from under a window.",
    },
    {
        "canonical": "Door Pan Flashing",
        "suffixes": ["6 in", "9 in"],
        "aliases": ["door flashing", "pan flashing"],
        "unit": "LF",
        "definition": "Flashing that seals the sill under an exterior door.",
    },
    {
        "canonical": "Caulking Backer Rod",
        "suffixes": ["1/2 in", "3/4 in"],
        "aliases": ["backer rod", "backer rope"],
        "unit": "LF",
        "definition": "Foam rod that backs joint sealant and controls depth.",
    },
    {
        "canonical": "Roof Rake Edge",
        "suffixes": ["2 x 2", "2 x 3"],
        "aliases": ["rake edge", "rake trim"],
        "unit": "LF",
        "definition": "Metal edge trim along the rake of a gable roof.",
    },
    {
        "canonical": "Gutter Machine",
        "suffixes": ["Portable", "On-Site"],
        "aliases": ["gutter forming machine", "gutter machine"],
        "unit": "EA",
        "definition": "Roll former that extrudes seamless gutter on site.",
    },
    {
        "canonical": "Standing Seam Accessories",
        "suffixes": ["Clips", "Flashing Kits"],
        "aliases": ["standing seam clip", "panel clip"],
        "unit": "EA",
        "definition": "Sliding clips and flashings for standing seam roofs.",
    },
    {
        "canonical": "Roofing Felt Applicator",
        "suffixes": ["Roller", "Cap Nailer"],
        "aliases": ["felt roller", "underlayment tool"],
        "unit": "EA",
        "definition": "Tool that rolls and fastens underlayment quickly.",
    },
    {
        "canonical": "Shingle Magnet",
        "suffixes": ["Sweeper", "Rake"],
        "aliases": ["shingle magnet", "roof magnet"],
        "unit": "EA",
        "definition": "Strong magnet that picks up shingle nails from the lawn.",
    },
    {
        "canonical": "Roofing Pneumatic Stapler",
        "suffixes": ["Standard", "Cap Stapler"],
        "aliases": ["roof stapler", "cap stapler"],
        "unit": "EA",
        "definition": "Air stapler for underlayment and cap-nail applications.",
    },
    {
        "canonical": "Siding Level",
        "suffixes": ["4 ft", "6 ft"],
        "aliases": ["level", "line level"],
        "unit": "EA",
        "definition": "Long level that keeps siding courses straight.",
    },
    {
        "canonical": "Gutter Cleaning Tool",
        "suffixes": ["Scoop", "Brush"],
        "aliases": ["gutter scoop", "gutter brush"],
        "unit": "EA",
        "definition": "Hand tool that clears leaves from gutters.",
    },
    {
        "canonical": "Shingle Bundles",
        "suffixes": ["Bundle 20 sq ft", "Bundle Starter"],
        "aliases": ["shingle bundle", "bundle of shingles"],
        "unit": "EA",
        "definition": "Single bundle; three bundles cover a square of roof.",
    },
    {
        "canonical": "Roofing Sealant Caulk",
        "suffixes": ["10 oz", "28 oz"],
        "aliases": ["roof caulk", "roof sealant"],
        "unit": "TUBE",
        "definition": "All-weather sealant for flashing and vent boot edges.",
    },
    {
        "canonical": "Attic Insulation Rake",
        "suffixes": ["Standard", "Extension"],
        "aliases": ["insulation rake", "attic rake"],
        "unit": "EA",
        "definition": "Rake that levels blown insulation across the attic floor.",
    },
]

