"""Tiling trade lexicon families: tile types/sizes, thinset, grout, backer,
waterproofing, Schluter profiles, tools, and the brands the voice
recognizer needs (Schluter, Laticrete, Mapei, Custom...).

TRADE matches the app's legacy "tiling" category."""

TRADE = "tiling"

FAMILIES = [
    # ---- Tile types ---------------------------------------------------------------
    {
        "canonical": "Ceramic Floor Tile",
        "suffixes": ["4 x 4", "6 x 6", "8 x 8", "12 x 12", "12 x 24", "18 x 18"],
        "aliases": ["ceramic tile", "floor tile", "ceramic floor tile"],
        "unit": "SF",
        "definition": "Glazed ceramic tile for floors.",
    },
    {
        "canonical": "Ceramic Wall Tile",
        "suffixes": ["4 x 4", "6 x 6", "8 x 8", "4 x 12", "12 x 24"],
        "aliases": ["wall tile", "ceramic wall tile"],
        "unit": "SF",
        "definition": "Glazed ceramic tile for walls and backsplashes.",
    },
    {
        "canonical": "Porcelain Floor Tile",
        "suffixes": ["12 x 12", "12 x 24", "18 x 18", "24 x 24", "32 x 64"],
        "aliases": ["porcelain tile", "porcelain floor"],
        "unit": "SF",
        "definition": "Dense low-absorption porcelain for floors.",
    },
    {
        "canonical": "Porcelain Plank Tile",
        "suffixes": ["6 x 36", "6 x 48", "8 x 48"],
        "aliases": ["plank tile", "porcelain plank", "wood look plank"],
        "unit": "SF",
        "definition": "Long narrow porcelain plank that mimics hardwood.",
    },
    {
        "canonical": "Porcelain Wood-Look Tile",
        "suffixes": ["Oak", "Hickory", "Walnut", "Gray Oak"],
        "aliases": ["wood look tile", "wood tile"],
        "unit": "SF",
        "definition": "Porcelain tile printed to look like wood grain.",
    },
    {
        "canonical": "Porcelain Marble-Look Tile",
        "suffixes": ["Carrara", "Calacatta", "Crema"],
        "aliases": ["marble look tile"],
        "unit": "SF",
        "definition": "Porcelain that mimics marble veining.",
    },
    {
        "canonical": "Porcelain Concrete-Look Tile",
        "suffixes": ["Gray", "White"],
        "aliases": ["concrete look tile"],
        "unit": "SF",
        "definition": "Porcelain with a polished concrete finish.",
    },
    {
        "canonical": "Marble Tile",
        "suffixes": ["Carrara 12 x 12", "Carrara 12 x 24", "Calacatta 12 x 24", "White 6 x 6"],
        "aliases": ["marble tile", "carrara marble"],
        "unit": "SF",
        "definition": "Natural marble for floors, walls, and showers.",
    },
    {
        "canonical": "Marble Mosaic",
        "suffixes": ["Hexagon", "Herringbone", "Penny"],
        "aliases": ["marble mosaic", "mosaic sheet"],
        "unit": "SF",
        "definition": "Marble tiles pre-mounted on mesh sheets.",
    },
    {
        "canonical": "Travertine Tile",
        "suffixes": ["4 x 4", "6 x 6", "12 x 12", "18 x 18"],
        "aliases": ["travertine", "travertine tile"],
        "unit": "SF",
        "definition": "Natural travertine with a tumbled or honed face.",
    },
    {
        "canonical": "Travertine Filled and Honed",
        "suffixes": ["12 x 12", "18 x 18"],
        "aliases": ["filled travertine", "honed travertine"],
        "unit": "SF",
        "definition": "Travertine with filled pores and a smooth honed finish.",
    },
    {
        "canonical": "Slate Tile",
        "suffixes": ["12 x 12", "12 x 24", "18 x 18"],
        "aliases": ["slate tile", "slate"],
        "unit": "SF",
        "definition": "Natural cleft slate for floors and patios.",
    },
    {
        "canonical": "Limestone Tile",
        "suffixes": ["6 x 6", "12 x 12", "12 x 24"],
        "aliases": ["limestone tile"],
        "unit": "SF",
        "definition": "Soft neutral natural stone tile.",
    },
    {
        "canonical": "Granite Tile",
        "suffixes": ["12 x 12", "12 x 24"],
        "aliases": ["granite tile"],
        "unit": "SF",
        "definition": "Polished granite tiles for floors and counters.",
    },
    {
        "canonical": "Quartzite Tile",
        "suffixes": ["12 x 24", "24 x 24"],
        "aliases": ["quartzite tile"],
        "unit": "SF",
        "definition": "Hard natural quartzite for heavy-traffic floors.",
    },
    {
        "canonical": "Subway Tile",
        "suffixes": ["2 x 6", "3 x 6", "3 x 12", "4 x 12", "4 x 16"],
        "aliases": ["subway tile", "brick tile"],
        "unit": "SF",
        "definition": "Rectangular tile laid in a running bond.",
    },
    {
        "canonical": "Subway Tile Colors",
        "suffixes": ["White", "Black", "Gray", "Blue", "Green"],
        "aliases": ["subway colors", "colored subway tile"],
        "unit": "SF",
        "definition": "Color options for subway tile.",
    },
    {
        "canonical": "Hexagon Tile",
        "suffixes": ["1 in", "2 in", "4 in"],
        "aliases": ["hexagon tile", "hex tile"],
        "unit": "SF",
        "definition": "Hexagonal tile on mesh sheets.",
    },
    {
        "canonical": "Penny Tile",
        "suffixes": ["White", "Black", "Silver"],
        "aliases": ["penny round", "penny tile"],
        "unit": "SF",
        "definition": "Small round tiles on mesh sheets.",
    },
    {
        "canonical": "Glass Mosaic Tile",
        "suffixes": ["1 x 1", "2 x 2", "Subway"],
        "aliases": ["glass mosaic", "glass tile"],
        "unit": "SF",
        "definition": "Translucent glass tiles on mesh sheets.",
    },
    {
        "canonical": "Glass Subway Tile",
        "suffixes": ["3 x 6", "4 x 12"],
        "aliases": ["glass subway", "glass brick tile"],
        "unit": "SF",
        "definition": "Glass tiles in the subway profile.",
    },
    {
        "canonical": "Brick Pattern Tile",
        "suffixes": ["3 x 12", "4 x 12"],
        "aliases": ["brick pattern", "stack bond tile"],
        "unit": "SF",
        "definition": "Tile sized for a brick-layout pattern.",
    },
    {
        "canonical": "Checkered Floor Tile",
        "suffixes": ["2 x 2 Black/White", "4 x 4 Black/White"],
        "aliases": ["checkerboard tile", "checkered tile"],
        "unit": "SF",
        "definition": "Classic black and white checkerboard.",
    },
    {
        "canonical": "Large Format Tile",
        "suffixes": ["24 x 48", "32 x 64"],
        "aliases": ["large format", "slab tile", "big tile"],
        "unit": "SF",
        "definition": "Extra-large tiles that need a leveling system.",
    },
    {
        "canonical": "Tile Bullnose",
        "suffixes": ["4 in", "6 in", "12 in"],
        "aliases": ["bullnose", "tile bullnose"],
        "unit": "EA",
        "definition": "Rounded-edge tile that finishes exposed edges.",
    },
    {
        "canonical": "Quarter Round Tile",
        "suffixes": ["1/2 in", "3/4 in"],
        "aliases": ["quarter round", "tile base"],
        "unit": "EA",
        "definition": "Curved tile trim used at the floor-to-wall joint.",
    },

    # ---- Thinset & adhesives --------------------------------------------------------
    {
        "canonical": "Modified Thinset",
        "suffixes": ["25 lb", "50 lb", "75 lb"],
        "aliases": ["thinset", "thin set", "modified thinset mortar"],
        "unit": "BAG",
        "definition": "Polymer-modified thinset mortar for most tile installations.",
    },
    {
        "canonical": "Unmodified Thinset",
        "suffixes": ["25 lb", "50 lb"],
        "aliases": ["unmodified thinset", "dry set mortar"],
        "unit": "BAG",
        "definition": "Plain thinset used under membranes and waterproofing.",
    },
    {
        "canonical": "Large Format Thinset",
        "suffixes": ["25 lb", "50 lb"],
        "aliases": ["large format thinset", "lft mortar"],
        "unit": "BAG",
        "definition": "High-bond thinset for tiles over 15 inches.",
    },
    {
        "canonical": "Rapid Setting Thinset",
        "suffixes": ["25 lb", "50 lb"],
        "aliases": ["rapid set", "fast set thinset"],
        "unit": "BAG",
        "definition": "Fast-curing thinset that allows grout the same day.",
    },
    {
        "canonical": "Self-Leveling Underlayment",
        "suffixes": ["50 lb", "80 lb"],
        "aliases": ["self leveler", "self leveling concrete", "floor leveler"],
        "unit": "BAG",
        "definition": "Flowable topping that flattens floors before tiling.",
    },
    {
        "canonical": "Mastic Tile Adhesive",
        "suffixes": ["1 Gallon", "3.5 Gallon"],
        "aliases": ["tile mastic", "premixed adhesive", "tile adhesive"],
        "unit": "GAL",
        "definition": "Ready-to-use adhesive for wall tile and backsplashes.",
    },
    {
        "canonical": "Laticrete 4-XLT",
        "suffixes": ["50 lb"],
        "aliases": ["4-xlt", "laticrete thinset"],
        "unit": "BAG",
        "definition": "Premium large-format thinset from Laticrete.",
        "phonetic": "LAT-ih-kreet",
        "ipa": "/ˈlætɪkriːt/",
    },
    {
        "canonical": "Mapei Kerabond",
        "suffixes": ["50 lb"],
        "aliases": ["kerabond", "mapei thinset"],
        "unit": "BAG",
        "definition": "Unmodified thinset from Mapei.",
        "phonetic": "mah-PAY",
        "ipa": "/mɑːˈpeɪ/",
    },
    {
        "canonical": "Custom MegaLite",
        "suffixes": ["50 lb"],
        "aliases": ["megalite", "custom building products"],
        "unit": "BAG",
        "definition": "Lightweight large-format thinset from Custom.",
    },
    {
        "canonical": "Ardex X77",
        "suffixes": ["50 lb"],
        "aliases": ["ardex", "x77 thinset"],
        "unit": "BAG",
        "definition": "High-performance thinset from Ardex.",
        "phonetic": "AR-dex",
        "ipa": "/ˈɑːrdɛks/",
    },
    {
        "canonical": "Crack Isolation Membrane",
        "suffixes": ["1 Gallon", "3.5 Gallon"],
        "aliases": ["crack isolation", "anti fracture membrane"],
        "unit": "GAL",
        "definition": "Roll-on membrane that stops cracks transferring to tile.",
    },
    {
        "canonical": "Tile Leveling System",
        "suffixes": ["Starter Kit", "Refill Clips", "Reusable Wedges"],
        "aliases": ["tile leveling", "levelling clips", "raimondi system"],
        "unit": "EA",
        "definition": "Clips and wedges that keep large tile flush.",
    },
    {
        "canonical": "Tile Leveling Wedges",
        "suffixes": ["Pack of 100", "Pack of 250"],
        "aliases": ["leveling wedges", "tile wedges"],
        "unit": "PK",
        "definition": "Plastic wedges driven into leveling clips.",
    },

    # ---- Grout ----------------------------------------------------------------------
    {
        "canonical": "Sanded Grout",
        "suffixes": ["10 lb", "25 lb", "50 lb"],
        "aliases": ["sanded grout", "cement grout"],
        "unit": "BAG",
        "definition": "Grout with sand for joints over 1/8 inch.",
    },
    {
        "canonical": "Unsanded Grout",
        "suffixes": ["10 lb", "25 lb"],
        "aliases": ["unsanded grout"],
        "unit": "BAG",
        "definition": "Smooth grout for tight joints under 1/8 inch.",
    },
    {
        "canonical": "Epoxy Grout",
        "suffixes": ["Small Unit", "Medium Unit", "Full Unit"],
        "aliases": ["epoxy grout", "spectralock"],
        "unit": "UNIT",
        "definition": "Stain-proof resin grout for countertops and showers.",
    },
    {
        "canonical": "Urethane Grout",
        "suffixes": ["Small Unit", "Medium Unit"],
        "aliases": ["urethane grout"],
        "unit": "UNIT",
        "definition": "Flexible single-component grout.",
    },
    {
        "canonical": "Grout Colors",
        "suffixes": ["White", "Bone", "Gray", "Charcoal", "Taupe"],
        "aliases": ["grout color", "colored grout"],
        "unit": "BAG",
        "definition": "Popular grout color choices.",
    },
    {
        "canonical": "Laticrete Permacolor",
        "suffixes": ["10 lb", "25 lb"],
        "aliases": ["permacolor", "laticrete grout"],
        "unit": "BAG",
        "definition": "High-performance grout from Laticrete.",
    },
    {
        "canonical": "Mapei Ultracolor Plus",
        "suffixes": ["10 lb", "25 lb"],
        "aliases": ["ultracolor", "mapei grout"],
        "unit": "BAG",
        "definition": "Premium fast-setting grout from Mapei.",
    },
    {
        "canonical": "Custom Polyblend Grout",
        "suffixes": ["10 lb", "25 lb"],
        "aliases": ["polyblend", "custom grout"],
        "unit": "BAG",
        "definition": "Sanded cement grout from Custom Building Products.",
    },
    {
        "canonical": "Grout Additive",
        "suffixes": ["1 Quart", "1 Gallon"],
        "aliases": ["grout additive", "acrylic admix"],
        "unit": "QT",
        "definition": "Liquid additive that strengthens grout.",
    },
    {
        "canonical": "Grout Sealer",
        "suffixes": ["1 Quart", "1 Gallon"],
        "aliases": ["grout sealer", "grout protectant"],
        "unit": "QT",
        "definition": "Sealer that keeps grout clean and stain-free.",
    },
    {
        "canonical": "Grout Enhancer",
        "suffixes": ["1 Quart", "1 Gallon"],
        "aliases": ["grout enhancer", "color enhancer"],
        "unit": "QT",
        "definition": "Enhancer that deepens grout color.",
    },
    {
        "canonical": "Grout Release",
        "suffixes": ["1 Quart"],
        "aliases": ["grout release", "grout shield"],
        "unit": "QT",
        "definition": "Protectant applied before grouting textured tile.",
    },
    {
        "canonical": "Epoxy Grout Colors",
        "suffixes": ["White", "Gray", "Charcoal"],
        "aliases": ["epoxy color"],
        "unit": "UNIT",
        "definition": "Color options for epoxy grout.",
    },

    # ---- Backer & underlayment ------------------------------------------------------
    {
        "canonical": "Cement Backer Board",
        "suffixes": ["1/2 in", "5/8 in"],
        "aliases": ["cement board", "backer board", "durock"],
        "unit": "SF",
        "definition": "Cementitious tile substrate for wet areas.",
    },
    {
        "canonical": "HardieBacker Board",
        "suffixes": ["1/4 in", "1/2 in", "5/8 in"],
        "aliases": ["hardiebacker", "hardie backer"],
        "unit": "SF",
        "definition": "James Hardie cement board.",
        "phonetic": "HAR-dee BAK-er",
        "ipa": "/ˈhɑːrdi ˈbækər/",
    },
    {
        "canonical": "Ditra Uncoupling Membrane",
        "suffixes": ["54 sq ft", "108 sq ft"],
        "aliases": ["ditra", "uncoupling membrane", "schulter ditra"],
        "unit": "ROLL",
        "definition": "Schluter uncoupling mat that lets tile and substrate move separately.",
        "phonetic": "DEE-truh",
        "ipa": "/ˈdiːtrə/",
    },
    {
        "canonical": "Ditra Heat Mat",
        "suffixes": ["30 sq ft", "120 sq ft"],
        "aliases": ["ditra heat", "heated tile mat"],
        "unit": "ROLL",
        "definition": "Ditra with embedded heating cable for warm tile floors.",
    },
    {
        "canonical": "Ditra XL",
        "suffixes": ["54 sq ft", "108 sq ft"],
        "aliases": ["ditra xl"],
        "unit": "ROLL",
        "definition": "Thicker Ditra for larger tile.",
    },
    {
        "canonical": "Kerdi Waterproof Membrane",
        "suffixes": ["108 sq ft", "323 sq ft"],
        "aliases": ["kerdi", "shower membrane", "waterproof membrane"],
        "unit": "ROLL",
        "definition": "Schluter sheet membrane that waterproofs showers.",
        "phonetic": "KER-dee",
        "ipa": "/ˈkɜːrdiː/",
    },
    {
        "canonical": "Kerdi Board",
        "suffixes": ["1/2 in", "5/8 in"],
        "aliases": ["kerdi board", "kerdi foam board"],
        "unit": "SF",
        "definition": "Waterproof foam board for shower walls.",
    },
    {
        "canonical": "Wedi Board",
        "suffixes": ["1/2 in", "5/8 in"],
        "aliases": ["wedi board", "wedi"],
        "unit": "SF",
        "definition": "Waterproof foam backer board.",
        "phonetic": "WAY-dee",
        "ipa": "/ˈweɪdiː/",
    },
    {
        "canonical": "GoBoard",
        "suffixes": ["1/2 in", "5/8 in"],
        "aliases": ["goboard", "fiberglass foam board"],
        "unit": "SF",
        "definition": "Waterproof fiberglass-faced foam backer.",
    },
    {
        "canonical": "Plywood Underlayment",
        "suffixes": ["1/4 in", "1/2 in"],
        "aliases": ["underlayment plywood", "tile underlayment"],
        "unit": "SF",
        "definition": "Smooth plywood base under tile and flooring.",
    },
    {
        "canonical": "Backer Board Screws",
        "suffixes": ["1-1/4 in", "1-5/8 in", "2 in"],
        "aliases": ["backer screws", "cement board screws"],
        "unit": "BOX",
        "definition": "Corrosion-resistant screws for cement board.",
    },
    {
        "canonical": "Thinset Trowel",
        "suffixes": ["1/4 x 3/16", "1/4 x 1/4", "3/8 x 3/8", "1/2 x 1/2", "3/4 x 3/4"],
        "aliases": ["notched trowel", "tile trowel"],
        "unit": "EA",
        "definition": "Notched trowel sized to the tile being set.",
    },
    {
        "canonical": "Margin Trowel",
        "suffixes": ["3 x 8", "4 x 10"],
        "aliases": ["margin trowel", "pointing trowel"],
        "unit": "EA",
        "definition": "Small trowel for buttering tile edges.",
    },

    # ---- Waterproofing ----------------------------------------------------------------
    {
        "canonical": "RedGard Waterproofing",
        "suffixes": ["1 Gallon", "3.5 Gallon"],
        "aliases": ["redgard", "red guard", "waterproofing membrane"],
        "unit": "GAL",
        "definition": "Roll-on liquid waterproof membrane from Custom.",
    },
    {
        "canonical": "Hydro Ban Waterproofing",
        "suffixes": ["1 Gallon", "3.5 Gallon"],
        "aliases": ["hydro ban", "laticrete waterproofing"],
        "unit": "GAL",
        "definition": "Laticrete liquid waterproofing membrane.",
        "phonetic": "HY-dro ban",
        "ipa": "/ˈhaɪdroʊ bæn/",
    },
    {
        "canonical": "Aqua Defense Waterproofing",
        "suffixes": ["1 Gallon", "3.5 Gallon"],
        "aliases": ["aqua defense", "mapei waterproofing"],
        "unit": "GAL",
        "definition": "Mapei liquid waterproofing membrane.",
    },
    {
        "canonical": "Kerdi-Fix Sealant",
        "suffixes": ["Tube"],
        "aliases": ["kerdi fix", "schluter sealant"],
        "unit": "TUBE",
        "definition": "Adhesive sealant for Kerdi connections.",
    },
    {
        "canonical": "Shower Pan Liner",
        "suffixes": ["PVC 40 Mil", "PVC 6 x 50"],
        "aliases": ["pan liner", "shower pan liner"],
        "unit": "LF",
        "definition": "PVC liner that waterproofs the shower floor pan.",
    },
    {
        "canonical": "Pre-Sloped Shower Tray",
        "suffixes": ["32 x 60", "38 x 60", "48 x 48"],
        "aliases": ["shower tray", "shower pan", "schluter tray"],
        "unit": "EA",
        "definition": "Pre-sloped foam pan for tile showers.",
    },
    {
        "canonical": "Shower Curb",
        "suffixes": ["Standard", "Extra Tall"],
        "aliases": ["shower curb", "curb"],
        "unit": "EA",
        "definition": "Pre-formed curb for a tile shower.",
    },
    {
        "canonical": "Linear Shower Drain",
        "suffixes": ["30 in", "42 in"],
        "aliases": ["linear drain", "trench drain"],
        "unit": "EA",
        "definition": "Long slim drain for curbless showers.",
    },
    {
        "canonical": "Tile Shower Seat",
        "suffixes": ["Square", "Corner"],
        "aliases": ["shower seat", "shower bench"],
        "unit": "EA",
        "definition": "Foam bench that gets tiled into the shower.",
    },
    {
        "canonical": "Floor Warming Cable",
        "suffixes": ["30 sq ft", "60 sq ft", "120 sq ft"],
        "aliases": ["floor heating cable", "radiant floor cable"],
        "unit": "EA",
        "definition": "Electric cable that warms tile floors.",
    },
    {
        "canonical": "Floor Heating Thermostat",
        "suffixes": ["Programmable", "Wi-Fi"],
        "aliases": ["floor thermostat", "heat thermostat"],
        "unit": "EA",
        "definition": "Thermostat that controls floor warming.",
    },
    {
        "canonical": "Floor Heating Sensor",
        "suffixes": ["Standard"],
        "aliases": ["floor sensor", "probe sensor"],
        "unit": "EA",
        "definition": "Temperature probe for floor heating control.",
    },

    # ---- Profiles & trim ---------------------------------------------------------------
    {
        "canonical": "Schluter Jolly Profile",
        "suffixes": ["3/8 in", "1/2 in"],
        "aliases": ["schluter jolly", "jolly"],
        "unit": "LF",
        "definition": "L-shaped edge trim that finishes tile edges.",
        "phonetic": "SHLOO-ter",
        "ipa": "/ˈʃluːtər/",
    },
    {
        "canonical": "Schluter Rondec Profile",
        "suffixes": ["3/8 in", "1/2 in"],
        "aliases": ["rondec", "schluter rondec"],
        "unit": "LF",
        "definition": "Round-edged tile profile.",
    },
    {
        "canonical": "Schluter Quadec Profile",
        "suffixes": ["3/8 in", "1/2 in"],
        "aliases": ["quadec", "schluter quadec"],
        "unit": "LF",
        "definition": "Square-edged tile profile.",
    },
    {
        "canonical": "Schluter Dilex Profile",
        "suffixes": ["1/2 in", "5/8 in"],
        "aliases": ["dilex", "expansion profile"],
        "unit": "LF",
        "definition": "Movement joint profile for tile transitions.",
    },
    {
        "canonical": "Schluter Schiene Profile",
        "suffixes": ["3/8 in", "1/2 in"],
        "aliases": ["schiene", "schluter schiene"],
        "unit": "LF",
        "definition": "Aluminum tile edge profile.",
        "phonetic": "SHEE-nuh",
        "ipa": "/ˈʃiːnə/",
    },
    {
        "canonical": "Tile Transition Strip",
        "suffixes": ["Marble", "Aluminum"],
        "aliases": ["transition strip", "tile transition"],
        "unit": "EA",
        "definition": "Strip that transitions tile to an adjacent floor.",
    },
    {
        "canonical": "Tile Threshold",
        "suffixes": ["Marble 3 ft", "Granite 3 ft", "Travertine 3 ft"],
        "aliases": ["threshold", "door threshold"],
        "unit": "EA",
        "definition": "Natural stone threshold at doorways.",
    },
    {
        "canonical": "Tile Reducer",
        "suffixes": ["Aluminum", "Marble"],
        "aliases": ["reducer", "tile reducer"],
        "unit": "EA",
        "definition": "Trim that transitions different floor heights.",
    },
    {
        "canonical": "Stair Nose Tile Trim",
        "suffixes": ["Aluminum", "Marble"],
        "aliases": ["stair nose", "stair tread trim"],
        "unit": "EA",
        "definition": "Profile that finishes the front of tiled stairs.",
    },
    {
        "canonical": "Caulking for Tile",
        "suffixes": ["Sanded", "Color Match"],
        "aliases": ["tile caulk", "sanded caulk", "siliconized caulk"],
        "unit": "TUBE",
        "definition": "Flexible caulk for tile plane changes.",
    },
    {
        "canonical": "Caulk Color Options",
        "suffixes": ["White", "Bone", "Gray", "Black"],
        "aliases": ["caulk color", "grout match caulk"],
        "unit": "TUBE",
        "definition": "Color-matched caulk to blend with grout.",
    },

    # ---- Tile tools -------------------------------------------------------------------
    {
        "canonical": "Tile Spacers",
        "suffixes": ["1/16 in", "1/8 in", "3/16 in", "1/4 in", "3/8 in"],
        "aliases": ["tile spacers", "spacers"],
        "unit": "PK",
        "definition": "Plastic crosses that set consistent grout lines.",
    },
    {
        "canonical": "Rubber Mallet",
        "suffixes": ["Small", "Large"],
        "aliases": ["rubber mallet", "dead blow hammer"],
        "unit": "EA",
        "definition": "Soft-faced hammer that beds tile without breaking it.",
    },
    {
        "canonical": "Grout Float",
        "suffixes": ["Standard", "Rubber"],
        "aliases": ["grout float", "grouting float"],
        "unit": "EA",
        "definition": "Rubber-faced float that pushes grout into joints.",
    },
    {
        "canonical": "Grout Sponge",
        "suffixes": ["Pack"],
        "aliases": ["grout sponge", "tile sponge"],
        "unit": "PK",
        "definition": "Sponge that wipes grout haze from tile.",
    },
    {
        "canonical": "Snap Tile Cutter",
        "suffixes": ["24 in", "36 in"],
        "aliases": ["tile cutter", "snap cutter", "score and snap"],
        "unit": "EA",
        "definition": "Manual cutter that scores and snaps tile.",
    },
    {
        "canonical": "Wet Tile Saw",
        "suffixes": ["7 in", "10 in"],
        "aliases": ["wet saw", "tile saw"],
        "unit": "EA",
        "definition": "Water-cooled saw for cutting tile.",
    },
    {
        "canonical": "Diamond Tile Blade",
        "suffixes": ["4 in", "7 in", "10 in"],
        "aliases": ["tile blade", "diamond blade"],
        "unit": "EA",
        "definition": "Diamond-rimmed blade for cutting tile.",
    },
    {
        "canonical": "Tile Nipper",
        "suffixes": ["Standard"],
        "aliases": ["tile nippers", "nibblers"],
        "unit": "EA",
        "definition": "Pincer tool that nibbles tile edges to shape.",
    },
    {
        "canonical": "Tile Scribe",
        "suffixes": ["Standard"],
        "aliases": ["tile scribe", "tungsten scribe"],
        "unit": "EA",
        "definition": "Hand scribe for scoring thin tile.",
    },
    {
        "canonical": "Rub Stone",
        "suffixes": ["Coarse", "Fine"],
        "aliases": ["rub stone", "tile stone", "abrasive stone"],
        "unit": "EA",
        "definition": "Abrasive block that smooths cut tile edges.",
    },
    {
        "canonical": "Diamond Hole Saw",
        "suffixes": ["1/4 in", "1/2 in", "1 in"],
        "aliases": ["diamond bit", "tile hole saw"],
        "unit": "EA",
        "definition": "Diamond-coated bit that drills holes in tile.",
    },
    {
        "canonical": "Knee Pads",
        "suffixes": ["Standard", "Pro"],
        "aliases": ["knee pads"],
        "unit": "PAIR",
        "definition": "Padded knee protection for setting tile.",
    },
    {
        "canonical": "Tile Kneeling Board",
        "suffixes": ["Standard"],
        "aliases": ["kneeling board", "tile kneeler"],
        "unit": "EA",
        "definition": "Foam board that spreads weight across the floor.",
    },
    {
        "canonical": "Mixing Paddle",
        "suffixes": ["Thinset", "Grout"],
        "aliases": ["mixing paddle", "drill paddle"],
        "unit": "EA",
        "definition": "Paddle that mixes thinset and grout smoothly.",
    },
    {
        "canonical": "Tile Bucket",
        "suffixes": ["3 Gallon", "5 Gallon"],
        "aliases": ["tile bucket", "mixing bucket"],
        "unit": "EA",
        "definition": "Heavy bucket for mixing thinset.",
    },
    {
        "canonical": "Tile Saw Stand",
        "suffixes": ["Folding"],
        "aliases": ["saw stand", "tile saw table"],
        "unit": "EA",
        "definition": "Stand that supports a wet saw.",
    },
    {
        "canonical": "Angle Grinder",
        "suffixes": ["4-1/2 in", "7 in"],
        "aliases": ["angle grinder", "grinder"],
        "unit": "EA",
        "definition": "Grinder used to cut and polish tile.",
    },
    {
        "canonical": "Grout Bag",
        "suffixes": ["Standard", "Large"],
        "aliases": ["grout bag", "piping bag"],
        "unit": "EA",
        "definition": "Bag that pipes grout into fine joints.",
    },
    {
        "canonical": "Laser Level",
        "suffixes": ["Line", "Rotary"],
        "aliases": ["laser level"],
        "unit": "EA",
        "definition": "Level laser for layout lines.",
    },
    {
        "canonical": "Tile Wet Saw Blade",
        "suffixes": ["Continuous Rim", "Turbo"],
        "aliases": ["wet saw blade"],
        "unit": "EA",
        "definition": "Blade style for clean or fast tile cuts.",
    },
    {
        "canonical": "Dust Mask",
        "suffixes": ["N95"],
        "aliases": ["dust mask"],
        "unit": "BOX",
        "definition": "Respirator for cutting tile and mixing.",
    },
    {
        "canonical": "Safety Glasses",
        "suffixes": ["Clear"],
        "aliases": ["safety glasses"],
        "unit": "EA",
        "definition": "Eye protection for tile cutting.",
    },

    # ---- Sealer & maintenance -----------------------------------------------------------
    {
        "canonical": "Penetrating Sealer",
        "suffixes": ["1 Quart", "1 Gallon", "5 Gallon"],
        "aliases": ["tile sealer", "penetrating sealer", "stone sealer"],
        "unit": "GAL",
        "definition": "Impregnating sealer that protects tile and stone.",
    },
    {
        "canonical": "Enhancing Sealer",
        "suffixes": ["1 Quart", "1 Gallon"],
        "aliases": ["enhancing sealer", "wet look sealer"],
        "unit": "QT",
        "definition": "Sealer that deepens the color of natural stone.",
    },
    {
        "canonical": "Tile and Grout Cleaner",
        "suffixes": ["Spray", "Concentrate"],
        "aliases": ["tile cleaner", "grout cleaner"],
        "unit": "GAL",
        "definition": "Cleaner for tile and grout maintenance.",
    },
    {
        "canonical": "Grout Haze Remover",
        "suffixes": ["1 Quart", "1 Gallon"],
        "aliases": ["haze remover", "grout haze"],
        "unit": "QT",
        "definition": "Product that strips dried grout haze from tile.",
    },
    {
        "canonical": "Tile Adhesive Roller",
        "suffixes": ["Standard"],
        "aliases": ["adhesive roller"],
        "unit": "EA",
        "definition": "Roller that applies waterproofing and membranes.",
    },
    {
        "canonical": "Tile Corner Rounder",
        "suffixes": ["Standard"],
        "aliases": ["corner rounder"],
        "unit": "EA",
        "definition": "Bit that rounds sharp tile edges.",
    },
    {
        "canonical": "Laticrete Products",
        "suffixes": ["3701 Mortar Additive", "9235 Waterproofing", "Spray On Grout Release"],
        "aliases": ["laticrete", "laticrete products"],
        "unit": "EA",
        "definition": "Laticrete mortar and waterproofing products.",
    },
    {
        "canonical": "Mapei Products",
        "suffixes": ["Keracolor Grout", "Ultracolor Grout", "Mapelastic Self-Leveler"],
        "aliases": ["mapei", "mapei products"],
        "unit": "EA",
        "definition": "Mapei grouts, mortars, and levelers.",
    },
    {
        "canonical": "Custom Building Products",
        "suffixes": ["MegaLite Thinset", "RedGard", "Polyblend Grout"],
        "aliases": ["custom building", "custom products", "cob products"],
        "unit": "EA",
        "definition": "Custom Building Products mortars and membranes.",
    },
    {
        "canonical": "Schluter Systems",
        "suffixes": ["Kerdi", "Ditra", "Shower Tray"],
        "aliases": ["schluter", "schluter systems"],
        "unit": "EA",
        "definition": "Schluter membranes, mats, and profiles.",
    },
    {
        "canonical": "TEC Products",
        "suffixes": ["Full Flex Thinset", "AccuColor Grout"],
        "aliases": ["tec products", "tec thinset"],
        "unit": "EA",
        "definition": "TEC mortars and grouts.",
        "phonetic": "TEK",
        "ipa": "/tɛk/",
    },
    {
        "canonical": "Ardex Products",
        "suffixes": ["K301 Self-Leveler", "X77 Thinset"],
        "aliases": ["ardex products"],
        "unit": "EA",
        "definition": "Ardex levelers and adhesives.",
    },
    {
        "canonical": "Bostik Products",
        "suffixes": ["Spectralock Grout", "Hydroment Grout"],
        "aliases": ["bostik", "spectralock"],
        "unit": "EA",
        "definition": "Bostik epoxy and cement grouts.",
        "phonetic": "BOSS-tik",
        "ipa": "/ˈbɒstɪk/",
    },
    {
        "canonical": "Wedi System",
        "suffixes": ["Board", "Sealant", "Screws"],
        "aliases": ["wedi system"],
        "unit": "EA",
        "definition": "Wedi waterproof building boards.",
    },
    {
        "canonical": "Prova Leveling System",
        "suffixes": ["Starter Kit", "Clips"],
        "aliases": ["prova", "prova leveling"],
        "unit": "EA",
        "definition": "Reusable tile leveling system.",
        "phonetic": "PRO-vah",
        "ipa": "/ˈproʊvɑː/",
    },
    {
        "canonical": "Tile Edge Metal",
        "suffixes": ["Aluminum", "Brass", "Stainless"],
        "aliases": ["edge metal", "tile edging"],
        "unit": "LF",
        "definition": "Metal edging in multiple finishes.",
    },
    {
        "canonical": "Tile Mat",
        "suffixes": ["Anti-Fatigue"],
        "aliases": ["tile mat", "anti fatigue mat"],
        "unit": "EA",
        "definition": "Comfort mat for long days setting tile.",
    },
    {
        "canonical": "Grout Saw",
        "suffixes": ["Manual", "Oscillating Blade"],
        "aliases": ["grout saw", "grout removal tool"],
        "unit": "EA",
        "definition": "Tool that removes old grout.",
    },
    {
        "canonical": "Tile Removal Chisel",
        "suffixes": ["Standard"],
        "aliases": ["tile chisel", "chipping chisel"],
        "unit": "EA",
        "definition": "Chisel for removing old tile.",
    },
    {
        "canonical": "Scoring Knife",
        "suffixes": ["Standard"],
        "aliases": ["scoring knife", "carbide knife"],
        "unit": "EA",
        "definition": "Knife that scores tile and membranes.",
    },
    {
        "canonical": "Membrane Roller",
        "suffixes": ["Standard"],
        "aliases": ["membrane roller", "ditra roller"],
        "unit": "EA",
        "definition": "Roller that presses membranes into thinset.",
    },
]

