#!/usr/bin/env python3
"""Generate app/static/js/trade_lexicon.js from the seed definitions.

The artifact is a static, dependency-free JS dictionary that powers two
consumers:

  * voiceCanonical  -- curated spoken-form -> canonical-term map used by
    voice_normalizer.js to fix STT mishearings and slang ("silcock" ->
    "Hose Bibb", "greenboard" -> "Water-Resistant Gypsum Board"). Lives in
    app/seeds/lexicon/_voice_synonyms.py and is validated against the seed
    families on every build.
  * canonicalBySpoken + entries -- compact {term, trade, unit} index for the
    builder's client-side autocomplete cache. Full phonetics, aliases and
    definitions are served by /api/lexicon/search on demand.

Regenerate after editing app/seeds/lexicon/*:
    python3 scripts/build_voice_lexicon.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.seeds.lexicon._shared import _load_providers, build_rows  # noqa: E402


def _spoke_keys(row):
    keys = {row["term"].lower()}
    for a in row["aliases"] or []:
        keys.add(a.lower())
    for t in row["common_misspellings_typos"] or []:
        keys.add(t.lower())
    return keys


def build() -> dict:
    from app.seeds.lexicon._shared import generate_misspellings
    from app.seeds.lexicon._voice_synonyms import VOICE_SYNONYMS

    entries = []
    canonical_by_spoken = {}
    voice_canonical = {}

    # Validate every curated voice target is a real family canonical.
    known_canonicals = {
        fam["canonical"]
        for families, _ in _load_providers()
        for fam in families
    }
    missing = sorted(t for t in VOICE_SYNONYMS.values() if t not in known_canonicals)
    if missing:
        raise ValueError(
            "VOICE_SYNONYMS targets missing from seed families: %s" % missing
        )

    for spoken, canonical in VOICE_SYNONYMS.items():
        voice_canonical[spoken] = canonical

    for families, trade in _load_providers():
        for fam in families:
            fam_trade = fam.get("trade", trade)
            family_canonical = fam["canonical"]
            aliases = list(fam.get("aliases") or [])
            unit = fam.get("unit", "EA")

            # Family-level spoken index for the autocomplete cache (canonical
            # base name + explicit aliases + generated misspellings).
            keys = [family_canonical.lower()] + [a.lower() for a in aliases]
            keys += generate_misspellings(family_canonical, aliases)
            for key in keys:
                if key not in canonical_by_spoken:
                    canonical_by_spoken[key] = {
                        "term": family_canonical,
                        "trade": fam_trade,
                        "unit": unit,
                    }

            # Per-row entries for the autocomplete cache (compact: phonetics,
            # definitions and full aliases are served by /api/lexicon/search
            # on demand).
            for row in build_rows([fam], fam_trade):
                entry = {
                    "term": row["term"],
                    "trade": row["trade"],
                    "unit": row["default_unit"] or "EA",
                }
                entries.append(entry)
                for key in _spoke_keys(row):
                    canonical_by_spoken[key] = entry

    return {
        "generated": __import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
        "total": len(entries),
        "voiceCanonical": dict(sorted(voice_canonical.items(), key=lambda kv: -len(kv[0]))),
        "canonicalBySpoken": canonical_by_spoken,
        "entries": entries,
    }


def main() -> None:
    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "app", "static", "js", "trade_lexicon.js",
    )
    data = build()
    payload = json.dumps(data, ensure_ascii=False)
    js = (
        "/* Generated by scripts/build_voice_lexicon.py -- DO NOT EDIT.\n"
        " * Multi-trade lexicon for the voice STT normalizer and the builder's\n"
        " * client-side autocomplete cache. Regenerate with:\n"
        " *   python3 scripts/build_voice_lexicon.py\n"
        " */\n"
        "(function () {\n"
        "  'use strict';\n"
        "  var __lexicon = " + payload + ";\n"
        "  if (typeof window !== 'undefined') window.BQTradeLexicon = __lexicon;\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = __lexicon;\n"
        "})();\n"
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(js)
    print(f"Wrote {data['total']} entries to {out_path}")
    print(f"  voiceCanonical: {len(data['voiceCanonical'])} distinctive spoken forms")
    print(f"  canonicalBySpoken: {len(data['canonicalBySpoken'])} keys")


if __name__ == "__main__":
    main()
